# Initial build script generated by OpenAI Codex on 2026-06-29.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceDirectory = Join-Path $root 'src\WeChatMessageNotifier'
$launcherSourceDirectory = Join-Path $root 'src\WeChatNotifierLauncher'
$settingsUiProject = Join-Path $root 'src\WeChatMessageNotifier.WinUI\WeChatMessageNotifier.WinUI.csproj'
$outputDirectory = Join-Path $root 'outputs\WeChatMessageNotifier'
$output = Join-Path $outputDirectory 'WeChatMessageNotifier.exe'
$launcherOutput = Join-Path $outputDirectory 'WeChatNotifierLauncher.exe'
$settingsUiOutputDirectory = Join-Path $outputDirectory 'SettingsUi'
$compiler = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
$uiaClient = Join-Path $env:WINDIR 'Microsoft.NET\assembly\GAC_MSIL\UIAutomationClient\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationClient.dll'
$uiaTypes = Join-Path $env:WINDIR 'Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'
$windowsBase = Join-Path $env:WINDIR 'Microsoft.NET\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'
$windowsUi = Join-Path $env:WINDIR 'System32\WinMetadata\Windows.UI.winmd'
$windowsData = Join-Path $env:WINDIR 'System32\WinMetadata\Windows.Data.winmd'
$windowsFoundation = Join-Path $env:WINDIR 'System32\WinMetadata\Windows.Foundation.winmd'
$windowsRuntime = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\System.Runtime.WindowsRuntime.dll'
$systemRuntime = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\System.Runtime.dll'
$windowsRuntimeInterop = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\System.Runtime.InteropServices.WindowsRuntime.dll'
$manifest = Join-Path $sourceDirectory 'app.manifest'
$sources = Get-ChildItem -LiteralPath $sourceDirectory -Filter '*.cs' | Select-Object -ExpandProperty FullName
$launcherSources = Get-ChildItem -LiteralPath $launcherSourceDirectory -Filter '*.cs' | Select-Object -ExpandProperty FullName

New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null

& $compiler `
    /nologo `
    /target:winexe `
    /platform:anycpu `
    /optimize+ `
    /win32manifest:$manifest `
    /out:$output `
    /reference:System.dll `
    /reference:System.Core.dll `
    /reference:System.Drawing.dll `
    /reference:System.Windows.Forms.dll `
    /reference:$uiaClient `
    /reference:$uiaTypes `
    /reference:$windowsBase `
    /reference:$windowsUi `
    /reference:$windowsData `
    /reference:$windowsFoundation `
    /reference:$windowsRuntime `
    /reference:$systemRuntime `
    /reference:$windowsRuntimeInterop `
    $sources

if ($LASTEXITCODE -ne 0) {
    throw "Compilation failed with exit code $LASTEXITCODE."
}

& $compiler `
    /nologo `
    /target:winexe `
    /platform:anycpu `
    /optimize+ `
    /out:$launcherOutput `
    /reference:System.dll `
    /reference:System.Core.dll `
    /reference:System.Management.dll `
    $launcherSources

if ($LASTEXITCODE -ne 0) {
    throw "Launcher compilation failed with exit code $LASTEXITCODE."
}

# The modern settings surface is deliberately a separate WinUI 3 executable.
# It keeps the proven .NET Framework monitor and Windows-toast path untouched,
# while WindowsAppSDK supplies compositor-backed Mica and Per-Monitor-V2 DPI.
# Self-contained publish avoids a runtime-version dependency on the user's PC.
& dotnet publish $settingsUiProject `
    --configuration Release `
    --runtime win-x64 `
    --self-contained true `
    -p:PublishTrimmed=false `
    -p:WindowsAppSDKSelfContained=true `
    --output $settingsUiOutputDirectory `
    --nologo

if ($LASTEXITCODE -ne 0) {
    throw "WinUI settings publish failed with exit code $LASTEXITCODE."
}

Copy-Item -LiteralPath (Join-Path $root 'LICENSE') `
    -Destination (Join-Path $outputDirectory 'LICENSE') `
    -Force
Copy-Item -LiteralPath (Join-Path $root 'NOTICE.md') `
    -Destination (Join-Path $outputDirectory 'NOTICE.md') `
    -Force

Write-Output $output
Write-Output $launcherOutput
