// Local, redacted decision-history window generated by OpenAI Codex.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class ActivityLogForm : Win11BackdropForm
    {
        internal static bool UsesResponsiveLayout
        {
            get { return true; }
        }

        internal static bool HandlesPerMonitorDpiChanges
        {
            get { return true; }
        }

        internal static bool UsesStableNativeTextControls
        {
            get { return true; }
        }

        internal ActivityLogForm(IEnumerable<NotificationActivityRecord> records)
        {
            Text = "最近通知决策 · 微信消息提醒器";
            StartPosition = FormStartPosition.CenterParent;
            FormBorderStyle = FormBorderStyle.Sizable;
            MaximizeBox = true;
            MinimizeBox = true;
            SizeGripStyle = SizeGripStyle.Show;
            AutoScaleMode = AutoScaleMode.Dpi;
            MinimumSize = new Size(760, 480);
            ClientSize = new Size(860, 540);
            Win11Visual.ApplyWindowStyle(this);

            var root = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 1,
                RowCount = 3,
                Padding = new Padding(18),
                BackColor = Win11Visual.WindowBackground
            };
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 78));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48));
            Controls.Add(root);

            root.Controls.Add(CreateHeader(), 0, 0);

            var list = new ListView
            {
                Dock = DockStyle.Fill,
                View = View.Details,
                FullRowSelect = true,
                GridLines = true,
                HeaderStyle = ColumnHeaderStyle.Nonclickable,
                BackColor = Win11Visual.SolidCardBackground,
                ForeColor = Win11Visual.Title
            };
            list.Columns.Add("时间", 90);
            list.Columns.Add("识别类型", 105);
            list.Columns.Add("最终类型", 105);
            list.Columns.Add("结果", 70);
            list.Columns.Add("原因", 205);
            list.Columns.Add("会话哈希", 135);
            if (records != null)
            {
                foreach (var record in records)
                {
                    var item = new ListViewItem(record.Timestamp.ToString("HH:mm:ss"));
                    item.SubItems.Add(record.DetectedKind.ToString());
                    item.SubItems.Add(record.ResolvedKind.ToString());
                    item.SubItems.Add(record.ResultText);
                    item.SubItems.Add(record.Reason ?? string.Empty);
                    item.SubItems.Add(record.ContactHash ?? string.Empty);
                    list.Items.Add(item);
                }
            }
            root.Controls.Add(list, 0, 1);

            var buttons = new FlowLayoutPanel
            {
                Dock = DockStyle.Bottom,
                FlowDirection = FlowDirection.RightToLeft,
                WrapContents = false,
                AutoSize = true,
                Anchor = AnchorStyles.Right | AnchorStyles.Bottom,
                BackColor = Win11Visual.WindowBackground
            };
            var close = new Button
            {
                Text = "关闭",
                DialogResult = DialogResult.OK,
                Size = new Size(88, 32),
                Margin = new Padding(8, 8, 0, 0)
            };
            Win11Visual.StyleSecondaryButton(close);
            buttons.Controls.Add(close);
            root.Controls.Add(buttons, 0, 2);
            CancelButton = close;
        }

        protected override void OnDpiChanged(DpiChangedEventArgs eventArgs)
        {
            base.OnDpiChanged(eventArgs);
            if (eventArgs.SuggestedRectangle.Width > 0 &&
                eventArgs.SuggestedRectangle.Height > 0)
            {
                Bounds = eventArgs.SuggestedRectangle;
            }
            PerformLayout();
            Invalidate(true);
        }

        private Control CreateHeader()
        {
            var panel = new Panel
            {
                Dock = DockStyle.Fill,
                Margin = new Padding(0, 0, 0, 12),
                BackColor = Color.FromArgb(255, 244, 249, 247)
            };
            var title = new Label
            {
                Text = "最近通知决策",
                AutoSize = true,
                Location = new Point(14, 10),
                BackColor = panel.BackColor,
                ForeColor = Win11Visual.Title,
                Font = new Font(Font, FontStyle.Bold),
                UseCompatibleTextRendering = true
            };
            var hint = new Label
            {
                Text = "仅保留本次运行最近 30 条候选记录；不显示联系人名称或消息正文。",
                AutoSize = true,
                MaximumSize = new Size(760, 0),
                Location = new Point(16, 40),
                BackColor = panel.BackColor,
                ForeColor = Win11Visual.SecondaryText,
                UseCompatibleTextRendering = true
            };
            panel.Controls.Add(title);
            panel.Controls.Add(hint);
            return panel;
        }
    }
}
