// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("WeChat Message Notifier")]
[assembly: AssemblyDescription("Local Windows WeChat notification helper initially written by OpenAI Codex.")]
[assembly: AssemblyProduct("WeChat Message Notifier")]
[assembly: AssemblyCopyright("Initial implementation by OpenAI Codex, 2026")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.9.0.0")]
[assembly: AssemblyFileVersion("1.9.0.0")]
