// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

namespace WeChatMessageNotifier
{
    // Parsed, in-memory representation of a single visible WeChat session row.
    internal sealed class ChatSession
    {
        internal string Contact { get; set; }
        internal string Preview { get; set; }
        internal string Timestamp { get; set; }
        internal string Signature { get; set; }
        internal int UnreadCount { get; set; }
        internal int Position { get; set; }
    }
}
