// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.IO;
using System.Text;

namespace WeChatMessageNotifier
{
    internal sealed class Logger
    {
        // Callers intentionally log only operational metadata. Contact names
        // and message bodies must never be passed to this class.
        private readonly object sync = new object();
        private readonly string path;

        internal Logger()
        {
            var directory = System.IO.Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "WeChatMessageNotifier");
            Directory.CreateDirectory(directory);
            path = System.IO.Path.Combine(directory, "app.log");
        }

        internal string Path
        {
            get { return path; }
        }

        internal void Info(string message)
        {
            Write("INFO", message);
        }

        internal void Error(string message, Exception exception)
        {
            Write("ERROR", message + " | " + exception.GetType().Name + ": " + exception.Message);
        }

        private void Write(string level, string message)
        {
            lock (sync)
            {
                File.AppendAllText(
                    path,
                    DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff") + " [" + level + "] " + message + Environment.NewLine,
                    Encoding.UTF8);
            }
        }
    }
}
