// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Text;

namespace WeChatMessageNotifier
{
    internal static class NativeMethods
    {
        // This file contains the small Win32 surface required for window
        // discovery, activation, topmost placement, and occlusion detection.
        internal delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);

        internal const int SwRestore = 9;
        internal const int SwShow = 5;
        internal const int SwShowMaximized = 3;
        internal static readonly IntPtr HwndTopmost = new IntPtr(-1);
        internal const uint SwpNoSize = 0x0001;
        internal const uint SwpNoActivate = 0x0010;
        internal const uint SwpShowWindow = 0x0040;
        private const int GwlExStyle = -20;
        private const int WsExTopmost = 0x00000008;
        private const uint GaRoot = 2;

        [DllImport("user32.dll")]
        internal static extern bool EnumWindows(EnumWindowsProc callback, IntPtr lParam);

        [DllImport("user32.dll")]
        internal static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint processId);

        [DllImport("user32.dll")]
        internal static extern bool IsWindow(IntPtr hWnd);

        [DllImport("user32.dll")]
        internal static extern bool IsWindowVisible(IntPtr hWnd);

        [DllImport("user32.dll")]
        internal static extern bool IsIconic(IntPtr hWnd);

        [DllImport("user32.dll")]
        internal static extern bool IsZoomed(IntPtr hWnd);

        [DllImport("user32.dll")]
        internal static extern IntPtr GetForegroundWindow();

        [DllImport("user32.dll")]
        internal static extern bool ShowWindow(IntPtr hWnd, int command);

        [DllImport("user32.dll")]
        internal static extern bool SetForegroundWindow(IntPtr hWnd);

        [DllImport("user32.dll")]
        internal static extern bool SetWindowPos(
            IntPtr hWnd,
            IntPtr insertAfter,
            int x,
            int y,
            int width,
            int height,
            uint flags);

        [DllImport("user32.dll")]
        private static extern IntPtr WindowFromPoint(NativePoint point);

        [DllImport("user32.dll")]
        private static extern IntPtr GetAncestor(IntPtr hWnd, uint flags);

        [DllImport("user32.dll")]
        private static extern int GetWindowLong(IntPtr hWnd, int index);

        [DllImport("user32.dll")]
        private static extern bool GetWindowRect(IntPtr hWnd, out NativeRect rect);

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        internal static extern int GetClassName(IntPtr hWnd, StringBuilder className, int maxCount);

        internal static string ReadClassName(IntPtr hWnd)
        {
            var buffer = new StringBuilder(256);
            GetClassName(hWnd, buffer, buffer.Capacity);
            return buffer.ToString();
        }

        internal static bool TryGetExternalTopmostWindowAt(
            Point point,
            int currentProcessId,
            out Rectangle rectangle)
        {
            rectangle = Rectangle.Empty;
            // WindowFromPoint lets the notifier discover a QQ or Windows toast
            // that was placed above our persistent popup.
            var window = WindowFromPoint(new NativePoint { X = point.X, Y = point.Y });
            if (window == IntPtr.Zero)
            {
                return false;
            }

            var root = GetAncestor(window, GaRoot);
            if (root == IntPtr.Zero)
            {
                root = window;
            }

            uint processId;
            GetWindowThreadProcessId(root, out processId);
            if (processId == (uint)currentProcessId)
            {
                return false;
            }

            var extendedStyle = GetWindowLong(root, GwlExStyle);
            if ((extendedStyle & WsExTopmost) == 0)
            {
                return false;
            }

            NativeRect nativeRect;
            if (!GetWindowRect(root, out nativeRect))
            {
                return false;
            }

            rectangle = Rectangle.FromLTRB(
                nativeRect.Left,
                nativeRect.Top,
                nativeRect.Right,
                nativeRect.Bottom);
            return rectangle.Width > 0 && rectangle.Height > 0;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct NativePoint
        {
            internal int X;
            internal int Y;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct NativeRect
        {
            internal int Left;
            internal int Top;
            internal int Right;
            internal int Bottom;
        }
    }
}
