// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace WeChatMessageNotifier
{
    // Stores two deliberately separate session-level rules. Classification
    // overrides answer "what is this session?"; notification overrides answer
    // "should this particular session notify?". Neither stores names or text.
    internal sealed class NotificationFilterSettings
    {
        internal NotificationFilterSettings()
        {
            SessionKindOverrides = new Dictionary<string, ChatSessionKind>(
                StringComparer.OrdinalIgnoreCase);
            SessionNotificationOverrides =
                new Dictionary<string, SessionNotificationOverride>(
                    StringComparer.OrdinalIgnoreCase);
            ServiceAccountAllowKeywords = new List<string>();
            OfficialAccountAllowKeywords = new List<string>();
            GroupChatBlockKeywords = new List<string>();
        }

        internal IDictionary<string, ChatSessionKind> SessionKindOverrides
        {
            get;
            private set;
        }

        internal IDictionary<string, SessionNotificationOverride>
            SessionNotificationOverrides
        {
            get;
            private set;
        }

        // Service-account and official-account matches are keyword allowlists.
        internal IList<string> ServiceAccountAllowKeywords { get; private set; }

        internal IList<string> OfficialAccountAllowKeywords { get; private set; }

        internal IList<string> GroupChatBlockKeywords { get; private set; }

        // Stored with the filter settings because it controls how the same
        // locally generated Windows notifications expose message summaries.
        internal bool PrivacyMode { get; set; }

        // UI placement is local, non-sensitive state. Keeping it alongside
        // the existing local settings lets the resizable settings window
        // return to a usable size without storing any conversation data.
        internal Rectangle? SettingsWindowBounds { get; private set; }

        internal bool SettingsWindowMaximized { get; private set; }

        // Bounds are physical pixels, so retain the source DPI as well.
        // This lets a normal (non-maximized) window restore at an equivalent
        // logical size after it moves to a different-DPI display.
        internal int SettingsWindowDpi { get; private set; }

        internal void SetSettingsWindowPlacement(
            Rectangle bounds,
            bool maximized)
        {
            SetSettingsWindowPlacement(bounds, maximized, 96);
        }

        internal void SetSettingsWindowPlacement(
            Rectangle bounds,
            bool maximized,
            int dpi)
        {
            if (bounds.Width < 100 || bounds.Height < 100)
            {
                return;
            }

            SettingsWindowBounds = bounds;
            SettingsWindowMaximized = maximized;
            SettingsWindowDpi = dpi >= 96 && dpi <= 960 ? dpi : 96;
        }

        internal void CopySettingsWindowPlacementFrom(
            NotificationFilterSettings source)
        {
            if (source == null || !source.SettingsWindowBounds.HasValue)
            {
                return;
            }

            SetSettingsWindowPlacement(
                source.SettingsWindowBounds.Value,
                source.SettingsWindowMaximized,
                source.SettingsWindowDpi);
        }

        internal bool HasServiceAccountAllowKeyword(string preview)
        {
            return ContainsKeyword(ServiceAccountAllowKeywords, preview);
        }

        internal bool HasOfficialAccountAllowKeyword(string preview)
        {
            return ContainsKeyword(OfficialAccountAllowKeywords, preview);
        }

        internal bool HasGroupChatBlockKeyword(string contact)
        {
            return ContainsKeyword(GroupChatBlockKeywords, contact);
        }

        internal ChatSessionKind ResolveKind(
            string contactHash,
            ChatSessionKind detectedKind)
        {
            ChatSessionKind overridden;
            return TryGetByHash(SessionKindOverrides, contactHash, out overridden)
                ? overridden
                : detectedKind;
        }

        internal SessionNotificationOverride? ResolveNotificationOverride(
            string contactHash)
        {
            SessionNotificationOverride overridden;
            return TryGetByHash(
                SessionNotificationOverrides,
                contactHash,
                out overridden)
                ? (SessionNotificationOverride?)overridden
                : null;
        }

        internal void SetOverride(string contactHash, ChatSessionKind kind)
        {
            ValidateNewHash(contactHash);
            SessionKindOverrides[contactHash] = kind;
        }

        internal void SetNotificationOverride(
            string contactHash,
            SessionNotificationOverride notificationOverride)
        {
            ValidateNewHash(contactHash);
            SessionNotificationOverrides[contactHash] = notificationOverride;
        }

        internal bool ClearOverride(string contactHash)
        {
            return SessionKindOverrides.Remove(contactHash);
        }

        internal bool ClearNotificationOverride(string contactHash)
        {
            return SessionNotificationOverrides.Remove(contactHash);
        }

        internal void ApplyFrom(NotificationFilterSettings source)
        {
            SessionKindOverrides.Clear();
            foreach (var item in source.SessionKindOverrides)
            {
                SessionKindOverrides[item.Key] = item.Value;
            }

            SessionNotificationOverrides.Clear();
            foreach (var item in source.SessionNotificationOverrides)
            {
                SessionNotificationOverrides[item.Key] = item.Value;
            }

            CopyKeywords(source.ServiceAccountAllowKeywords, ServiceAccountAllowKeywords);
            CopyKeywords(source.OfficialAccountAllowKeywords, OfficialAccountAllowKeywords);
            CopyKeywords(source.GroupChatBlockKeywords, GroupChatBlockKeywords);
            PrivacyMode = source.PrivacyMode;
            SettingsWindowBounds = source.SettingsWindowBounds;
            SettingsWindowMaximized = source.SettingsWindowMaximized;
            SettingsWindowDpi = source.SettingsWindowDpi;
        }

        internal NotificationFilterSettings Clone()
        {
            var clone = new NotificationFilterSettings();
            clone.ApplyFrom(this);
            return clone;
        }

        internal string ToJson()
        {
            var builder = new StringBuilder();
            builder.AppendLine("{");
            AppendDictionary(builder, "sessionKindOverrides", SessionKindOverrides);
            builder.AppendLine(",");
            AppendDictionary(
                builder,
                "sessionNotificationOverrides",
                SessionNotificationOverrides);
            builder.AppendLine(",");
            AppendStringArray(
                builder,
                "serviceAccountAllowKeywords",
                ServiceAccountAllowKeywords);
            builder.AppendLine(",");
            AppendStringArray(
                builder,
                "officialAccountAllowKeywords",
                OfficialAccountAllowKeywords);
            builder.AppendLine(",");
            AppendStringArray(
                builder,
                "groupChatBlockKeywords",
                GroupChatBlockKeywords);
            builder.AppendLine(",");
            builder.Append("  \"privacyMode\": ");
            builder.AppendLine(PrivacyMode ? "true," : "false,");
            AppendSettingsWindowPlacement(builder);
            builder.AppendLine();
            builder.AppendLine("}");
            return builder.ToString();
        }

        internal static bool TryParse(
            string json,
            out NotificationFilterSettings settings)
        {
            settings = null;
            if (string.IsNullOrWhiteSpace(json)) return false;
            var trimmed = json.Trim();
            if (!trimmed.StartsWith("{", StringComparison.Ordinal) ||
                !trimmed.EndsWith("}", StringComparison.Ordinal)) return false;

            var parsed = new NotificationFilterSettings();
            bool privacyMode;
            if (!TryParseKinds(json, parsed) ||
                !TryParseNotificationOverrides(json, parsed) ||
                !TryParseKeywords(
                    json,
                    "serviceAccountAllowKeywords",
                    parsed.ServiceAccountAllowKeywords) ||
                !TryParseKeywords(
                    json,
                    "officialAccountAllowKeywords",
                    parsed.OfficialAccountAllowKeywords) ||
                !TryParseKeywords(
                    json,
                    "groupChatBlockKeywords",
                    parsed.GroupChatBlockKeywords) ||
                !TryParseBoolean(json, "privacyMode", out privacyMode) ||
                !TryParseSettingsWindowPlacement(json, parsed))
            {
                return false;
            }
            parsed.PrivacyMode = privacyMode;
            settings = parsed;
            return true;
        }

        private static bool TryParseSettingsWindowPlacement(
            string json,
            NotificationFilterSettings parsed)
        {
            var match = Regex.Match(
                json,
                "\\\"settingsWindow\\\"\\s*:\\s*\\{\\s*" +
                "\\\"x\\\"\\s*:\\s*(?<x>-?\\d+)\\s*,\\s*" +
                "\\\"y\\\"\\s*:\\s*(?<y>-?\\d+)\\s*,\\s*" +
                "\\\"width\\\"\\s*:\\s*(?<width>\\d+)\\s*,\\s*" +
                "\\\"height\\\"\\s*:\\s*(?<height>\\d+)\\s*,\\s*" +
                "\\\"maximized\\\"\\s*:\\s*(?<maximized>true|false)" +
                "(?:\\s*,\\s*\\\"dpi\\\"\\s*:\\s*(?<dpi>\\d+))?\\s*\\}",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant |
                RegexOptions.Singleline);
            if (!match.Success)
            {
                return json.IndexOf("\"settingsWindow\"", StringComparison.OrdinalIgnoreCase) < 0 ||
                    Regex.IsMatch(
                        json,
                        "\\\"settingsWindow\\\"\\s*:\\s*null",
                        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
            }

            int x;
            int y;
            int width;
            int height;
            int dpi;
            bool maximized;
            if (!int.TryParse(match.Groups["x"].Value, out x) ||
                !int.TryParse(match.Groups["y"].Value, out y) ||
                !int.TryParse(match.Groups["width"].Value, out width) ||
                !int.TryParse(match.Groups["height"].Value, out height) ||
                !bool.TryParse(match.Groups["maximized"].Value, out maximized) ||
                width < 100 || height < 100)
            {
                return false;
            }

            parsed.SetSettingsWindowPlacement(
                new Rectangle(x, y, width, height),
                maximized,
                int.TryParse(match.Groups["dpi"].Value, out dpi) ? dpi : 96);
            return true;
        }

        private static bool TryParseKinds(
            string json,
            NotificationFilterSettings parsed)
        {
            string body;
            if (!TryGetObjectBody(json, "sessionKindOverrides", out body))
            {
                return true;
            }

            var pairs = Regex.Matches(
                body,
                "\"(?<hash>[0-9a-fA-F]{8,64})\"\\s*:\\s*\"(?<kind>[A-Za-z]+)\"",
                RegexOptions.CultureInvariant);
            foreach (Match pair in pairs)
            {
                ChatSessionKind kind;
                if (Enum.TryParse(pair.Groups["kind"].Value, true, out kind) &&
                    Enum.IsDefined(typeof(ChatSessionKind), kind))
                {
                    // Eight-character keys are read for backward compatibility.
                    parsed.SessionKindOverrides[pair.Groups["hash"].Value] = kind;
                }
            }
            return true;
        }

        private static bool TryParseNotificationOverrides(
            string json,
            NotificationFilterSettings parsed)
        {
            string body;
            if (!TryGetObjectBody(json, "sessionNotificationOverrides", out body))
            {
                return true;
            }

            var pairs = Regex.Matches(
                body,
                "\"(?<hash>[0-9a-fA-F]{8,64})\"\\s*:\\s*\"(?<policy>[A-Za-z]+)\"",
                RegexOptions.CultureInvariant);
            foreach (Match pair in pairs)
            {
                SessionNotificationOverride notificationOverride;
                if (!Enum.TryParse(
                    pair.Groups["policy"].Value,
                    true,
                    out notificationOverride) ||
                    !Enum.IsDefined(
                        typeof(SessionNotificationOverride),
                        notificationOverride))
                {
                    return false;
                }
                parsed.SessionNotificationOverrides[pair.Groups["hash"].Value] =
                    notificationOverride;
            }
            return true;
        }

        private static bool TryGetObjectBody(
            string json,
            string propertyName,
            out string body)
        {
            var match = Regex.Match(
                json,
                "\"" + Regex.Escape(propertyName) +
                "\"\\s*:\\s*\\{(?<body>[^}]*)\\}",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant |
                RegexOptions.Singleline);
            body = match.Success ? match.Groups["body"].Value : null;
            return match.Success;
        }

        private static bool TryParseKeywords(
            string json,
            string propertyName,
            IList<string> destination)
        {
            var match = Regex.Match(
                json,
                "\"" + Regex.Escape(propertyName) +
                "\"\\s*:\\s*\\[(?<body>[^]]*)\\]",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant |
                RegexOptions.Singleline);
            if (!match.Success)
            {
                // Missing keyword settings are valid for existing files.
                return json.IndexOf("\"" + propertyName + "\"", StringComparison.OrdinalIgnoreCase) < 0;
            }

            var values = Regex.Matches(
                match.Groups["body"].Value,
                "\"(?<value>(?:\\\\.|[^\"])*)\"",
                RegexOptions.CultureInvariant);
            foreach (Match value in values)
            {
                AddKeyword(destination, UnescapeJson(value.Groups["value"].Value));
            }
            return true;
        }

        private static bool TryParseBoolean(
            string json,
            string propertyName,
            out bool value)
        {
            value = false;
            var match = Regex.Match(
                json,
                "\"" + Regex.Escape(propertyName) + "\"\\s*:\\s*(?<value>true|false)",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
            if (match.Success)
            {
                return bool.TryParse(match.Groups["value"].Value, out value);
            }

            // Older settings files legitimately have no privacy field.
            return json.IndexOf("\"" + propertyName + "\"", StringComparison.OrdinalIgnoreCase) < 0;
        }

        private static void AppendDictionary<TValue>(
            StringBuilder builder,
            string propertyName,
            IDictionary<string, TValue> source)
        {
            builder.Append("  \"");
            builder.Append(propertyName);
            builder.AppendLine("\": {");
            var values = source.OrderBy(
                delegate(KeyValuePair<string, TValue> item) { return item.Key; },
                StringComparer.OrdinalIgnoreCase).ToArray();
            for (var index = 0; index < values.Length; index++)
            {
                builder.Append("    \"");
                builder.Append(values[index].Key.ToLowerInvariant());
                builder.Append("\": \"");
                builder.Append(values[index].Value);
                builder.Append("\"");
                builder.AppendLine(index + 1 < values.Length ? "," : string.Empty);
            }
            builder.Append("  }");
        }

        private static void AppendStringArray(
            StringBuilder builder,
            string propertyName,
            IEnumerable<string> values)
        {
            builder.Append("  \"");
            builder.Append(propertyName);
            builder.AppendLine("\": [");
            var normalized = values
                .Where(delegate(string value) { return !string.IsNullOrWhiteSpace(value); })
                .Select(delegate(string value) { return value.Trim(); })
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(delegate(string value) { return value; }, StringComparer.OrdinalIgnoreCase)
                .ToArray();
            for (var index = 0; index < normalized.Length; index++)
            {
                builder.Append("    \"");
                builder.Append(EscapeJson(normalized[index]));
                builder.Append("\"");
                builder.AppendLine(index + 1 < normalized.Length ? "," : string.Empty);
            }
            builder.Append("  ]");
        }

        private void AppendSettingsWindowPlacement(StringBuilder builder)
        {
            if (!SettingsWindowBounds.HasValue)
            {
                builder.AppendLine("  \"settingsWindow\": null");
                return;
            }

            var bounds = SettingsWindowBounds.Value;
            builder.AppendLine("  \"settingsWindow\": {");
            builder.AppendLine("    \"x\": " + bounds.X + ",");
            builder.AppendLine("    \"y\": " + bounds.Y + ",");
            builder.AppendLine("    \"width\": " + bounds.Width + ",");
            builder.AppendLine("    \"height\": " + bounds.Height + ",");
            builder.AppendLine(
                "    \"maximized\": " +
                (SettingsWindowMaximized ? "true," : "false,"));
            builder.AppendLine("    \"dpi\": " +
                (SettingsWindowDpi >= 96 ? SettingsWindowDpi : 96));
            builder.AppendLine("  }");
        }

        private static bool ContainsKeyword(
            IEnumerable<string> keywords,
            string preview)
        {
            if (string.IsNullOrEmpty(preview)) return false;
            foreach (var keyword in keywords)
            {
                if (!string.IsNullOrWhiteSpace(keyword) &&
                    preview.IndexOf(keyword.Trim(), StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }
            return false;
        }

        private static void CopyKeywords(
            IEnumerable<string> source,
            IList<string> destination)
        {
            destination.Clear();
            foreach (var value in source)
            {
                AddKeyword(destination, value);
            }
        }

        private static void AddKeyword(IList<string> destination, string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return;
            var trimmed = value.Trim();
            foreach (var existing in destination)
            {
                if (string.Equals(existing, trimmed, StringComparison.OrdinalIgnoreCase)) return;
            }
            destination.Add(trimmed);
        }

        private static string EscapeJson(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string UnescapeJson(string value)
        {
            return value.Replace("\\\"", "\"").Replace("\\\\", "\\");
        }

        private static bool TryGetByHash<TValue>(
            IDictionary<string, TValue> source,
            string contactHash,
            out TValue value)
        {
            if (!string.IsNullOrWhiteSpace(contactHash) &&
                source.TryGetValue(contactHash, out value))
            {
                return true;
            }

            // Older settings used 32-bit hashes. Read these keys only as a
            // compatibility fallback; newly created entries require 16 hex.
            if (!string.IsNullOrWhiteSpace(contactHash) &&
                contactHash.Length >= 16 &&
                source.TryGetValue(contactHash.Substring(0, 8), out value))
            {
                return true;
            }

            value = default(TValue);
            return false;
        }

        private static void ValidateNewHash(string value)
        {
            if (string.IsNullOrWhiteSpace(value) || !Regex.IsMatch(
                value,
                "^[0-9a-fA-F]{16,64}$",
                RegexOptions.CultureInvariant))
            {
                throw new ArgumentException(
                    "Contact hash must contain 16 to 64 hexadecimal characters.",
                    "contactHash");
            }
        }
    }
}
