// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using EventWaitHandle = System.Threading.EventWaitHandle;

namespace WeChatMessageNotifier
{
    internal sealed class NotifierApplicationContext : ApplicationContext
    {
        // The tray application owns all timers and UI objects on one STA thread,
        // avoiding cross-thread access to WinForms and UI Automation objects.
        private readonly Logger logger;
        private readonly WeChatMonitor monitor;
        private readonly PopupManager popupManager;
        private readonly WindowsNotificationCenter notificationCenter;
        private readonly NotifyIcon trayIcon;
        private readonly Timer pollTimer;
        private readonly Timer activationTimer;
        private readonly EventWaitHandle activationEvent;
        private readonly ToolStripMenuItem pauseItem;
        private readonly ToolStripMenuItem privacyItem;
        private bool paused;
        private bool privacyMode;
        private bool suppressWhenWeChatForeground;

        internal NotifierApplicationContext(
            string[] args,
            EventWaitHandle activationEvent)
        {
            this.activationEvent = activationEvent;
            logger = new Logger();
            monitor = new WeChatMonitor(logger);
            popupManager = new PopupManager(monitor.ActivateWeChat);
            notificationCenter = new WindowsNotificationCenter(
                monitor.ActivateWeChat,
                logger);

            privacyMode = HasArgument(args, "--privacy");
            // A notification click brings WeChat to the foreground. Suppressing
            // every later message in that state can hide messages from other
            // conversations, so foreground notifications are enabled by
            // default. The opt-in switch preserves the quieter old behavior.
            suppressWhenWeChatForeground =
                HasArgument(args, "--suppress-foreground") &&
                !HasArgument(args, "--notify-foreground");

            pauseItem = new ToolStripMenuItem("暂停监控");
            pauseItem.Click += delegate
            {
                paused = !paused;
                pauseItem.Text = paused ? "继续监控" : "暂停监控";
                trayIcon.Text = paused ? "微信消息提醒器（已暂停）" : "微信消息提醒器";
            };

            privacyItem = new ToolStripMenuItem("隐私模式（仅显示联系人）")
            {
                Checked = privacyMode,
                CheckOnClick = true
            };
            privacyItem.CheckedChanged += delegate { privacyMode = privacyItem.Checked; };

            var testItem = new ToolStripMenuItem("发送测试通知");
            testItem.Click += delegate
            {
                var popupShown = true;
                try
                {
                    popupManager.Show(
                        "微信消息提醒器",
                        "测试成功：消息弹窗与通知中心工作正常。");
                }
                catch (Exception exception)
                {
                    popupShown = false;
                    logger.Error("Test popup failed", exception);
                }
                notificationCenter.Show(
                    "微信消息提醒器",
                    "测试成功：消息弹窗与通知中心工作正常。",
                    popupShown);
            };

            var logItem = new ToolStripMenuItem("打开日志");
            logItem.Click += delegate
            {
                try
                {
                    Process.Start("explorer.exe", "/select,\"" + logger.Path + "\"");
                }
                catch (Exception exception)
                {
                    logger.Error("Could not open log file", exception);
                }
            };

            var exitItem = new ToolStripMenuItem("退出");
            exitItem.Click += delegate { Exit(); };

            var menu = new ContextMenuStrip();
            menu.Items.Add(pauseItem);
            menu.Items.Add(privacyItem);
            menu.Items.Add(new ToolStripSeparator());
            menu.Items.Add(testItem);
            menu.Items.Add(logItem);
            menu.Items.Add(new ToolStripSeparator());
            menu.Items.Add(exitItem);

            trayIcon = new NotifyIcon
            {
                Icon = SystemIcons.Information,
                Text = "微信消息提醒器",
                Visible = true,
                ContextMenuStrip = menu
            };
            trayIcon.DoubleClick += delegate { popupManager.Show("微信消息提醒器", "程序正在监控微信会话列表。"); };

            pollTimer = new Timer { Interval = 1500 };
            pollTimer.Tick += Poll;
            pollTimer.Start();

            activationTimer = new Timer { Interval = 200 };
            activationTimer.Tick += delegate
            {
                if (this.activationEvent.WaitOne(0))
                {
                    logger.Info("Notification center entry activated.");
                    monitor.ActivateWeChat();
                }
            };
            activationTimer.Start();

            logger.Info("Application started. Message content is not written to the log.");
            popupManager.Show("微信消息提醒器", "已启动，本地监控微信新消息。");
        }

        private void Poll(object sender, EventArgs eventArgs)
        {
            if (paused)
            {
                return;
            }

            var changes = monitor.Poll();
            if (changes.Count == 0)
            {
                return;
            }

            // Avoid repeating a message the user can already see in WeChat.
            if (suppressWhenWeChatForeground && monitor.IsWeChatForeground())
            {
                logger.Info("Suppressed " + changes.Count + " notification(s) while WeChat was foreground.");
                return;
            }

            foreach (var session in changes)
            {
                var body = privacyMode ? "收到一条新消息" : Limit(session.Preview, 180);
                var title = Limit(session.Contact, 80);
                var popupShown = true;
                try
                {
                    // Keep the full contact name as the popup's navigation key.
                    // The label already truncates visually when necessary.
                    popupManager.Show(session.Contact, body);
                }
                catch (Exception exception)
                {
                    popupShown = false;
                    logger.Error("Custom notification popup failed", exception);
                }
                // Normally this is a silent history entry. If the custom
                // popup fails, Windows displays its own banner as a fallback.
                notificationCenter.Show(title, body, popupShown);
                logger.Info(
                    "Notification shown. ContactLength=" + session.Contact.Length +
                    " PreviewLength=" + session.Preview.Length);
            }
        }

        private void Exit()
        {
            pollTimer.Stop();
            activationTimer.Stop();
            popupManager.CloseAll();
            trayIcon.Visible = false;
            trayIcon.Dispose();
            pollTimer.Dispose();
            activationTimer.Dispose();
            logger.Info("Application exited.");
            ExitThread();
        }

        private static bool HasArgument(string[] args, string expected)
        {
            foreach (var value in args)
            {
                if (string.Equals(value, expected, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        private static string Limit(string value, int maximum)
        {
            if (string.IsNullOrEmpty(value) || value.Length <= maximum)
            {
                return value;
            }
            return value.Substring(0, maximum - 1) + "…";
        }
    }
}
