// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

namespace WeChatMessageNotifier
{
    internal sealed class NotificationDecision
    {
        internal bool ShouldDeliver { get; set; }
        internal ChatSessionKind ResolvedKind { get; set; }
        internal SessionNotificationOverride? NotificationOverride { get; set; }
        internal string DefaultPolicy { get; set; }
        internal string Reason { get; set; }
    }
}
