// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace WeChatMessageNotifier
{
    internal sealed class NotificationFilterSettings
    {
        private static readonly ChatSessionKind[] AllKinds =
        {
            ChatSessionKind.DirectContact,
            ChatSessionKind.OfficialAccount,
            ChatSessionKind.ServiceAccount,
            ChatSessionKind.GroupChat,
            ChatSessionKind.MutedGroupChat,
            ChatSessionKind.Unknown
        };

        internal NotificationFilterSettings()
        {
            DirectContact = true;
            OfficialAccount = true;
            ServiceAccount = true;
            GroupChat = true;
            MutedGroupChat = true;
            Unknown = true;
            NotificationDisplayMode = NotificationDisplayMode.WindowsToast;
            MotionMode = MotionMode.Standard;
            PopupVisualMode = PopupVisualMode.Glass;
            SessionKindOverrides =
                new Dictionary<string, ChatSessionKind>(
                    StringComparer.OrdinalIgnoreCase);
        }

        internal bool DirectContact { get; set; }

        internal bool OfficialAccount { get; set; }

        internal bool ServiceAccount { get; set; }

        internal bool GroupChat { get; set; }

        internal bool MutedGroupChat { get; set; }

        internal bool Unknown { get; set; }

        internal NotificationDisplayMode NotificationDisplayMode { get; set; }

        internal MotionMode MotionMode { get; set; }

        internal PopupVisualMode PopupVisualMode { get; set; }

        internal IDictionary<string, ChatSessionKind> SessionKindOverrides
        {
            get;
            private set;
        }

        internal bool IsEnabled(ChatSessionKind kind)
        {
            switch (kind)
            {
                case ChatSessionKind.DirectContact:
                    return DirectContact;
                case ChatSessionKind.OfficialAccount:
                    return OfficialAccount;
                case ChatSessionKind.ServiceAccount:
                    return ServiceAccount;
                case ChatSessionKind.GroupChat:
                    return GroupChat;
                case ChatSessionKind.MutedGroupChat:
                    return MutedGroupChat;
                default:
                    return Unknown;
            }
        }

        internal void SetEnabled(ChatSessionKind kind, bool enabled)
        {
            switch (kind)
            {
                case ChatSessionKind.DirectContact:
                    DirectContact = enabled;
                    break;
                case ChatSessionKind.OfficialAccount:
                    OfficialAccount = enabled;
                    break;
                case ChatSessionKind.ServiceAccount:
                    ServiceAccount = enabled;
                    break;
                case ChatSessionKind.GroupChat:
                    GroupChat = enabled;
                    break;
                case ChatSessionKind.MutedGroupChat:
                    MutedGroupChat = enabled;
                    break;
                default:
                    Unknown = enabled;
                    break;
            }
        }

        internal ChatSessionKind ResolveKind(
            string contactHash,
            ChatSessionKind detectedKind)
        {
            ChatSessionKind overridden;
            return !string.IsNullOrWhiteSpace(contactHash) &&
                   SessionKindOverrides.TryGetValue(
                       contactHash,
                       out overridden)
                ? overridden
                : detectedKind;
        }

        internal void SetOverride(
            string contactHash,
            ChatSessionKind kind)
        {
            if (!IsValidHash(contactHash))
            {
                throw new ArgumentException(
                    "Contact hash must contain 8 to 64 hexadecimal characters.",
                    "contactHash");
            }
            SessionKindOverrides[contactHash] = kind;
        }

        internal bool ClearOverride(string contactHash)
        {
            return SessionKindOverrides.Remove(contactHash);
        }

        internal void ApplyFrom(NotificationFilterSettings source)
        {
            DirectContact = source.DirectContact;
            OfficialAccount = source.OfficialAccount;
            ServiceAccount = source.ServiceAccount;
            GroupChat = source.GroupChat;
            MutedGroupChat = source.MutedGroupChat;
            Unknown = source.Unknown;
            NotificationDisplayMode = source.NotificationDisplayMode;
            MotionMode = source.MotionMode;
            PopupVisualMode = source.PopupVisualMode;
            SessionKindOverrides.Clear();
            foreach (var item in source.SessionKindOverrides)
            {
                SessionKindOverrides[item.Key] = item.Value;
            }
        }

        internal string ToJson()
        {
            var builder = new StringBuilder();
            builder.AppendLine("{");
            for (var index = 0; index < AllKinds.Length; index++)
            {
                var kind = AllKinds[index];
                builder.Append("  \"");
                builder.Append(GetPropertyName(kind));
                builder.Append("\": ");
                builder.Append(IsEnabled(kind) ? "true" : "false");
                builder.AppendLine(",");
            }

            builder.Append("  \"notificationDisplayMode\": \"");
            builder.Append(NotificationDisplayMode);
            builder.AppendLine("\",");
            builder.Append("  \"motionMode\": \"");
            builder.Append(MotionMode);
            builder.AppendLine("\",");
            builder.Append("  \"popupVisualMode\": \"");
            builder.Append(PopupVisualMode);
            builder.AppendLine("\",");
            builder.AppendLine("  \"sessionKindOverrides\": {");
            var overrides = SessionKindOverrides
                .OrderBy(
                    delegate(KeyValuePair<string, ChatSessionKind> item)
                    {
                        return item.Key;
                    },
                    StringComparer.OrdinalIgnoreCase)
                .ToArray();
            for (var index = 0; index < overrides.Length; index++)
            {
                builder.Append("    \"");
                builder.Append(overrides[index].Key.ToLowerInvariant());
                builder.Append("\": \"");
                builder.Append(overrides[index].Value);
                builder.Append("\"");
                builder.AppendLine(
                    index + 1 < overrides.Length ? "," : string.Empty);
            }
            builder.AppendLine("  }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        internal static bool TryParse(
            string json,
            out NotificationFilterSettings settings)
        {
            settings = null;
            if (string.IsNullOrWhiteSpace(json))
            {
                return false;
            }

            var trimmed = json.Trim();
            if (!trimmed.StartsWith("{", StringComparison.Ordinal) ||
                !trimmed.EndsWith("}", StringComparison.Ordinal))
            {
                return false;
            }

            var parsed = new NotificationFilterSettings();
            foreach (var kind in AllKinds)
            {
                Match match;
                if (!TryMatchBoolean(
                    json,
                    GetPropertyName(kind),
                    out match) &&
                    !TryMatchBoolean(
                        json,
                        kind.ToString(),
                        out match))
                {
                    return false;
                }

                parsed.SetEnabled(
                    kind,
                    string.Equals(
                        match.Groups[1].Value,
                        "true",
                        StringComparison.OrdinalIgnoreCase));
            }

            var displayMatch = Regex.Match(
                json,
                "\"notificationDisplayMode\"\\s*:\\s*\"(?<mode>[A-Za-z]+)\"",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant);
            if (displayMatch.Success)
            {
                NotificationDisplayMode mode;
                if (!Enum.TryParse(
                        displayMatch.Groups["mode"].Value,
                        true,
                        out mode) ||
                    !Enum.IsDefined(typeof(NotificationDisplayMode), mode))
                {
                    return false;
                }
                parsed.NotificationDisplayMode = mode;
            }

            var motionMatch = Regex.Match(
                json,
                "\"motionMode\"\\s*:\\s*\"(?<mode>[A-Za-z]+)\"",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant);
            if (motionMatch.Success)
            {
                MotionMode mode;
                if (!Enum.TryParse(
                        motionMatch.Groups["mode"].Value,
                        true,
                        out mode) ||
                    !Enum.IsDefined(typeof(MotionMode), mode))
                {
                    return false;
                }
                parsed.MotionMode = mode;
            }

            var visualMatch = Regex.Match(
                json,
                "\"popupVisualMode\"\\s*:\\s*\"(?<mode>[A-Za-z]+)\"",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant);
            if (visualMatch.Success)
            {
                PopupVisualMode mode;
                if (!Enum.TryParse(
                        visualMatch.Groups["mode"].Value,
                        true,
                        out mode) ||
                    !Enum.IsDefined(typeof(PopupVisualMode), mode))
                {
                    return false;
                }
                parsed.PopupVisualMode = mode;
            }

            var overridesMatch = Regex.Match(
                json,
                "\"sessionKindOverrides\"\\s*:\\s*\\{(?<body>[^}]*)\\}",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant |
                RegexOptions.Singleline);
            if (overridesMatch.Success)
            {
                var pairMatches = Regex.Matches(
                    overridesMatch.Groups["body"].Value,
                    "\"(?<hash>[0-9a-fA-F]{8,64})\"\\s*:\\s*\"(?<kind>[A-Za-z]+)\"",
                    RegexOptions.CultureInvariant);
                foreach (Match pair in pairMatches)
                {
                    ChatSessionKind kind;
                    if (!Enum.TryParse(
                            pair.Groups["kind"].Value,
                            true,
                            out kind) ||
                        !Enum.IsDefined(typeof(ChatSessionKind), kind))
                    {
                        return false;
                    }
                    parsed.SetOverride(pair.Groups["hash"].Value, kind);
                }
            }

            settings = parsed;
            return true;
        }

        private static bool TryMatchBoolean(
            string json,
            string propertyName,
            out Match match)
        {
            match = Regex.Match(
                json,
                "\"" + Regex.Escape(propertyName) +
                "\"\\s*:\\s*(true|false)",
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant);
            return match.Success;
        }

        private static string GetPropertyName(ChatSessionKind kind)
        {
            switch (kind)
            {
                case ChatSessionKind.DirectContact:
                    return "enableDirectContact";
                case ChatSessionKind.OfficialAccount:
                    return "enableOfficialAccount";
                case ChatSessionKind.ServiceAccount:
                    return "enableServiceAccount";
                case ChatSessionKind.GroupChat:
                    return "enableGroupChat";
                case ChatSessionKind.MutedGroupChat:
                    return "enableMutedGroupChat";
                default:
                    return "enableUnknown";
            }
        }

        private static bool IsValidHash(string value)
        {
            return !string.IsNullOrWhiteSpace(value) &&
                   Regex.IsMatch(
                       value,
                       "^[0-9a-fA-F]{8,64}$",
                       RegexOptions.CultureInvariant);
        }
    }
}
