// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using EventWaitHandle = System.Threading.EventWaitHandle;

namespace WeChatMessageNotifier
{
    internal sealed class NotifierApplicationContext : ApplicationContext
    {
        internal const string WindowsNotificationDurationSettingsUri =
            "ms-settings:easeofaccess-visualeffects";

        // The tray application owns all timers and UI objects on one STA thread,
        // avoiding cross-thread access to WinForms and UI Automation objects.
        private readonly Logger logger;
        private readonly WeChatMonitor monitor;
        private readonly WindowsNotificationCenter notificationCenter;
        private readonly NotifyIcon trayIcon;
        private readonly Timer pollTimer;
        private readonly Timer activationTimer;
        private readonly EventWaitHandle activationEvent;
        private readonly ToolStripMenuItem pauseItem;
        private readonly ToolStripMenuItem privacyItem;
        private readonly ToolStripMenuItem diagnosticNextItem;
        private readonly ToolStripMenuItem diagnosticWeChatWindowsItem;
        private readonly NotificationFilterSettings notificationFilters;
        private readonly SettingsStore settingsStore;
        private bool paused;
        private bool privacyMode;
        private bool suppressWhenWeChatForeground;
        private ToastActivationRequest pendingActivationRequest;

        internal NotifierApplicationContext(
            string[] args,
            EventWaitHandle activationEvent)
        {
            this.activationEvent = activationEvent;
            logger = new Logger();
            settingsStore = new SettingsStore(logger);
            notificationFilters = settingsStore.Load();
            // Persist the active schema once so legacy popup/motion fields and
            // retired type switches disappear without touching hash-only rules.
            settingsStore.Save(notificationFilters);
            monitor = new WeChatMonitor(logger);
            notificationCenter = new WindowsNotificationCenter(
                HandleToastActivation,
                logger);
            pendingActivationRequest =
                Program.ExtractToastActivationRequest(args) ??
                Program.ReadActivationPayload();

            privacyMode = HasArgument(args, "--privacy");
            // A notification click brings WeChat to the foreground. Suppressing
            // every later message in that state can hide messages from other
            // conversations, so foreground notifications are enabled by
            // default. The opt-in switch preserves the quieter old behavior.
            suppressWhenWeChatForeground =
                HasArgument(args, "--suppress-foreground") &&
                !HasArgument(args, "--notify-foreground");

            pauseItem = new ToolStripMenuItem("暂停监控");
            pauseItem.Click += delegate
            {
                paused = !paused;
                pauseItem.Text = paused ? "继续监控" : "暂停监控";
                trayIcon.Text = paused ? "微信消息提醒器（已暂停）" : "微信消息提醒器";
            };

            privacyItem = new ToolStripMenuItem("隐私模式（仅显示联系人）")
            {
                Checked = privacyMode,
                CheckOnClick = true
            };
            privacyItem.CheckedChanged += delegate
            {
                privacyMode = privacyItem.Checked;
            };

            var testItem = new ToolStripMenuItem("发送测试通知");
            testItem.Click += delegate
            {
                notificationCenter.Show(
                    "微信消息提醒器",
                    "测试成功：Windows 系统通知工作正常。",
                    false);
            };

            var notificationDurationSettingsItem =
                new ToolStripMenuItem("打开 Windows 通知时长设置");
            notificationDurationSettingsItem.Click += delegate
            {
                OpenWindowsNotificationDurationSettings();
            };

            var logItem = new ToolStripMenuItem("打开日志");
            logItem.Click += delegate
            {
                try
                {
                    Process.Start("explorer.exe", "/select,\"" + logger.Path + "\"");
                }
                catch (Exception exception)
                {
                    logger.Error("Could not open log file", exception);
                }
            };

            diagnosticNextItem = new ToolStripMenuItem(
                "\u4E0B\u4E00\u6B21\u63D0\u9192\u663E\u793A\u5206\u7C7B")
            {
                CheckOnClick = true
            };

            diagnosticWeChatWindowsItem = new ToolStripMenuItem(
                "\u8BB0\u5F55\u5FAE\u4FE1\u7A97\u53E3\u7ED3\u6784");
            diagnosticWeChatWindowsItem.Click += delegate { monitor.LogWindowStructure(); };
            var settingsItem = new ToolStripMenuItem(
                "\u6253\u5F00\u8BBE\u7F6E\u6587\u4EF6");
            settingsItem.Click += delegate
            {
                try
                {
                    settingsStore.Save(notificationFilters);
                    Process.Start(
                        "notepad.exe",
                        "\"" + settingsStore.Path + "\"");
                }
                catch (Exception exception)
                {
                    logger.Error("Could not open settings file", exception);
                }
            };

            var diagnosticItem = new ToolStripMenuItem("\u8BCA\u65AD");
            diagnosticItem.DropDownItems.Add(diagnosticNextItem);
            diagnosticItem.DropDownItems.Add(diagnosticWeChatWindowsItem);
            diagnosticItem.DropDownItems.Add(settingsItem);
            diagnosticItem.DropDownItems.Add(logItem);

            var exitItem = new ToolStripMenuItem("退出");
            exitItem.Click += delegate { Exit(); };

            var menu = new ContextMenuStrip();
            menu.Items.Add(pauseItem);
            menu.Items.Add(privacyItem);
            menu.Items.Add(diagnosticItem);
            menu.Items.Add(new ToolStripSeparator());
            menu.Items.Add(testItem);
            menu.Items.Add(notificationDurationSettingsItem);
            menu.Items.Add(new ToolStripSeparator());
            menu.Items.Add(exitItem);

            trayIcon = new NotifyIcon
            {
                Icon = SystemIcons.Information,
                Text = "微信消息提醒器",
                Visible = true,
                ContextMenuStrip = menu
            };
            trayIcon.DoubleClick += delegate
            {
                notificationCenter.Show(
                    "微信消息提醒器",
                    "程序正在监控微信会话列表。",
                    false);
            };

            pollTimer = new Timer { Interval = 1500 };
            pollTimer.Tick += Poll;
            pollTimer.Start();

            activationTimer = new Timer { Interval = 200 };
            activationTimer.Tick += delegate
            {
                if (this.activationEvent.WaitOne(0))
                {
                    logger.Info("Notification center entry activated.");
                    var request =
                        Program.ReadActivationPayload() ??
                        pendingActivationRequest;
                    pendingActivationRequest = null;
                    HandleToastActivation(request);
                }
            };
            activationTimer.Start();

            logger.Info("Application started. Message content is not written to the log.");
            logger.Info("Notification delivery uses Windows system notifications only.");
        }

        private void Poll(object sender, EventArgs eventArgs)
        {
            if (paused)
            {
                return;
            }

            settingsStore.ReloadIfChanged(notificationFilters);
            var changes = monitor.Poll();
            if (changes.Count == 0)
            {
                return;
            }

            // Avoid repeating a message the user can already see in WeChat.
            if (suppressWhenWeChatForeground && monitor.IsWeChatForeground())
            {
                logger.Info("Suppressed " + changes.Count + " notification(s) while WeChat was foreground.");
                return;
            }

            foreach (var session in changes)
            {
                var decision = EvaluateNotification(
                    notificationFilters,
                    session);
                session.Kind = decision.ResolvedKind;
                if (diagnosticNextItem.Checked)
                {
                    LogCandidateDiagnostic(
                        session,
                        decision);
                    diagnosticNextItem.Checked = false;
                }

                if (!decision.ShouldDeliver)
                {
                    logger.Info(
                        "Notification filtered. ContactHash=" +
                        session.ContactHash +
                        " DetectedKind=" +
                        session.DetectedKind +
                        " ResolvedKind=" +
                        session.Kind +
                        " Reason=" +
                        decision.Reason +
                        " Count=1");
                    continue;
                }

                var preview = Limit(session.Preview, 180);
                var title = Limit(session.Contact, 80);
                var contactMessageCount = notificationCenter.ShowMessage(
                    session.SessionKey,
                    session.Kind,
                    title,
                    preview,
                    privacyMode,
                    false);
                logger.Info(
                    "Notification shown. ContactLength=" + session.Contact.Length +
                    " PreviewLength=" + session.Preview.Length +
                    " ContactMessageCount=" + contactMessageCount);
            }
        }

        private void HandleToastActivation(ToastActivationRequest request)
        {
            if (request == null || string.IsNullOrWhiteSpace(request.SessionKey))
            {
                monitor.ActivateWeChat(request);
                return;
            }

            // Clear only after UIA confirms that WeChat selected the intended
            // conversation. Failed navigation must leave the notification in
            // place rather than making unread messages disappear.
            if (monitor.ActivateWeChat(request))
            {
                notificationCenter.ClearSession(request.SessionKey);
            }
        }

        private void Exit()
        {
            pollTimer.Stop();
            activationTimer.Stop();
            notificationCenter.Dispose();
            trayIcon.Visible = false;
            trayIcon.Dispose();
            pollTimer.Dispose();
            activationTimer.Dispose();
            logger.Info("Application exited.");
            ExitThread();
        }

        private void OpenWindowsNotificationDurationSettings()
        {
            try
            {
                Process.Start(
                    "explorer.exe",
                    WindowsNotificationDurationSettingsUri);
                logger.Info("Opened Windows notification duration settings.");
            }
            catch (Exception exception)
            {
                logger.Error(
                    "Could not open Windows notification duration settings",
                    exception);
            }
        }

        private static bool HasArgument(string[] args, string expected)
        {
            foreach (var value in args)
            {
                if (string.Equals(value, expected, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        internal static bool ShouldDeliverNotification(
            NotificationFilterSettings settings,
            ChatSession session)
        {
            return EvaluateNotification(settings, session).ShouldDeliver;
        }

        internal static NotificationDecision EvaluateNotification(
            NotificationFilterSettings settings,
            ChatSession session)
        {
            var decision = new NotificationDecision
            {
                ShouldDeliver = false,
                ResolvedKind = ChatSessionKind.Unknown,
                DefaultPolicy = "NoSession",
                Reason = "NoSession"
            };
            if (settings == null || session == null)
            {
                return decision;
            }

            decision.ResolvedKind = settings.ResolveKind(
                session.ContactHash,
                session.DetectedKind);
            decision.NotificationOverride = settings.ResolveNotificationOverride(
                session.ContactHash);

            // Official accounts are keyword-allow-only. A matching current
            // summary can notify; all other official messages remain blocked.
            if (session.DetectedKind == ChatSessionKind.OfficialAccount ||
                session.HasOfficialMarker ||
                decision.ResolvedKind == ChatSessionKind.OfficialAccount)
            {
                decision.DefaultPolicy = "OfficialAccountKeywordAllowOnly";
                decision.ShouldDeliver = settings.HasOfficialAccountAllowKeyword(
                    session.Preview);
                decision.Reason = decision.ShouldDeliver
                    ? "OfficialAccountKeywordMatched"
                    : "OfficialAccountKeywordNotMatched";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.ServiceAccount)
            {
                decision.DefaultPolicy = "ServiceAccountKeywordOrSessionAllow";
                if (decision.NotificationOverride == SessionNotificationOverride.Block)
                {
                    decision.Reason = "ServiceAccountExplicitlyBlocked";
                    return decision;
                }
                if (settings.HasServiceAccountAllowKeyword(session.Preview))
                {
                    decision.ShouldDeliver = true;
                    decision.Reason = "ServiceAccountKeywordMatched";
                    return decision;
                }
                decision.ShouldDeliver =
                    decision.NotificationOverride ==
                    SessionNotificationOverride.Allow;
                decision.Reason = decision.ShouldDeliver
                    ? "ServiceAccountExplicitlyAllowed"
                    : "ServiceAccountNotAllowed";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.GroupChat)
            {
                decision.DefaultPolicy = "GroupChatDefaultAllowed";
                if (decision.NotificationOverride == SessionNotificationOverride.Block)
                {
                    decision.Reason = "GroupChatExplicitlyBlocked";
                    return decision;
                }
                if (settings.HasGroupChatBlockKeyword(session.Contact))
                {
                    decision.Reason = "GroupChatNameBlockKeywordMatched";
                    return decision;
                }
                decision.ShouldDeliver = true;
                decision.Reason = "GroupChatDefaultAllowed";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.DirectContact)
            {
                decision.DefaultPolicy = "DirectContactDefaultAllowed";
                decision.ShouldDeliver =
                    decision.NotificationOverride !=
                    SessionNotificationOverride.Block;
                decision.Reason = decision.ShouldDeliver
                    ? "DirectContactDefaultAllowed"
                    : "DirectContactExplicitlyBlocked";
                return decision;
            }

            decision.DefaultPolicy = "UnknownDefaultAllowed";
            decision.ShouldDeliver =
                decision.NotificationOverride != SessionNotificationOverride.Block;
            decision.Reason = decision.ShouldDeliver
                ? "UnknownDefaultAllowed"
                : "UnknownExplicitlyBlocked";
            return decision;
        }

        private void LogCandidateDiagnostic(
            ChatSession session,
            NotificationDecision decision)
        {
            logger.Info(FormatCandidateDiagnostic(
                session,
                decision));
        }

        internal static string FormatCandidateDiagnostic(
            ChatSession session,
            NotificationDecision decision)
        {
            return "Notification candidate: ContactHash=" +
                session.ContactHash +
                ", DetectedKind=" +
                session.DetectedKind +
                ", ResolvedKind=" +
                decision.ResolvedKind +
                ", NotificationOverride=" +
                (decision.NotificationOverride.HasValue
                    ? decision.NotificationOverride.Value.ToString()
                    : "None") +
                ", DefaultPolicy=" +
                decision.DefaultPolicy +
                ", Result=" +
                (decision.ShouldDeliver ? "Allowed" : "Blocked") +
                ", Reason=" +
                decision.Reason +
                ", HasGroupMarker=" +
                session.HasGroupMarker +
                ", HasOfficialMarker=" +
                session.HasOfficialMarker;
        }

        private static string Limit(string value, int maximum)
        {
            if (string.IsNullOrEmpty(value) || value.Length <= maximum)
            {
                return value;
            }
            return value.Substring(0, maximum - 1) + "…";
        }
    }
}
