// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using EventWaitHandle = System.Threading.EventWaitHandle;

namespace WeChatMessageNotifier
{
    internal sealed class NotifierApplicationContext : ApplicationContext
    {
        internal const string WindowsNotificationDurationSettingsUri =
            "ms-settings:easeofaccess-visualeffects";
        internal const int ActivePollIntervalMilliseconds = 1500;
        internal const int IdlePollIntervalMilliseconds = 5000;

        // NotifyIcon has no ContextMenuStrip on the production path. Right
        // clicks are routed to the WinUI 3 tray surface, which owns its
        // Acrylic and Per-Monitor-V2 rendering.
        internal static bool UsesCustomTrayMenuRuntime
        {
            get { return false; }
        }

        internal static bool UsesWinUiTrayRuntime
        {
            get { return true; }
        }

        internal static bool UsesWinUiSettingsRuntime
        {
            get { return true; }
        }

        // The tray application owns all timers and UI objects on one STA thread,
        // avoiding cross-thread access to WinForms and UI Automation objects.
        private readonly Logger logger;
        private readonly WeChatMonitor monitor;
        private readonly WindowsNotificationCenter notificationCenter;
        private readonly NotifyIcon trayIcon;
        private readonly Timer pollTimer;
        private readonly Timer activationTimer;
        private readonly Timer uiCommandTimer;
        private readonly EventWaitHandle activationEvent;
        private readonly TrayMenuEntry pauseItem;
        private readonly TrayMenuEntry privacyItem;
        private readonly TrayMenuEntry diagnosticNextItem;
        private readonly TrayMenuEntry diagnosticWeChatWindowsItem;
        private readonly TrayMenuEntry statusItem;
        private readonly NotificationFilterSettings notificationFilters;
        private readonly SettingsStore settingsStore;
        private readonly string trayCommandPath;
        private readonly Icon trayVisualIcon;
        private readonly Queue<NotificationActivityRecord> recentActivity =
            new Queue<NotificationActivityRecord>();
        private const int RecentActivityCapacity = 30;
        private bool paused;
        private bool privacyMode;
        private bool suppressWhenWeChatForeground;
        private ToastActivationRequest pendingActivationRequest;
        private Process settingsUiProcess;
        private Process trayUiProcess;
        private string monitoringState = "状态：等待首次扫描";

        internal NotifierApplicationContext(
            string[] args,
            EventWaitHandle activationEvent)
        {
            this.activationEvent = activationEvent;
            logger = new Logger();
            settingsStore = new SettingsStore(logger);
            trayCommandPath = Path.Combine(
                Path.GetDirectoryName(settingsStore.Path),
                "ui-command.txt");
            notificationFilters = settingsStore.Load();
            // Persist the active schema once so legacy popup/motion fields and
            // retired type switches disappear without touching hash-only rules.
            settingsStore.Save(notificationFilters);
            monitor = new WeChatMonitor(logger);
            notificationCenter = new WindowsNotificationCenter(
                HandleToastActivation,
                logger);
            pendingActivationRequest =
                Program.ExtractToastActivationRequest(args) ??
                Program.ReadActivationPayload();

            privacyMode = notificationFilters.PrivacyMode || HasArgument(args, "--privacy");
            notificationFilters.PrivacyMode = privacyMode;
            // A notification click brings WeChat to the foreground. Suppressing
            // every later message in that state can hide messages from other
            // conversations, so foreground notifications are enabled by
            // default. The opt-in switch preserves the quieter old behavior.
            suppressWhenWeChatForeground =
                HasArgument(args, "--suppress-foreground") &&
                !HasArgument(args, "--notify-foreground");

            pauseItem = new TrayMenuEntry("\u6682\u505c\u76d1\u63a7", delegate { TogglePause(); });

            privacyItem = new TrayMenuEntry("\u9690\u79c1\u6a21\u5f0f\uff08\u4ec5\u663e\u793a\u8054\u7cfb\u4eba\uff09", delegate { TogglePrivacy(); });
            privacyItem.IsChecked = privacyMode;

            diagnosticNextItem = new TrayMenuEntry(
                "\u4e0b\u4e00\u6b21\u63d0\u9192\u663e\u793a\u5206\u7c7b", delegate { ToggleDiagnosticNext(); });
            diagnosticWeChatWindowsItem = new TrayMenuEntry(
                "\u8bb0\u5f55\u5fae\u4fe1\u7a97\u53e3\u7ed3\u6784",
                delegate { monitor.LogWindowStructure(); });
            statusItem = new TrayMenuEntry(string.Empty, null) { Enabled = false };
            RefreshTrayStatus();

            trayIcon = new NotifyIcon
            {
                Icon = trayVisualIcon = LoadTrayIcon(),
                Text = "微信消息提醒器",
                Visible = true
            };
            trayIcon.MouseUp += delegate(object sender, MouseEventArgs eventArgs)
            {
                if (eventArgs.Button == MouseButtons.Right)
                {
                    ShowWinUiTrayMenu(Cursor.Position);
                }
            };
            trayIcon.DoubleClick += delegate
            {
                OpenSettingsWindow();
            };

            uiCommandTimer = new Timer { Interval = 300 };
            uiCommandTimer.Tick += delegate { ProcessWinUiCommand(); };
            uiCommandTimer.Start();

            pollTimer = new Timer { Interval = ActivePollIntervalMilliseconds };
            pollTimer.Tick += Poll;
            pollTimer.Start();

            activationTimer = new Timer { Interval = 200 };
            activationTimer.Tick += delegate
            {
                if (this.activationEvent.WaitOne(0))
                {
                    logger.Info("Notification center entry activated.");
                    var request =
                        Program.ReadActivationPayload() ??
                        pendingActivationRequest;
                    pendingActivationRequest = null;
                    HandleToastActivation(request);
                }
            };
            activationTimer.Start();

            logger.Info("Application started. Message content is not written to the log.");
            logger.Info("Notification delivery uses Windows system notifications only.");
        }

        private void OpenSettingsWindow()
        {
            try
            {
                var settingsUiPath = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "SettingsUi",
                    "WeChatMessageNotifier.WinUI.exe");
                if (!File.Exists(settingsUiPath))
                {
                    throw new FileNotFoundException(
                        "Modern settings UI was not found. Rebuild or reinstall the notifier.",
                        settingsUiPath);
                }
                EnsureWinUiWindowIcon(Path.GetDirectoryName(settingsUiPath));

                if (settingsUiProcess != null && !settingsUiProcess.HasExited)
                {
                    var handle = settingsUiProcess.MainWindowHandle;
                    if (handle != IntPtr.Zero)
                    {
                        NativeMethods.ShowWindow(handle, NativeMethods.SwRestore);
                        NativeMethods.SetForegroundWindow(handle);
                    }
                    return;
                }

                settingsUiProcess = Process.Start(new ProcessStartInfo
                {
                    FileName = settingsUiPath,
                    Arguments = "--settings-path " + QuoteArgument(settingsStore.Path) +
                        " --monitoring-state " + QuoteArgument(monitoringState),
                    WorkingDirectory = Path.GetDirectoryName(settingsUiPath),
                    UseShellExecute = false
                });
                logger.Info("Opened the WinUI settings window.");
            }
            catch (Exception exception)
            {
                logger.Error("Could not open settings window", exception);
                MessageBox.Show(
                    "无法打开设置窗口。请查看提醒器日志中的错误详情。",
                    "微信消息提醒器",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private static string QuoteArgument(string value)
        {
            return "\"" + (value ?? string.Empty).Replace("\"", "\\\"") + "\"";
        }

        private void ShowWinUiTrayMenu(Point cursorPosition)
        {
            try
            {
                if (trayUiProcess != null && !trayUiProcess.HasExited)
                {
                    return;
                }

                var uiPath = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "SettingsUi",
                    "WeChatMessageNotifier.WinUI.exe");
                if (!File.Exists(uiPath))
                {
                    throw new FileNotFoundException("Modern tray UI was not found.", uiPath);
                }
                EnsureWinUiWindowIcon(Path.GetDirectoryName(uiPath));

                var workingArea = Screen.FromPoint(cursorPosition).WorkingArea;
                const int menuWidth = 338;
                const int menuHeight = 510;
                var right = Math.Max(workingArea.Left + menuWidth,
                    Math.Min(cursorPosition.X, workingArea.Right));
                var bottom = Math.Max(workingArea.Top + menuHeight,
                    Math.Min(cursorPosition.Y, workingArea.Bottom));
                trayUiProcess = Process.Start(new ProcessStartInfo
                {
                    FileName = uiPath,
                    Arguments = "--tray --command-path " + QuoteArgument(trayCommandPath) +
                        " --monitoring-state " + QuoteArgument(monitoringState) +
                        " --x " + right + " --y " + bottom +
                        (paused ? " --paused" : string.Empty) +
                        (privacyMode ? " --privacy" : string.Empty),
                    WorkingDirectory = Path.GetDirectoryName(uiPath),
                    UseShellExecute = false
                });
            }
            catch (Exception exception)
            {
                logger.Error("Could not open WinUI tray menu", exception);
            }
        }

        // WinUI title bars need an .ico file rather than the in-memory
        // NotifyIcon instance. Generate it once beside the deployed WinUI
        // executable from the same local WeChat executable used for the tray
        // icon; no contact data, message data, or network access is involved.
        private void EnsureWinUiWindowIcon(string uiDirectory)
        {
            if (string.IsNullOrWhiteSpace(uiDirectory) || !Directory.Exists(uiDirectory))
            {
                return;
            }

            var destination = Path.Combine(uiDirectory, "WeChatMessageNotifier.WinUI.ico");
            if (File.Exists(destination))
            {
                return;
            }

            var source = WindowsNotificationCenter.ResolveWeChatIconSourcePathForTest();
            if (string.IsNullOrWhiteSpace(source) || !File.Exists(source))
            {
                return;
            }

            var temporary = destination + ".tmp";
            try
            {
                using (var icon = Icon.ExtractAssociatedIcon(source))
                {
                    if (icon == null)
                    {
                        return;
                    }

                    using (var stream = new FileStream(temporary, FileMode.Create, FileAccess.Write, FileShare.None))
                    {
                        icon.Save(stream);
                    }
                }
                File.Move(temporary, destination);
                logger.Info("Prepared the local WeChat icon for WinUI title bars.");
            }
            catch (Exception exception)
            {
                // The UI remains usable with the packaged fallback icon when a
                // particular WeChat installation does not expose an ICO.
                logger.Error("Could not prepare the WinUI title-bar icon", exception);
            }
            finally
            {
                try
                {
                    if (File.Exists(temporary))
                    {
                        File.Delete(temporary);
                    }
                }
                catch
                {
                    // A temporary icon file is harmless and can be retried next time.
                }
            }
        }

        private void ProcessWinUiCommand()
        {
            string command = null;
            try
            {
                if (!File.Exists(trayCommandPath))
                {
                    return;
                }
                command = File.ReadAllText(trayCommandPath).Trim();
                File.Delete(trayCommandPath);
            }
            catch (Exception exception)
            {
                logger.Error("Could not read WinUI tray command", exception);
                return;
            }

            try
            {
                switch (command)
                {
                    case "open-settings": OpenSettingsWindow(); break;
                    case "toggle-pause": TogglePause(); break;
                    case "toggle-privacy": TogglePrivacy(); break;
                    case "send-test": SendTestNotification(); break;
                    case "open-notification-duration": OpenWindowsNotificationDurationSettings(); break;
                    case "toggle-diagnostic-next": ToggleDiagnosticNext(); break;
                    case "log-wechat-windows": monitor.LogWindowStructure(); break;
                    case "open-settings-file": OpenSettingsFile(); break;
                    case "open-log": OpenLogFile(); break;
                    case "exit": Exit(); break;
                    default: return;
                }
                logger.Info("Processed WinUI tray command: " + command + ".");
            }
            catch (Exception exception)
            {
                logger.Error("Could not process WinUI tray command", exception);
            }
        }

        private void TogglePause()
        {
            paused = !paused;
            pauseItem.Text = paused ? "继续监控" : "暂停监控";
            trayIcon.Text = paused ? "微信消息提醒器（已暂停）" : "微信消息提醒器";
            RefreshTrayStatus();
        }

        private static Icon LoadTrayIcon()
        {
            try
            {
                var source = WindowsNotificationCenter.ResolveWeChatIconSourcePathForTest();
                if (!string.IsNullOrWhiteSpace(source) && File.Exists(source))
                {
                    using (var icon = Icon.ExtractAssociatedIcon(source))
                    {
                        if (icon != null)
                        {
                            return (Icon)icon.Clone();
                        }
                    }
                }
            }
            catch
            {
                // The notifier remains usable on installations where WeChat
                // is not discoverable yet; use a stable generic fallback.
            }
            return (Icon)SystemIcons.Information.Clone();
        }

        private void TogglePrivacy()
        {
            privacyMode = !privacyMode;
            privacyItem.IsChecked = privacyMode;
            notificationFilters.PrivacyMode = privacyMode;
            settingsStore.Save(notificationFilters);
        }

        private void ToggleDiagnosticNext()
        {
            diagnosticNextItem.IsChecked = !diagnosticNextItem.IsChecked;
        }

        private void SendTestNotification()
        {
            notificationCenter.Show(
                "微信消息提醒器",
                "测试成功：Windows 系统通知工作正常。",
                false);
        }

        private void OpenSettingsFile()
        {
            settingsStore.Save(notificationFilters);
            Process.Start("notepad.exe", "\"" + settingsStore.Path + "\"");
        }

        private void OpenLogFile()
        {
            Process.Start("explorer.exe", "/select,\"" + logger.Path + "\"");
        }

        private void RefreshTrayStatus()
        {
            if (statusItem != null)
            {
                statusItem.Text = paused ? "状态：监控已暂停" : monitoringState;
            }
        }

        private void Poll(object sender, EventArgs eventArgs)
        {
            if (paused)
            {
                return;
            }

            settingsStore.ReloadIfChanged(notificationFilters);
            if (privacyMode != notificationFilters.PrivacyMode)
            {
                privacyMode = notificationFilters.PrivacyMode;
                privacyItem.IsChecked = privacyMode;
            }
            var changes = monitor.Poll();
            UpdateMonitoringState();
            if (changes.Count == 0)
            {
                return;
            }

            // Avoid repeating a message the user can already see in WeChat.
            if (suppressWhenWeChatForeground && monitor.IsWeChatForeground())
            {
                logger.Info("Suppressed " + changes.Count + " notification(s) while WeChat was foreground.");
                return;
            }

            foreach (var session in changes)
            {
                var decision = EvaluateNotification(
                    notificationFilters,
                    session);
                session.Kind = decision.ResolvedKind;
                RecordActivity(session, decision);
                if (diagnosticNextItem.IsChecked)
                {
                    LogCandidateDiagnostic(
                        session,
                        decision);
                    diagnosticNextItem.IsChecked = false;
                }

                if (!decision.ShouldDeliver)
                {
                    logger.Info(
                        "Notification filtered. ContactHash=" +
                        session.ContactHash +
                        " DetectedKind=" +
                        session.DetectedKind +
                        " ResolvedKind=" +
                        session.Kind +
                        " Reason=" +
                        decision.Reason +
                        " Count=1");
                    continue;
                }

                var preview = Limit(session.Preview, 180);
                var title = Limit(session.Contact, 80);
                var contactMessageCount = notificationCenter.ShowMessage(
                    session.SessionKey,
                    session.Kind,
                    title,
                    preview,
                    privacyMode,
                    false);
                logger.Info(
                    "Notification shown. ContactLength=" + session.Contact.Length +
                    " PreviewLength=" + session.Preview.Length +
                    " ContactMessageCount=" + contactMessageCount);
            }
        }

        private void UpdateMonitoringState()
        {
            if (monitor.MainWindow == IntPtr.Zero)
            {
                monitoringState = "状态：未检测到微信";
            }
            else if (monitor.LastSessionCount <= 0)
            {
                monitoringState = "状态：已连接微信，未读取会话列表";
            }
            else
            {
                monitoringState = "状态：已连接微信 · " +
                    monitor.LastSessionCount + " 个会话";
            }
            pollTimer.Interval = SelectPollInterval(
                monitor.MainWindow != IntPtr.Zero,
                monitor.LastSessionCount);
            RefreshTrayStatus();
        }

        internal static int SelectPollInterval(
            bool hasWeChatWindow,
            int sessionCount)
        {
            return hasWeChatWindow && sessionCount > 0
                ? ActivePollIntervalMilliseconds
                : IdlePollIntervalMilliseconds;
        }

        private void RecordActivity(
            ChatSession session,
            NotificationDecision decision)
        {
            recentActivity.Enqueue(new NotificationActivityRecord
            {
                Timestamp = DateTime.Now,
                ContactHash = session.ContactHash,
                DetectedKind = session.DetectedKind,
                ResolvedKind = decision.ResolvedKind,
                Delivered = decision.ShouldDeliver,
                Reason = decision.Reason
            });
            while (recentActivity.Count > RecentActivityCapacity)
            {
                recentActivity.Dequeue();
            }
        }

        private void HandleToastActivation(ToastActivationRequest request)
        {
            if (request == null || string.IsNullOrWhiteSpace(request.SessionKey))
            {
                monitor.ActivateWeChat(request);
                return;
            }

            // Clear only after UIA confirms that WeChat selected the intended
            // conversation. Failed navigation must leave the notification in
            // place rather than making unread messages disappear.
            if (monitor.ActivateWeChat(request))
            {
                notificationCenter.ClearSession(request.SessionKey);
            }
        }

        private void Exit()
        {
            pollTimer.Stop();
            activationTimer.Stop();
            uiCommandTimer.Stop();
            notificationCenter.Dispose();
            if (settingsUiProcess != null)
            {
                settingsUiProcess.Dispose();
                settingsUiProcess = null;
            }
            if (trayUiProcess != null)
            {
                trayUiProcess.Dispose();
                trayUiProcess = null;
            }
            trayIcon.Visible = false;
            trayIcon.Dispose();
            trayVisualIcon.Dispose();
            pollTimer.Dispose();
            activationTimer.Dispose();
            uiCommandTimer.Dispose();
            logger.Info("Application exited.");
            ExitThread();
        }

        private void OpenWindowsNotificationDurationSettings()
        {
            try
            {
                Process.Start(
                    "explorer.exe",
                    WindowsNotificationDurationSettingsUri);
                logger.Info("Opened Windows notification duration settings.");
            }
            catch (Exception exception)
            {
                logger.Error(
                    "Could not open Windows notification duration settings",
                    exception);
            }
        }

        private static bool HasArgument(string[] args, string expected)
        {
            foreach (var value in args)
            {
                if (string.Equals(value, expected, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        internal static bool ShouldDeliverNotification(
            NotificationFilterSettings settings,
            ChatSession session)
        {
            return EvaluateNotification(settings, session).ShouldDeliver;
        }

        internal static NotificationDecision EvaluateNotification(
            NotificationFilterSettings settings,
            ChatSession session)
        {
            var decision = new NotificationDecision
            {
                ShouldDeliver = false,
                ResolvedKind = ChatSessionKind.Unknown,
                DefaultPolicy = "NoSession",
                Reason = "NoSession"
            };
            if (settings == null || session == null)
            {
                return decision;
            }

            decision.ResolvedKind = settings.ResolveKind(
                session.ContactHash,
                session.DetectedKind);
            decision.NotificationOverride = settings.ResolveNotificationOverride(
                session.ContactHash);

            // Official accounts are keyword-allow-only. A matching current
            // summary can notify; all other official messages remain blocked.
            if (session.DetectedKind == ChatSessionKind.OfficialAccount ||
                session.HasOfficialMarker ||
                decision.ResolvedKind == ChatSessionKind.OfficialAccount)
            {
                decision.DefaultPolicy = "OfficialAccountKeywordAllowOnly";
                decision.ShouldDeliver = settings.HasOfficialAccountAllowKeyword(
                    session.Preview);
                decision.Reason = decision.ShouldDeliver
                    ? "OfficialAccountKeywordMatched"
                    : "OfficialAccountKeywordNotMatched";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.ServiceAccount)
            {
                decision.DefaultPolicy = "ServiceAccountKeywordOrSessionAllow";
                if (decision.NotificationOverride == SessionNotificationOverride.Block)
                {
                    decision.Reason = "ServiceAccountExplicitlyBlocked";
                    return decision;
                }
                if (settings.HasServiceAccountAllowKeyword(session.Preview))
                {
                    decision.ShouldDeliver = true;
                    decision.Reason = "ServiceAccountKeywordMatched";
                    return decision;
                }
                decision.ShouldDeliver =
                    decision.NotificationOverride ==
                    SessionNotificationOverride.Allow;
                decision.Reason = decision.ShouldDeliver
                    ? "ServiceAccountExplicitlyAllowed"
                    : "ServiceAccountNotAllowed";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.GroupChat)
            {
                decision.DefaultPolicy = "GroupChatDefaultAllowed";
                if (decision.NotificationOverride == SessionNotificationOverride.Block)
                {
                    decision.Reason = "GroupChatExplicitlyBlocked";
                    return decision;
                }
                if (settings.HasGroupChatBlockKeyword(session.Contact))
                {
                    decision.Reason = "GroupChatNameBlockKeywordMatched";
                    return decision;
                }
                decision.ShouldDeliver = true;
                decision.Reason = "GroupChatDefaultAllowed";
                return decision;
            }

            if (decision.ResolvedKind == ChatSessionKind.DirectContact)
            {
                decision.DefaultPolicy = "DirectContactDefaultAllowed";
                decision.ShouldDeliver =
                    decision.NotificationOverride !=
                    SessionNotificationOverride.Block;
                decision.Reason = decision.ShouldDeliver
                    ? "DirectContactDefaultAllowed"
                    : "DirectContactExplicitlyBlocked";
                return decision;
            }

            decision.DefaultPolicy = "UnknownDefaultAllowed";
            decision.ShouldDeliver =
                decision.NotificationOverride != SessionNotificationOverride.Block;
            decision.Reason = decision.ShouldDeliver
                ? "UnknownDefaultAllowed"
                : "UnknownExplicitlyBlocked";
            return decision;
        }

        private void LogCandidateDiagnostic(
            ChatSession session,
            NotificationDecision decision)
        {
            logger.Info(FormatCandidateDiagnostic(
                session,
                decision));
        }

        internal static string FormatCandidateDiagnostic(
            ChatSession session,
            NotificationDecision decision)
        {
            return "Notification candidate: ContactHash=" +
                session.ContactHash +
                ", DetectedKind=" +
                session.DetectedKind +
                ", ResolvedKind=" +
                decision.ResolvedKind +
                ", NotificationOverride=" +
                (decision.NotificationOverride.HasValue
                    ? decision.NotificationOverride.Value.ToString()
                    : "None") +
                ", DefaultPolicy=" +
                decision.DefaultPolicy +
                ", Result=" +
                (decision.ShouldDeliver ? "Allowed" : "Blocked") +
                ", Reason=" +
                decision.Reason +
                ", HasGroupMarker=" +
                session.HasGroupMarker +
                ", HasOfficialMarker=" +
                session.HasOfficialMarker;
        }

        private static string Limit(string value, int maximum)
        {
            if (string.IsNullOrEmpty(value) || value.Length <= maximum)
            {
                return value;
            }
            return value.Substring(0, maximum - 1) + "…";
        }
    }
}
