// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class PopupManager
    {
        // A lightweight timer re-evaluates popup placement. This is separate
        // from message polling and never reads message content.
        private readonly List<PopupForm> active = new List<PopupForm>();
        private readonly Action activateWeChat;
        private readonly Timer avoidanceTimer;
        private readonly int currentProcessId;
        private int avoidanceOffset;

        internal PopupManager(Action activateWeChat)
        {
            this.activateWeChat = activateWeChat;
            currentProcessId = Process.GetCurrentProcess().Id;
            avoidanceTimer = new Timer { Interval = 250 };
            avoidanceTimer.Tick += delegate { Reposition(); };
            avoidanceTimer.Start();
        }

        internal void Show(string contact, string preview)
        {
            active.RemoveAll(delegate(PopupForm existingPopup) { return existingPopup.IsDisposed; });
            var existing = active.FirstOrDefault(
                delegate(PopupForm existingPopup)
                {
                    return string.Equals(existingPopup.ContactKey, contact, StringComparison.Ordinal);
                });
            // Consecutive messages from one contact update the existing popup
            // instead of filling the screen with duplicates.
            if (existing != null)
            {
                existing.UpdateMessage(contact, preview);
                active.Remove(existing);
                active.Add(existing);
                Reposition();
                return;
            }

            var popup = new PopupForm(contact, preview, activateWeChat);
            popup.FormClosed += delegate
            {
                active.Remove(popup);
                Reposition();
            };
            active.Add(popup);
            popup.Show();
            Reposition();
        }

        internal void CloseAll()
        {
            avoidanceTimer.Stop();
            avoidanceTimer.Dispose();
            foreach (var popup in active.ToArray())
            {
                popup.Close();
            }
            active.Clear();
        }

        private void Reposition()
        {
            var foreground = NativeMethods.GetForegroundWindow();
            var targetScreen = foreground != IntPtr.Zero
                ? Screen.FromHandle(foreground)
                : Screen.PrimaryScreen;
            var area = targetScreen.WorkingArea;
            var targetOffset = CalculateAvoidanceOffset(area);
            if (avoidanceOffset < targetOffset)
            {
                avoidanceOffset = Math.Min(targetOffset, avoidanceOffset + 48);
            }
            else if (avoidanceOffset > targetOffset)
            {
                avoidanceOffset = Math.Max(targetOffset, avoidanceOffset - 32);
            }

            var bottom = area.Bottom - 12 - avoidanceOffset;
            foreach (var popup in active.Where(delegate(PopupForm form) { return !form.IsDisposed; }).Reverse())
            {
                popup.Location = new Point(area.Right - popup.Width - 12, bottom - popup.Height);
                popup.EnsureTopMost();
                bottom -= popup.Height + 10;
            }
        }

        private int CalculateAvoidanceOffset(Rectangle area)
        {
            if (active.Count == 0)
            {
                return 0;
            }

            var popup = active[active.Count - 1];
            var left = area.Right - popup.Width - 12;
            var top = area.Bottom - popup.Height - 12;
            // Sample several points in the default popup rectangle. If a later
            // topmost toast occupies the area, the entire WeChat stack moves up.
            var samplePoints = new[]
            {
                new Point(left + 24, top + 24),
                new Point(left + popup.Width / 2, top + popup.Height / 2),
                new Point(left + popup.Width - 24, top + popup.Height - 24)
            };

            var offset = 0;
            foreach (var point in samplePoints)
            {
                Rectangle obstruction;
                if (NativeMethods.TryGetExternalTopmostWindowAt(point, currentProcessId, out obstruction))
                {
                    offset = Math.Max(offset, area.Bottom - obstruction.Top + 16);
                }
            }

            return Math.Max(0, Math.Min(offset, area.Height / 2));
        }
    }
}
