// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class PopupManager
    {
        internal const int AnimationIntervalMilliseconds = 16;
        private const int DetectionIntervalFrames = 15;

        // One timer drives a 60 FPS spring animation. Expensive window
        // obstruction detection still runs only about every 240 milliseconds.
        private readonly List<PopupForm> active = new List<PopupForm>();
        private readonly Action activateWeChat;
        private readonly Timer avoidanceTimer;
        private readonly int currentProcessId;
        private double avoidanceOffset;
        private double avoidanceVelocity;
        private int targetAvoidanceOffset;
        private int framesSinceDetection = DetectionIntervalFrames;
        private Rectangle workingArea = Rectangle.Empty;

        internal PopupManager(Action activateWeChat)
        {
            this.activateWeChat = activateWeChat;
            currentProcessId = Process.GetCurrentProcess().Id;
            avoidanceTimer = new Timer { Interval = AnimationIntervalMilliseconds };
            avoidanceTimer.Tick += delegate { Reposition(); };
        }

        internal void Show(string contact, string preview)
        {
            active.RemoveAll(delegate(PopupForm existingPopup) { return existingPopup.IsDisposed; });
            var existing = active.FirstOrDefault(
                delegate(PopupForm existingPopup)
                {
                    return string.Equals(existingPopup.ContactKey, contact, StringComparison.Ordinal);
                });
            // Consecutive messages from one contact update the existing popup
            // instead of filling the screen with duplicates.
            if (existing != null)
            {
                existing.UpdateMessage(contact, preview);
                active.Remove(existing);
                active.Add(existing);
                framesSinceDetection = DetectionIntervalFrames;
                if (!avoidanceTimer.Enabled)
                {
                    avoidanceTimer.Start();
                }
                Reposition();
                return;
            }

            var popup = new PopupForm(contact, preview, activateWeChat);
            popup.FormClosed += delegate
            {
                active.Remove(popup);
                framesSinceDetection = DetectionIntervalFrames;
                if (active.Count == 0)
                {
                    avoidanceTimer.Stop();
                    avoidanceOffset = 0;
                    avoidanceVelocity = 0;
                    targetAvoidanceOffset = 0;
                    workingArea = Rectangle.Empty;
                }
                Reposition();
            };
            active.Add(popup);
            popup.Show();
            framesSinceDetection = DetectionIntervalFrames;
            if (!avoidanceTimer.Enabled)
            {
                avoidanceTimer.Start();
            }
            Reposition();
        }

        internal void CloseAll()
        {
            avoidanceTimer.Stop();
            avoidanceTimer.Dispose();
            foreach (var popup in active.ToArray())
            {
                popup.Close();
            }
            active.Clear();
        }

        private void Reposition()
        {
            if (active.Count == 0)
            {
                return;
            }

            framesSinceDetection++;
            if (workingArea == Rectangle.Empty ||
                framesSinceDetection >= DetectionIntervalFrames)
            {
                var foreground = NativeMethods.GetForegroundWindow();
                var targetScreen = foreground != IntPtr.Zero
                    ? Screen.FromHandle(foreground)
                    : Screen.PrimaryScreen;
                workingArea = targetScreen.WorkingArea;
                targetAvoidanceOffset = CalculateAvoidanceOffset(workingArea);
                framesSinceDetection = 0;
            }

            // Damped spring motion gives fast initial movement, natural
            // deceleration, and a very small settling response near the target.
            var displacement = targetAvoidanceOffset - avoidanceOffset;
            avoidanceVelocity = (avoidanceVelocity + displacement * 0.12) * 0.72;
            avoidanceOffset += avoidanceVelocity;
            if (Math.Abs(displacement) < 0.5 &&
                Math.Abs(avoidanceVelocity) < 0.5)
            {
                avoidanceOffset = targetAvoidanceOffset;
                avoidanceVelocity = 0;
            }

            avoidanceOffset = Math.Max(
                0,
                Math.Min(avoidanceOffset, workingArea.Height / 2.0));
            var renderedOffset = (int)Math.Round(avoidanceOffset);
            var bottom = workingArea.Bottom - 12 - renderedOffset;
            foreach (var popup in active.Where(delegate(PopupForm form) { return !form.IsDisposed; }).Reverse())
            {
                popup.Location = new Point(
                    workingArea.Right - popup.Width - 12,
                    bottom - popup.Height);
                popup.EnsureTopMost();
                bottom -= popup.Height + 10;
            }
        }

        private int CalculateAvoidanceOffset(Rectangle area)
        {
            if (active.Count == 0)
            {
                return 0;
            }

            var popup = active[active.Count - 1];
            var left = area.Right - popup.Width - 12;
            var top = area.Bottom - popup.Height - 12;
            // Sample several points in the default popup rectangle. If a later
            // topmost toast occupies the area, the entire WeChat stack moves up.
            var samplePoints = new[]
            {
                new Point(left + 24, top + 24),
                new Point(left + popup.Width / 2, top + popup.Height / 2),
                new Point(left + popup.Width - 24, top + popup.Height - 24)
            };

            var offset = 0;
            foreach (var point in samplePoints)
            {
                Rectangle obstruction;
                if (NativeMethods.TryGetExternalTopmostWindowAt(point, currentProcessId, out obstruction))
                {
                    offset = Math.Max(offset, area.Bottom - obstruction.Top + 16);
                }
            }

            return Math.Max(0, Math.Min(offset, area.Height / 2));
        }
    }
}
