// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class PopupForm : Form
    {
        // Keep a notification visible long enough to be useful, but do not let
        // an unread popup remain on the desktop indefinitely.
        internal const int AutoCloseMilliseconds = 2 * 60 * 1000;

        private readonly Action activateWeChat;
        private readonly Label titleLabel;
        private readonly Label bodyLabel;
        private readonly Label closeLabel;
        private readonly Timer autoCloseTimer;

        internal PopupForm(string contact, string preview, Action activateWeChat)
        {
            this.activateWeChat = activateWeChat;
            ContactKey = contact;

            Width = 380;
            Height = 118;
            FormBorderStyle = FormBorderStyle.None;
            StartPosition = FormStartPosition.Manual;
            ShowInTaskbar = false;
            TopMost = true;
            BackColor = Color.FromArgb(242, 247, 250);
            Padding = new Padding(16, 12, 16, 12);
            Opacity = 0.94;

            var accent = new Panel
            {
                Dock = DockStyle.Left,
                Width = 5,
                BackColor = Color.FromArgb(7, 193, 96)
            };

            titleLabel = new Label
            {
                AutoEllipsis = true,
                AutoSize = false,
                Font = new Font("Microsoft YaHei UI", 11F, FontStyle.Bold),
                ForeColor = Color.FromArgb(31, 41, 55),
                Location = new Point(24, 13),
                Size = new Size(305, 27),
                Text = contact
            };

            closeLabel = new Label
            {
                AutoSize = false,
                Cursor = Cursors.Hand,
                Font = new Font("Microsoft YaHei UI", 12F, FontStyle.Regular),
                ForeColor = Color.FromArgb(107, 114, 128),
                Location = new Point(342, 9),
                Size = new Size(24, 28),
                Text = "×",
                TextAlign = ContentAlignment.MiddleCenter
            };

            bodyLabel = new Label
            {
                AutoEllipsis = true,
                AutoSize = false,
                Font = new Font("Microsoft YaHei UI", 9.5F, FontStyle.Regular),
                ForeColor = Color.FromArgb(75, 85, 99),
                Location = new Point(24, 44),
                Size = new Size(335, 55),
                Text = preview
            };

            Controls.Add(accent);
            Controls.Add(titleLabel);
            Controls.Add(bodyLabel);
            Controls.Add(closeLabel);

            autoCloseTimer = new Timer { Interval = AutoCloseMilliseconds };
            autoCloseTimer.Tick += delegate
            {
                autoCloseTimer.Stop();
                Close();
            };

            Click += OnPopupClick;
            titleLabel.Click += OnPopupClick;
            bodyLabel.Click += OnPopupClick;
            accent.Click += OnPopupClick;
            closeLabel.Click += delegate
            {
                autoCloseTimer.Stop();
                Close();
            };

            HandleCreated += delegate
            {
                NativeMethods.ApplyWindows11PopupStyle(Handle);
            };
            Shown += delegate
            {
                EnsureTopMost();
                autoCloseTimer.Start();
            };
        }

        internal string ContactKey { get; private set; }

        internal void UpdateMessage(string contact, string preview)
        {
            ContactKey = contact;
            titleLabel.Text = contact;
            bodyLabel.Text = preview;
            Opacity = 0.94;
            EnsureTopMost();

            // A newer message from the same contact refreshes the existing
            // popup, so give the user a full two minutes to notice it.
            autoCloseTimer.Stop();
            autoCloseTimer.Start();
        }

        internal void EnsureTopMost()
        {
            if (!IsHandleCreated || IsDisposed)
            {
                return;
            }

            NativeMethods.SetWindowPos(
                Handle,
                NativeMethods.HwndTopmost,
                Left,
                Top,
                0,
                0,
                NativeMethods.SwpNoSize |
                NativeMethods.SwpNoActivate |
                NativeMethods.SwpShowWindow);
        }

        protected override bool ShowWithoutActivation
        {
            get { return true; }
        }

        protected override CreateParams CreateParams
        {
            get
            {
                const int WsExToolWindow = 0x00000080;
                const int WsExNoActivate = 0x08000000;
                const int CsDropShadow = 0x00020000;
                var parameters = base.CreateParams;
                // WS_EX_NOACTIVATE keeps the notification from stealing focus
                // from games, video, or the user's current full-screen app.
                parameters.ExStyle |= WsExToolWindow | WsExNoActivate;
                parameters.ClassStyle |= CsDropShadow;
                return parameters;
            }
        }

        protected override void OnResize(EventArgs eventArgs)
        {
            base.OnResize(eventArgs);
            if (Width <= 0 || Height <= 0)
            {
                return;
            }

            const int radius = 12;
            using (var path = new GraphicsPath())
            {
                path.AddArc(0, 0, radius * 2, radius * 2, 180, 90);
                path.AddArc(Width - radius * 2, 0, radius * 2, radius * 2, 270, 90);
                path.AddArc(
                    Width - radius * 2,
                    Height - radius * 2,
                    radius * 2,
                    radius * 2,
                    0,
                    90);
                path.AddArc(0, Height - radius * 2, radius * 2, radius * 2, 90, 90);
                path.CloseFigure();

                var oldRegion = Region;
                Region = new Region(path);
                if (oldRegion != null)
                {
                    oldRegion.Dispose();
                }
            }
        }

        private void OnPopupClick(object sender, EventArgs eventArgs)
        {
            autoCloseTimer.Stop();
            if (activateWeChat != null)
            {
                activateWeChat();
            }
            Close();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                autoCloseTimer.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
