// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;

namespace WeChatMessageNotifier
{
    // UI-independent state for one active contact notification. Keeping this
    // model separate makes contact merging and privacy formatting testable
    // without creating desktop windows.
    internal sealed class PopupEntry
    {
        internal PopupEntry(
            string sessionKey,
            string contact,
            string preview,
            bool privacyMode)
        {
            SessionKey = sessionKey;
            Contact = contact;
            LatestPreview = preview;
            PrivacyMode = privacyMode;
            MessageCount = 1;
        }

        internal string SessionKey { get; private set; }

        internal string Contact { get; private set; }

        internal string LatestPreview { get; private set; }

        internal bool PrivacyMode { get; private set; }

        internal int MessageCount { get; private set; }

        internal string TitleText
        {
            get
            {
                return MessageCount > 1
                    ? Contact + "\uFF08" + MessageCount + "\u6761\u65B0\u6D88\u606F\uFF09"
                    : Contact;
            }
        }

        internal string BodyText
        {
            get
            {
                if (!PrivacyMode)
                {
                    return LatestPreview;
                }

                return MessageCount > 1
                    ? "\u6536\u5230 " + MessageCount + " \u6761\u65B0\u6D88\u606F"
                    : "\u6536\u5230\u4E00\u6761\u65B0\u6D88\u606F";
            }
        }

        internal void Update(
            string contact,
            string preview,
            bool privacyMode)
        {
            Contact = contact;
            LatestPreview = preview;
            PrivacyMode = privacyMode;
            MessageCount++;
        }

        internal void SetPrivacyMode(bool privacyMode)
        {
            PrivacyMode = privacyMode;
        }
    }
}
