// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    // The only top-level notification window. Individual messages are child
    // controls, so they can never compete for TOPMOST z-order.
    internal sealed class PopupHostForm : Form
    {
        internal const int CardSpacing = 10;
        private const int WmDpiChanged = 0x02E0;
        private DpiMetrics metrics;
        private PopupVisualMode requestedVisualMode;
        private PopupVisualMode effectiveVisualMode;
        private bool backdropApplied;
        private bool accentBackdropApplied;
        private bool extendFrameApplied;
        private PopupBackdropKind appliedBackdropKind;

        internal PopupHostForm()
            : this(1.0f, PopupVisualMode.Auto)
        {
        }

        internal PopupHostForm(float dpiScale, PopupVisualMode visualMode)
        {
            metrics = DpiMetrics.FromScale(dpiScale);
            requestedVisualMode = visualMode;
            effectiveVisualMode = visualMode == PopupVisualMode.Solid
                ? PopupVisualMode.Solid
                : PopupVisualMode.Glass;
            Width = metrics.CardWidth;
            Height = metrics.CardHeight;
            FormBorderStyle = FormBorderStyle.None;
            StartPosition = FormStartPosition.Manual;
            ShowInTaskbar = false;
            TopMost = true;
            BackColor = Color.Black;
            // Keep the host as a normal opaque window. Form.Opacity and
            // TransparencyKey create a layered window, and layered-window
            // composition commonly softens ClearType text on Windows.
            Opacity = 1.0;
            DoubleBuffered = true;
            AutoScaleMode = AutoScaleMode.None;
            UpdateClipRegion();
        }

        internal event EventHandler DpiScaleChanged;

        internal float DpiScale
        {
            get { return metrics.Scale; }
        }

        internal DpiMetrics Metrics
        {
            get { return metrics; }
        }

        internal PopupVisualMode EffectiveVisualMode
        {
            get { return effectiveVisualMode; }
        }

        internal bool BackdropApplied
        {
            get { return backdropApplied; }
        }

        internal bool AccentBackdropApplied
        {
            get { return accentBackdropApplied; }
        }

        internal bool ExtendFrameApplied
        {
            get { return extendFrameApplied; }
        }

        internal PopupBackdropKind AppliedBackdropKind
        {
            get { return appliedBackdropKind; }
        }

        internal string VisualDiagnostics
        {
            get
            {
                return "VisualDiag: DwmBackdrop=" + backdropApplied +
                    ", ExtendFrame=" + extendFrameApplied +
                    ", Accent=" + accentBackdropApplied +
                    ", EffectiveVisualMode=" + effectiveVisualMode +
                    ", TextPath=GDI/TextRenderer" +
                    ", RequestedVisualMode=" + requestedVisualMode +
                    ", DwmBackdropApplied=" + backdropApplied +
                    ", AccentApplied=" + accentBackdropApplied +
                    ", ExtendFrameApplied=" + extendFrameApplied +
                    ", BackdropKind=" + appliedBackdropKind;
            }
        }

        internal int CardCount
        {
            get { return Controls.Count; }
        }

        internal void AddCard(PopupCardControl card)
        {
            if (!Controls.Contains(card))
            {
                Controls.Add(card);
                UpdateClipRegion();
                Invalidate();
            }
        }

        internal void RemoveCard(PopupCardControl card)
        {
            Controls.Remove(card);
            UpdateClipRegion();
            Invalidate();
        }

        // Called only after add/remove/reflow, never from the 60 FPS frame
        // loop. That keeps the union Region accurate without per-frame GDI
        // Region churn.
        internal void RefreshCardGeometry()
        {
            UpdateClipRegion();
            Invalidate();
        }

        internal void UpdateDpiScale(float dpiScale)
        {
            if (Math.Abs(metrics.Scale - dpiScale) < 0.01f)
            {
                return;
            }

            metrics = DpiMetrics.FromScale(dpiScale);
            Width = metrics.CardWidth;
            Height = CalculateRequiredHeight(
                Math.Max(1, Controls.Count),
                metrics);
            UpdateClipRegion();
        }

        internal void UpdateVisualMode(PopupVisualMode visualMode)
        {
            requestedVisualMode = visualMode;
            ApplyVisualMode();
            Invalidate(true);
        }

        internal int GrowToFit(int cardCount)
        {
            var requiredHeight = CalculateRequiredHeight(cardCount, metrics);
            if (requiredHeight <= Height)
            {
                return 0;
            }

            var delta = requiredHeight - Height;
            // Move the top and resize in one native bounds update so the
            // bottom edge remains fixed. Existing cards receive the opposite
            // local-Y compensation before this call and therefore do not jump
            // on screen while the host grows upward.
            SetBounds(
                Left,
                Top - delta,
                Width,
                requiredHeight,
                BoundsSpecified.Location | BoundsSpecified.Size);
            UpdateClipRegion();
            return delta;
        }

        internal int ShrinkToFit(int cardCount)
        {
            var requiredHeight = CalculateRequiredHeight(cardCount, metrics);
            if (requiredHeight >= Height)
            {
                return 0;
            }

            var delta = Height - requiredHeight;
            // Keep the bottom edge anchored and remove the unused glass area
            // from the top. PopupManager compensates remaining card local-Y
            // positions by -delta so their screen positions do not jump.
            SetBounds(
                Left,
                Top + delta,
                Width,
                requiredHeight,
                BoundsSpecified.Location | BoundsSpecified.Size);
            UpdateClipRegion();
            return delta;
        }

        internal static int CalculateRequiredHeight(int cardCount)
        {
            return CalculateRequiredHeight(
                cardCount,
                DpiUtil.DefaultMetrics);
        }

        internal static int CalculateRequiredHeight(
            int cardCount,
            DpiMetrics metrics)
        {
            return cardCount <= 0
                ? metrics.CardHeight
                : cardCount * metrics.CardHeight +
                  (cardCount - 1) * metrics.CardSpacing;
        }

        internal void ResetStackHeight()
        {
            Height = metrics.CardHeight;
            UpdateClipRegion();
        }

        internal void EnsureTopMost()
        {
            if (!IsHandleCreated || IsDisposed)
            {
                return;
            }

            NativeMethods.SetWindowPos(
                Handle,
                NativeMethods.HwndTopmost,
                Left,
                Top,
                0,
                0,
                NativeMethods.SwpNoMove |
                NativeMethods.SwpNoSize |
                NativeMethods.SwpNoActivate);
        }

        protected override bool ShowWithoutActivation
        {
            get { return true; }
        }

        protected override CreateParams CreateParams
        {
            get
            {
                const int WsExToolWindow = 0x00000080;
                const int WsExNoActivate = 0x08000000;
                var parameters = base.CreateParams;
                parameters.ExStyle |= WsExToolWindow | WsExNoActivate;
                return parameters;
            }
        }

        protected override void OnShown(EventArgs eventArgs)
        {
            base.OnShown(eventArgs);
            ApplyVisualMode();
            UpdateClipRegion();
            EnsureTopMost();
        }

        protected override void OnHandleCreated(EventArgs eventArgs)
        {
            base.OnHandleCreated(eventArgs);
            ApplyVisualMode();
            UpdateClipRegion();
        }

        protected override void OnResize(EventArgs eventArgs)
        {
            base.OnResize(eventArgs);
            UpdateClipRegion();
        }

        protected override void OnPaintBackground(PaintEventArgs eventArgs)
        {
            if (effectiveVisualMode == PopupVisualMode.Solid)
            {
                base.OnPaintBackground(eventArgs);
            }
            // DWM owns the Glass client background; painting a WinForms solid
            // host here would cover it before the single host composition pass.
        }

        protected override void OnPaint(PaintEventArgs eventArgs)
        {
            base.OnPaint(eventArgs);
            if (effectiveVisualMode != PopupVisualMode.Glass)
            {
                return;
            }

            eventArgs.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
            foreach (Control control in Controls)
            {
                var card = control as PopupCardControl;
                if (card == null || !card.Visible)
                {
                    continue;
                }
                var opacity = Math.Max(0, Math.Min(1, card.VisualOpacity));
                var alpha = Math.Max(218, (int)Math.Round(238 * opacity));
                using (var path = CreateRoundedPath(card.Bounds, metrics.CornerRadius))
                using (var tint = new SolidBrush(Color.FromArgb(alpha, 248, 251, 254)))
                using (var accent = new SolidBrush(Color.FromArgb(255, 7, 193, 96)))
                using (var border = new Pen(Color.FromArgb(170, 218, 226, 235)))
                {
                    eventArgs.Graphics.FillPath(tint, path);
                    eventArgs.Graphics.SetClip(path);
                    eventArgs.Graphics.FillRectangle(
                        accent,
                        card.Left,
                        card.Top,
                        metrics.AccentWidth,
                        card.Height);
                    eventArgs.Graphics.ResetClip();
                    eventArgs.Graphics.DrawPath(border, path);
                }
            }
        }

        protected override void WndProc(ref Message message)
        {
            if (message.Msg == WmDpiChanged)
            {
                var dpi = message.WParam.ToInt32() & 0xFFFF;
                UpdateDpiScale(DpiUtil.ScaleFromDpi(dpi));
                var handler = DpiScaleChanged;
                if (handler != null)
                {
                    handler(this, EventArgs.Empty);
                }
            }
            base.WndProc(ref message);
        }

        private void UpdateClipRegion()
        {
            if (Width <= 0 || Height <= 0 || metrics == null)
            {
                return;
            }

            var oldRegion = Region;
            using (var path = CreateCardUnionPath())
            {
                Region = new Region(path);
            }
            if (oldRegion != null)
            {
                oldRegion.Dispose();
            }
        }

        private GraphicsPath CreateCardUnionPath()
        {
            var result = new GraphicsPath();
            if (Controls.Count == 0)
            {
                result.AddPath(CreateRoundedPath(new Rectangle(0, 0, Width, Height), metrics.CornerRadius), false);
                return result;
            }
            foreach (Control control in Controls)
            {
                if (!control.Visible)
                {
                    continue;
                }
                using (var cardPath = CreateRoundedPath(control.Bounds, metrics.CornerRadius))
                {
                    result.AddPath(cardPath, false);
                }
            }
            return result;
        }

        private void ApplyVisualMode()
        {
            if (!IsHandleCreated)
            {
                return;
            }

            if (requestedVisualMode == PopupVisualMode.Solid)
            {
                backdropApplied = false;
                accentBackdropApplied = false;
                extendFrameApplied = false;
                appliedBackdropKind = PopupBackdropKind.None;
                effectiveVisualMode = PopupVisualMode.Solid;
                BackColor = Color.White;
                NativeMethods.TryDisableAccentBackdrop(Handle);
                NativeMethods.TryApplyWindows11Backdrop(
                    Handle,
                    PopupBackdropKind.None);
                return;
            }

            effectiveVisualMode = PopupVisualMode.Glass;
            BackColor = Color.FromArgb(244, 247, 250);
            extendFrameApplied = false;
            NativeMethods.TryDisableAccentBackdrop(Handle);
            backdropApplied = TryApplyBackdrop(PopupBackdropKind.Acrylic) ||
                TryApplyBackdrop(PopupBackdropKind.MicaAlt) ||
                TryApplyBackdrop(PopupBackdropKind.Mica);
            // Keep Accent Acrylic disabled on the default path. It works at
            // the whole-window composition layer and can contaminate WinForms
            // GDI text. If DWM backdrop alone is visually weak, the card tint
            // still gives a safe Windows-11-like layer without whitening text.
            accentBackdropApplied = false;
            if (!backdropApplied)
            {
                appliedBackdropKind = PopupBackdropKind.None;
            }
        }

        private bool TryApplyBackdrop(PopupBackdropKind kind)
        {
            if (NativeMethods.TryApplyWindows11Backdrop(Handle, kind))
            {
                appliedBackdropKind = kind;
                extendFrameApplied = NativeMethods.LastExtendFrameApplied;
                return true;
            }
            return false;
        }

        private static GraphicsPath CreateRoundedPath(
            Rectangle rectangle,
            int radius)
        {
            var diameter = Math.Max(1, radius * 2);
            var right = rectangle.Right - 1;
            var bottom = rectangle.Bottom - 1;
            var path = new GraphicsPath();
            path.AddArc(
                rectangle.Left,
                rectangle.Top,
                diameter,
                diameter,
                180,
                90);
            path.AddArc(
                right - diameter,
                rectangle.Top,
                diameter,
                diameter,
                270,
                90);
            path.AddArc(
                right - diameter,
                bottom - diameter,
                diameter,
                diameter,
                0,
                90);
            path.AddArc(
                rectangle.Left,
                bottom - diameter,
                diameter,
                diameter,
                90,
                90);
            path.CloseFigure();
            return path;
        }
    }
}
