// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Drawing;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class PopupForm : Form
    {
        // The popup is intentionally persistent. It closes only after the user
        // clicks it to open WeChat, or exits/pauses the notifier.
        private readonly Action activateWeChat;
        private readonly Label titleLabel;
        private readonly Label bodyLabel;

        internal PopupForm(string contact, string preview, Action activateWeChat)
        {
            this.activateWeChat = activateWeChat;
            ContactKey = contact;

            Width = 380;
            Height = 118;
            FormBorderStyle = FormBorderStyle.None;
            StartPosition = FormStartPosition.Manual;
            ShowInTaskbar = false;
            TopMost = true;
            BackColor = Color.FromArgb(248, 250, 252);
            Padding = new Padding(16, 12, 16, 12);
            Opacity = 0.98;

            var accent = new Panel
            {
                Dock = DockStyle.Left,
                Width = 5,
                BackColor = Color.FromArgb(7, 193, 96)
            };

            titleLabel = new Label
            {
                AutoEllipsis = true,
                AutoSize = false,
                Font = new Font("Microsoft YaHei UI", 11F, FontStyle.Bold),
                ForeColor = Color.FromArgb(31, 41, 55),
                Location = new Point(24, 13),
                Size = new Size(335, 27),
                Text = contact
            };

            bodyLabel = new Label
            {
                AutoEllipsis = true,
                AutoSize = false,
                Font = new Font("Microsoft YaHei UI", 9.5F, FontStyle.Regular),
                ForeColor = Color.FromArgb(75, 85, 99),
                Location = new Point(24, 44),
                Size = new Size(335, 55),
                Text = preview
            };

            Controls.Add(accent);
            Controls.Add(titleLabel);
            Controls.Add(bodyLabel);

            Click += OnPopupClick;
            titleLabel.Click += OnPopupClick;
            bodyLabel.Click += OnPopupClick;
            accent.Click += OnPopupClick;

            Shown += delegate { EnsureTopMost(); };
        }

        internal string ContactKey { get; private set; }

        internal void UpdateMessage(string contact, string preview)
        {
            ContactKey = contact;
            titleLabel.Text = contact;
            bodyLabel.Text = preview;
            Opacity = 0.98;
            EnsureTopMost();
        }

        internal void EnsureTopMost()
        {
            if (!IsHandleCreated || IsDisposed)
            {
                return;
            }

            NativeMethods.SetWindowPos(
                Handle,
                NativeMethods.HwndTopmost,
                Left,
                Top,
                0,
                0,
                NativeMethods.SwpNoSize |
                NativeMethods.SwpNoActivate |
                NativeMethods.SwpShowWindow);
        }

        protected override bool ShowWithoutActivation
        {
            get { return true; }
        }

        protected override CreateParams CreateParams
        {
            get
            {
                const int WsExToolWindow = 0x00000080;
                const int WsExNoActivate = 0x08000000;
                var parameters = base.CreateParams;
                // WS_EX_NOACTIVATE keeps the notification from stealing focus
                // from games, video, or the user's current full-screen app.
                parameters.ExStyle |= WsExToolWindow | WsExNoActivate;
                return parameters;
            }
        }

        private void OnPopupClick(object sender, EventArgs eventArgs)
        {
            if (activateWeChat != null)
            {
                activateWeChat();
            }
            Close();
        }
    }
}
