// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal static class Program
    {
        internal const string ActivationEventName =
            "Local\\WeChatMessageNotifier.ToastActivation";
        private const string ProtocolName = "wechat-message-notifier://";

        // The application uses a named mutex so only one tray monitor can run
        // for the current Windows session.
        [STAThread]
        private static int Main(string[] args)
        {
            var toastActivation = HasToastActivationArgument(args);
            if (toastActivation)
            {
                try
                {
                    using (var existingEvent = EventWaitHandle.OpenExisting(
                        ActivationEventName))
                    {
                        WriteActivationPayload(args);
                        existingEvent.Set();
                        return 0;
                    }
                }
                catch (WaitHandleCannotBeOpenedException)
                {
                    // No notifier is running yet. Continue startup and seed
                    // the activation event so the new instance opens WeChat.
                    WriteActivationPayload(args);
                }
            }

            if (args.Length > 0 && string.Equals(args[0], "--self-test", StringComparison.OrdinalIgnoreCase))
            {
                return SelfTests.Run();
            }

            if (args.Length > 0 && string.Equals(args[0], "--integration-test", StringComparison.OrdinalIgnoreCase))
            {
                return RunIntegrationTest();
            }

            bool createdNew;
            using (var mutex = new Mutex(true, "Local\\WeChatMessageNotifier.Singleton", out createdNew))
            using (var activationEvent = new EventWaitHandle(
                toastActivation,
                EventResetMode.AutoReset,
                ActivationEventName))
            {
                if (!createdNew)
                {
                    MessageBox.Show(
                        "微信消息提醒器已经在运行。",
                        "微信消息提醒器",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Information);
                    return 0;
                }

                // This project is built with the .NET Framework csc.exe, so
                // Application.SetHighDpiMode is not available. Per-monitor
                // DPI awareness is declared in app.manifest and the popup UI
                // scales its own WinForms sizes from the active monitor DPI.
                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                Application.Run(new NotifierApplicationContext(args, activationEvent));
                return 0;
            }
        }

        private static bool HasToastActivationArgument(string[] args)
        {
            foreach (var value in args)
            {
                if (string.Equals(
                        value,
                        "--toast-activate",
                        StringComparison.OrdinalIgnoreCase) ||
                    value.StartsWith(
                        ProtocolName,
                        StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        internal static ToastActivationRequest ReadActivationPayload()
        {
            try
            {
                var path = GetActivationPayloadPath();
                if (!File.Exists(path))
                {
                    return null;
                }

                var value = File.ReadAllText(path, Encoding.UTF8);
                File.Delete(path);
                ToastActivationRequest request;
                if (ToastActivationRequest.TryParseJson(value, out request))
                {
                    return request;
                }

                // Compatibility with payloads produced before v2.5. The
                // legacy file contained the stable session key only.
                return string.IsNullOrWhiteSpace(value)
                    ? null
                    : ToastActivationRequest.FromSession(
                        value.Trim(),
                        ChatSessionKind.Unknown);
            }
            catch
            {
                return null;
            }
        }

        internal static ToastActivationRequest ExtractToastActivationRequest(string[] args)
        {
            if (args == null)
            {
                return null;
            }

            foreach (var value in args)
            {
                if (value != null &&
                    value.StartsWith(
                        ProtocolName,
                        StringComparison.OrdinalIgnoreCase))
                {
                    return ExtractRequestFromUri(value);
                }
            }
            return null;
        }

        internal static string ExtractToastActivationSessionKey(string[] args)
        {
            var request = ExtractToastActivationRequest(args);
            return request == null ? null : request.SessionKey;
        }

        private static void WriteActivationPayload(string[] args)
        {
            var request = ExtractToastActivationRequest(args);
            if (request == null || string.IsNullOrWhiteSpace(request.SessionKey))
            {
                return;
            }

            try
            {
                var path = GetActivationPayloadPath();
                Directory.CreateDirectory(Path.GetDirectoryName(path));
                var temporary = path + ".tmp";
                File.WriteAllText(temporary, request.ToJson(), new UTF8Encoding(true));
                if (File.Exists(path))
                {
                    File.Replace(temporary, path, null);
                }
                else
                {
                    File.Move(temporary, path);
                }
            }
            catch
            {
                // Toast activation must never fail just because the transient
                // payload file could not be written. The running instance will
                // still open WeChat without a target session.
            }
        }

        private static ToastActivationRequest ExtractRequestFromUri(string value)
        {
            try
            {
                var uri = new Uri(value);
                var query = uri.Query;
                if (string.IsNullOrEmpty(query))
                {
                    return null;
                }

                if (query.StartsWith("?", StringComparison.Ordinal))
                {
                    query = query.Substring(1);
                }

                string sessionKey = null;
                ChatSessionKind kind = ChatSessionKind.Unknown;
                ToastActivationRoute route = ToastActivationRoute.MainSession;
                foreach (var pair in query.Split('&'))
                {
                    var parts = pair.Split(new[] { '=' }, 2);
                    if (parts.Length == 2 &&
                        string.Equals(
                            parts[0],
                            "session",
                            StringComparison.OrdinalIgnoreCase))
                    {
                        sessionKey = Uri.UnescapeDataString(parts[1].Replace("+", " "));
                    }
                    else if (parts.Length == 2 && string.Equals(parts[0], "kind", StringComparison.OrdinalIgnoreCase))
                    {
                        Enum.TryParse(Uri.UnescapeDataString(parts[1]), true, out kind);
                    }
                    else if (parts.Length == 2 && string.Equals(parts[0], "route", StringComparison.OrdinalIgnoreCase))
                    {
                        Enum.TryParse(Uri.UnescapeDataString(parts[1]), true, out route);
                    }
                }
                return string.IsNullOrWhiteSpace(sessionKey)
                    ? null
                    : new ToastActivationRequest(sessionKey, kind, route);
            }
            catch
            {
                return null;
            }

        }

        private static string GetActivationPayloadPath()
        {
            return Path.Combine(
                Environment.GetFolderPath(
                    Environment.SpecialFolder.LocalApplicationData),
                "WeChatMessageNotifier",
                "toast-activation.txt");
        }

        private static int RunIntegrationTest()
        {
            try
            {
                var logger = new Logger();
                var monitor = new WeChatMonitor(logger);
                monitor.Poll();
                if (monitor.MainWindow == IntPtr.Zero || monitor.LastSessionCount == 0)
                {
                    Console.WriteLine("INTEGRATION-TEST FAILED: WeChat session list was not found.");
                    return 1;
                }

                Console.WriteLine(
                    "INTEGRATION-TEST PASSED: sessionCount=" + monitor.LastSessionCount +
                    " selectedCount=" + monitor.LastSelectedSessionCount +
                    " groupMarkerCount=" + monitor.LastGroupMarkerCount +
                    " direct=" + monitor.GetLastSessionKindCount(ChatSessionKind.DirectContact) +
                    " official=" + monitor.GetLastSessionKindCount(ChatSessionKind.OfficialAccount) +
                    " service=" + monitor.GetLastSessionKindCount(ChatSessionKind.ServiceAccount) +
                    " group=" + monitor.GetLastSessionKindCount(ChatSessionKind.GroupChat) +
                    " unknown=" + monitor.GetLastSessionKindCount(ChatSessionKind.Unknown) +
                    " contentWasNotPrinted=true");
                return 0;
            }
            catch (Exception exception)
            {
                Console.WriteLine("INTEGRATION-TEST FAILED: " + exception.GetType().Name + ": " + exception.Message);
                return 1;
            }
        }
    }
}
