// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Threading;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal static class Program
    {
        internal const string ActivationEventName =
            "Local\\WeChatMessageNotifier.ToastActivation";

        // The application uses a named mutex so only one tray monitor can run
        // for the current Windows session.
        [STAThread]
        private static int Main(string[] args)
        {
            var toastActivation = HasToastActivationArgument(args);
            if (toastActivation)
            {
                try
                {
                    using (var existingEvent = EventWaitHandle.OpenExisting(
                        ActivationEventName))
                    {
                        existingEvent.Set();
                        return 0;
                    }
                }
                catch (WaitHandleCannotBeOpenedException)
                {
                    // No notifier is running yet. Continue startup and seed
                    // the activation event so the new instance opens WeChat.
                }
            }

            if (args.Length > 0 && string.Equals(args[0], "--self-test", StringComparison.OrdinalIgnoreCase))
            {
                return SelfTests.Run();
            }

            if (args.Length > 0 && string.Equals(args[0], "--integration-test", StringComparison.OrdinalIgnoreCase))
            {
                return RunIntegrationTest();
            }

            bool createdNew;
            using (var mutex = new Mutex(true, "Local\\WeChatMessageNotifier.Singleton", out createdNew))
            using (var activationEvent = new EventWaitHandle(
                toastActivation,
                EventResetMode.AutoReset,
                ActivationEventName))
            {
                if (!createdNew)
                {
                    MessageBox.Show(
                        "微信消息提醒器已经在运行。",
                        "微信消息提醒器",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Information);
                    return 0;
                }

                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                Application.Run(new NotifierApplicationContext(args, activationEvent));
                return 0;
            }
        }

        private static bool HasToastActivationArgument(string[] args)
        {
            foreach (var value in args)
            {
                if (string.Equals(
                        value,
                        "--toast-activate",
                        StringComparison.OrdinalIgnoreCase) ||
                    value.StartsWith(
                        "wechat-message-notifier://",
                        StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        private static int RunIntegrationTest()
        {
            try
            {
                var logger = new Logger();
                var monitor = new WeChatMonitor(logger);
                monitor.Poll();
                if (monitor.MainWindow == IntPtr.Zero || monitor.LastSessionCount == 0)
                {
                    Console.WriteLine("INTEGRATION-TEST FAILED: WeChat session list was not found.");
                    return 1;
                }

                Console.WriteLine(
                    "INTEGRATION-TEST PASSED: sessionCount=" + monitor.LastSessionCount +
                    " contentWasNotPrinted=true");
                return 0;
            }
            catch (Exception exception)
            {
                Console.WriteLine("INTEGRATION-TEST FAILED: " + exception.GetType().Name + ": " + exception.Message);
                return 1;
            }
        }
    }
}
