// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

namespace WeChatMessageNotifier
{
    // Regression coverage for the Windows-notification-only architecture.
    internal static class SelfTests
    {
        internal static int Run()
        {
            var failures = new List<string>();
            TestClassification(failures);
            TestNotificationPolicy(failures);
            TestServiceAccountPageClassification(failures);
            TestChangeDetection(failures);
            TestOutgoingFilter(failures);
            TestNotificationAggregation(failures);
            TestSettings(failures);
            TestPollingIntervals(failures);
            TestVisualSafety(failures);
            TestToastRequest(failures);
            TestToastIconFallback(failures);

            if (failures.Count == 0)
            {
                Console.WriteLine("SELF-TEST PASSED");
                return 0;
            }
            Console.WriteLine("SELF-TEST FAILED");
            foreach (var failure in failures) Console.WriteLine("- " + failure);
            return 1;
        }

        private static void TestClassification(ICollection<string> failures)
        {
            var group = SessionParser.Parse(
                "\u7FA4\u804A\n\u6D88\u606F\n14:58",
                0,
                "session_item_room@chatroom");
            Expect(group != null && group.Kind == ChatSessionKind.GroupChat,
                "Stable group identity was not classified as GroupChat.", failures);
            Expect(group.ContactHash.Length == 16,
                "New contact hashes are not 16 hexadecimal characters.", failures);

            var groupByName = SessionParser.Parse(
                "\u56E2\u8D2D\u7FA4\n\u6D88\u606F\n14:58",
                0,
                "session_item_no_stable_group_identity");
            Expect(groupByName != null &&
                groupByName.Kind == ChatSessionKind.GroupChat &&
                groupByName.HasGroupMarker,
                "A session name containing 群 was not classified as GroupChat.",
                failures);

            var unknown = SessionParser.Parse(
                "\u672A\u6807\u8BB0\u4F1A\u8BDD\n\u6D88\u606F\n10:00",
                0,
                "session_item_wxid_unknown");
            Expect(unknown != null && unknown.Kind == ChatSessionKind.Unknown,
                "Unlabeled session was not kept as Unknown.", failures);

            var official = SessionParser.Parse(
                "\u8D26\u53F7\n\u6D88\u606F\n10:00",
                0,
                "session_item_gh_123456");
            Expect(official != null && official.Kind == ChatSessionKind.OfficialAccount,
                "Official-account identity was not recognized.", failures);
        }

        private static void TestNotificationPolicy(ICollection<string> failures)
        {
            var settings = new NotificationFilterSettings();
            var official = CreateSession("1111111111111111", ChatSessionKind.OfficialAccount);
            settings.SetNotificationOverride(
                official.ContactHash,
                SessionNotificationOverride.Allow);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, official),
                "OfficialAccount notified without an allow keyword.", failures);

            var overriddenOfficial = CreateSession(
                "1212121212121212",
                ChatSessionKind.Unknown);
            settings.SetOverride(
                overriddenOfficial.ContactHash,
                ChatSessionKind.OfficialAccount);
            settings.SetNotificationOverride(
                overriddenOfficial.ContactHash,
                SessionNotificationOverride.Allow);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(
                    settings,
                    overriddenOfficial),
                "Kind override to OfficialAccount notified without a keyword.", failures);

            settings.OfficialAccountAllowKeywords.Add("AA");
            settings.OfficialAccountAllowKeywords.Add("AB");
            official.Preview = "message AA matched";
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, official),
                "OfficialAccount keyword AA did not allow notification.", failures);
            official.Preview = "message AB matched";
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, official),
                "OfficialAccount keyword AB did not allow notification.", failures);
            official.Preview = "message did not match";
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, official),
                "OfficialAccount notified without a matching keyword.", failures);

            var service = CreateSession("2222222222222222", ChatSessionKind.ServiceAccount);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, service),
                "ServiceAccount default policy was not blocked.", failures);
            settings.SetNotificationOverride(
                service.ContactHash,
                SessionNotificationOverride.Allow);
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, service),
                "Explicitly allowed ServiceAccount did not notify.", failures);
            settings.ServiceAccountAllowKeywords.Add("AA");
            service.Preview = "message AA matched";
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, service),
                "ServiceAccount allow keyword AA did not allow notification.", failures);
            service.Preview = "message did not match";
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, service),
                "Explicitly allowed ServiceAccount did not remain allowed.", failures);
            settings.SetNotificationOverride(
                service.ContactHash,
                SessionNotificationOverride.Block);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, service),
                "Blocked ServiceAccount notified.", failures);

            var keywordOnlyService = CreateSession(
                "2323232323232323",
                ChatSessionKind.ServiceAccount);
            keywordOnlyService.Preview = "message AA matched";
            Expect(NotifierApplicationContext.ShouldDeliverNotification(
                    settings,
                    keywordOnlyService),
                "ServiceAccount keyword did not allow a default-blocked session.", failures);

            var group = CreateSession("3333333333333333", ChatSessionKind.GroupChat);
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, group),
                "GroupChat default policy was not allowed.", failures);
            settings.SetNotificationOverride(
                group.ContactHash,
                SessionNotificationOverride.Block);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, group),
                "Blocked GroupChat notified.", failures);
            settings.SetNotificationOverride(
                group.ContactHash,
                SessionNotificationOverride.Allow);
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, group),
                "Allowed GroupChat did not notify.", failures);
            settings.GroupChatBlockKeywords.Add("\u56E2\u8D2D");
            group.Contact = "\u56E2\u8D2D\u7FA4";
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, group),
                "GroupChat name keyword did not override an Allow rule.", failures);

            var direct = CreateSession("4444444444444444", ChatSessionKind.DirectContact);
            var unknown = CreateSession("5555555555555555", ChatSessionKind.Unknown);
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, direct),
                "DirectContact default policy was not allowed.", failures);
            Expect(NotifierApplicationContext.ShouldDeliverNotification(settings, unknown),
                "Unknown default policy was not allowed.", failures);
            settings.SetNotificationOverride(
                unknown.ContactHash,
                SessionNotificationOverride.Block);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, unknown),
                "Blocked Unknown notified.", failures);

            var diagnosticSession = CreateSession(
                "5656565656565656",
                ChatSessionKind.GroupChat);
            diagnosticSession.Contact = "Private Contact";
            diagnosticSession.Preview = "Private message";
            var diagnostic = NotifierApplicationContext.FormatCandidateDiagnostic(
                diagnosticSession,
                NotifierApplicationContext.EvaluateNotification(
                    settings,
                    diagnosticSession));
            Expect(diagnostic.IndexOf("Private", StringComparison.Ordinal) < 0 &&
                diagnostic.IndexOf("ContactHash=", StringComparison.Ordinal) >= 0 &&
                diagnostic.IndexOf("GroupChatDefaultAllowed", StringComparison.Ordinal) >= 0,
                "Candidate diagnostic leaked content or omitted policy reason.", failures);
        }

        private static void TestServiceAccountPageClassification(
            ICollection<string> failures)
        {
            var row = CreateSession("6666666666666666", ChatSessionKind.Unknown);
            WeChatMonitor.ApplySourcePageClassification(
                row,
                WeChatPageKind.ServiceAccountList);
            Expect(row.DetectedKind == ChatSessionKind.ServiceAccount &&
                row.Kind == ChatSessionKind.ServiceAccount,
                "ServiceAccountList row was not classified as ServiceAccount.", failures);

            var settings = new NotificationFilterSettings();
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, row),
                "ServiceAccountList row was not blocked by default.", failures);

            var aggregate = CreateSession("7777777777777777", ChatSessionKind.ServiceAccount);
            settings.SetNotificationOverride(
                row.ContactHash,
                SessionNotificationOverride.Allow);
            Expect(!NotifierApplicationContext.ShouldDeliverNotification(settings, aggregate),
                "Allowed concrete service session opened an aggregate entry.", failures);
        }

        private static void TestChangeDetection(ICollection<string> failures)
        {
            var detector = new SessionChangeDetector();
            var now = new DateTime(2026, 7, 16, 10, 0, 0);
            var baseline = SessionParser.Parse("\u8054\u7CFB\u4EBA\n\u65E7\u6D88\u606F\n10:00", 0);
            Expect(detector.Update(new[] { baseline }, now).Count == 0,
                "Initial scan produced a notification.", failures);
            var changed = SessionParser.Parse("\u8054\u7CFB\u4EBA\n\u65B0\u6D88\u606F\n10:01", 0);
            Expect(detector.Update(new[] { changed }, now.AddMinutes(1)).Count == 1,
                "Incoming summary change was not detected.", failures);
            Expect(detector.Update(new[] { changed }, now.AddMinutes(2)).Count == 0,
                "Duplicate message was not suppressed.", failures);
        }

        private static void TestOutgoingFilter(ICollection<string> failures)
        {
            Expect(SessionParser.LooksLikeOutgoing("\u6211: \u597D\u7684") &&
                SessionParser.LooksLikeOutgoing("You: ok") &&
                SessionParser.LooksLikeOutgoing("\u6211 [\u56FE\u7247]"),
                "Outgoing summary recognition regressed.", failures);
            Expect(!SessionParser.LooksLikeOutgoing("\u4F60\u597D\uFF0C\u6211\u6765\u4E86"),
                "Incoming content was treated as outgoing.", failures);
        }

        private static void TestNotificationAggregation(ICollection<string> failures)
        {
            var path = Path.Combine(Path.GetTempPath(), "WechatNotifierTest-" + Guid.NewGuid().ToString("N"));
            try
            {
                var logger = new Logger(path, 4096);
                using (var center = new WindowsNotificationCenter(
                    delegate(string ignored) { }, logger, false, false))
                {
                    Expect(center.ShowMessage("session-a", "A", "one", false, false) == 1 &&
                        center.ShowMessage("session-a", "A", "two", false, false) == 2,
                        "Same-session notifications did not aggregate.", failures);
                    center.ClearSession("session-a");
                    Expect(center.GetMessageCountForTest("session-a") == 0 &&
                        center.ShowMessage("session-a", "A", "three", false, false) == 1,
                        "Successful activation did not reset notification count.", failures);
                }
            }
            finally
            {
                if (Directory.Exists(path)) Directory.Delete(path, true);
            }
        }

        private static void TestSettings(ICollection<string> failures)
        {
            var settings = new NotificationFilterSettings();
            settings.SetOverride("a1b2c3d4e5f60708", ChatSessionKind.GroupChat);
            settings.SetNotificationOverride(
                "1020304050607080",
                SessionNotificationOverride.Block);
            settings.ServiceAccountAllowKeywords.Add("AA");
            settings.OfficialAccountAllowKeywords.Add("AA");
            settings.OfficialAccountAllowKeywords.Add("AB");
            settings.GroupChatBlockKeywords.Add("\u56E2\u8D2D");
            settings.PrivacyMode = true;
            settings.SetSettingsWindowPlacement(
                new System.Drawing.Rectangle(-1200, 80, 820, 680),
                true,
                144);
            NotificationFilterSettings parsed;
            Expect(NotificationFilterSettings.TryParse(settings.ToJson(), out parsed) &&
                parsed.ResolveKind("a1b2c3d4e5f60708", ChatSessionKind.Unknown) == ChatSessionKind.GroupChat &&
                parsed.ResolveNotificationOverride("1020304050607080") == SessionNotificationOverride.Block &&
                parsed.HasServiceAccountAllowKeyword("notice AA") &&
                parsed.HasOfficialAccountAllowKeyword("notice AB") &&
                parsed.HasGroupChatBlockKeyword("\u56E2\u8D2D\u7FA4"),
                "New session settings did not round-trip.", failures);
            Expect(parsed.PrivacyMode,
                "Persistent privacy mode did not round-trip.", failures);
            Expect(parsed.SettingsWindowBounds.HasValue &&
                parsed.SettingsWindowBounds.Value.X == -1200 &&
                parsed.SettingsWindowBounds.Value.Width == 820 &&
                parsed.SettingsWindowMaximized &&
                parsed.SettingsWindowDpi == 144,
                "Settings window placement did not round-trip.", failures);
            Expect(settings.ToJson().IndexOf("\"enable", StringComparison.OrdinalIgnoreCase) < 0,
                "Retired global type switches were persisted.", failures);
            var cloned = settings.Clone();
            Expect(cloned.HasGroupChatBlockKeyword("\u56E2\u8D2D\u7FA4") &&
                cloned.HasOfficialAccountAllowKeyword("notice AB"),
                "Settings clone did not preserve keyword rules.", failures);

            var legacyProperty = "enable" + "ServiceAccount";
            var legacy = "{\"" + legacyProperty + "\":true,\"sessionKindOverrides\":{" +
                "\"a1b2c3d4\":\"GroupChat\"}}";
            Expect(NotificationFilterSettings.TryParse(legacy, out parsed) &&
                parsed.ResolveKind("a1b2c3d4ffffffff", ChatSessionKind.Unknown) == ChatSessionKind.GroupChat &&
                parsed.ToJson().IndexOf("\"enable", StringComparison.OrdinalIgnoreCase) < 0,
                "Legacy settings did not preserve a valid kind override safely.", failures);

            var tempPath = Path.Combine(Path.GetTempPath(), "WechatNotifierSettings-" + Guid.NewGuid().ToString("N"), "settings.json");
            try
            {
                var store = new SettingsStore(new Logger(Path.GetDirectoryName(tempPath), 4096), tempPath);
                Expect(store.Save(settings), "Settings store did not save.", failures);
                var bytes = File.ReadAllBytes(tempPath);
                Expect(bytes.Length < 3 || bytes[0] != 0xef || bytes[1] != 0xbb || bytes[2] != 0xbf,
                    "Settings file unexpectedly used a UTF-8 BOM.", failures);
                settings.PrivacyMode = false;
                Expect(store.Save(settings) && File.Exists(store.BackupPath),
                    "Settings store did not create an atomic-save backup.", failures);
                NotificationFilterSettings backup;
                Expect(NotificationFilterSettings.TryParse(
                        File.ReadAllText(store.BackupPath, Encoding.UTF8),
                        out backup) && backup.PrivacyMode,
                    "Settings backup did not retain the previous valid configuration.",
                    failures);
                File.WriteAllText(tempPath, "{invalid", Encoding.UTF8);
                Expect(store.Load().PrivacyMode,
                    "Invalid primary settings did not recover the local backup.", failures);
            }
            finally
            {
                var directory = Path.GetDirectoryName(tempPath);
                if (Directory.Exists(directory)) Directory.Delete(directory, true);
            }
        }

        private static void TestPollingIntervals(ICollection<string> failures)
        {
            Expect(NotifierApplicationContext.SelectPollInterval(true, 1) ==
                    NotifierApplicationContext.ActivePollIntervalMilliseconds &&
                NotifierApplicationContext.SelectPollInterval(false, 0) ==
                    NotifierApplicationContext.IdlePollIntervalMilliseconds &&
                NotifierApplicationContext.SelectPollInterval(true, 0) ==
                    NotifierApplicationContext.IdlePollIntervalMilliseconds,
                "Adaptive polling intervals were not selected correctly.", failures);
        }

        private static void TestVisualSafety(ICollection<string> failures)
        {
            Expect(NotifierApplicationContext.UsesWinUiSettingsRuntime &&
                NotifierApplicationContext.UsesWinUiTrayRuntime &&
                !NotifierApplicationContext.UsesCustomTrayMenuRuntime,
                "The production path did not select the WinUI settings and tray surfaces.",
                failures);

            var secondary = Win11Visual.ForceOpaque(
                System.Drawing.Color.FromArgb(64, 100, 116, 139));
            var healthy = Win11Visual.ForceOpaque(
                System.Drawing.Color.FromArgb(16, 22, 101, 52));
            Expect(secondary.A == 255 && secondary.R == 100 &&
                    secondary.G == 116 && secondary.B == 139 &&
                    healthy.A == 255 && healthy.R == 22 &&
                    healthy.G == 101 && healthy.B == 52,
                "EnsureOpaqueText helper changed semantic text RGB values.", failures);

            Expect(SettingsForm.UsesStableNativeTextControls &&
                SettingsForm.UsesNoCustomCardPainting &&
                SettingsForm.UsesFrameworkDpiAutoScale &&
                typeof(SettingsForm).GetField(
                    "keywordCards",
                    BindingFlags.Instance | BindingFlags.NonPublic) == null &&
                typeof(NativeMethods).GetMethod(
                    "DwmExtendFrameIntoClientArea",
                    BindingFlags.Static | BindingFlags.NonPublic) == null,
                "Settings did not use the stable native-control/DPI rendering path.",
                failures);

            Expect(NotifierApplicationContext.UsesWinUiTrayRuntime &&
                !NotifierApplicationContext.UsesCustomTrayMenuRuntime &&
                Win11BackdropForm.UsesStableClientErase,
                "The backend did not keep the WinUI tray surface as its only production menu path.",
                failures);

            try
            {
                // Layout can briefly paint a card at a 1- or 2-pixel size.
                // The round-rectangle helper must never pass an oversized arc
                // to GDI+ during that transition.
                using (var tinyPath = Win11Visual.CreateRoundRect(
                    new System.Drawing.Rectangle(0, 0, 1, 1), 10))
                using (var narrowPath = Win11Visual.CreateRoundRect(
                    new System.Drawing.Rectangle(0, 0, 8, 3), 10))
                {
                    Expect(tinyPath.PointCount > 0 && narrowPath.PointCount > 0,
                        "Round-rectangle fallback did not create a safe paint path.",
                        failures);
                }
            }
            catch (Exception exception)
            {
                Expect(false,
                    "Round-rectangle fallback threw " + exception.GetType().Name + ".",
                    failures);
            }

            var settingsLayoutSelfTest = SettingsForm.RunLayoutStructureSelfTest();
            var settingsDpiSelfTest = SettingsForm.RunDpiAndEditorSelfTest();
            var settingsSurfaceSmokeTest = SettingsForm.RunNativeSurfaceSmokeTest();
            Expect(SettingsForm.UsesResponsiveLayout &&
                SettingsForm.IsResizable &&
                SettingsForm.HandlesPerMonitorDpiChanges &&
                SettingsForm.UsesStableNativeTextControls &&
                SettingsForm.UsesSingleConstructionPath &&
                SettingsForm.UsesScrollableContent &&
                SettingsForm.FooterIsOutsideScrollContent &&
                SettingsForm.UsesTableLayoutRoot &&
                SettingsForm.UsesOpaqueClientContainers &&
                SettingsForm.UsesForcedDpiMetricRefresh &&
                SettingsForm.UsesFrameworkDpiAutoScale &&
                SettingsForm.UsesNoCustomCardPainting &&
                SettingsForm.UsesExplicitEditableKeywordEditors &&
                SettingsForm.UsesStableFooterButtonTable &&
                SettingsForm.MinimumLogicalSize.Width >= 680 &&
                SettingsForm.MinimumLogicalSize.Height >= 620 &&
                settingsLayoutSelfTest &&
                settingsDpiSelfTest &&
                settingsSurfaceSmokeTest &&
                Win11BackdropForm.ReappliesBackdropForDpiAndScreenChanges &&
                ActivityLogForm.UsesResponsiveLayout &&
                ActivityLogForm.HandlesPerMonitorDpiChanges &&
                ActivityLogForm.UsesStableNativeTextControls &&
                typeof(NativeMethods).GetMethod(
                    "GetWindowDpiOrDefault",
                    BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public) != null,
                "Settings or activity window did not use the responsive, resizable layout path.",
                failures);

            Expect(typeof(NativeMethods).GetMethod(
                    "TryApplyWindows11Acrylic",
                    BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public) == null,
                "The retired generic AccentPolicy path remained available.",
                failures);
            Expect(typeof(NativeMethods).GetMethod(
                    "TryApplyLightTrayAcrylic",
                    BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public) != null,
                "The dedicated light Acrylic tray path was unavailable.",
                failures);
        }

        private static void TestToastRequest(ICollection<string> failures)
        {
            var original = ToastActivationRequest.FromSession(
                "session-a", ChatSessionKind.GroupChat);
            ToastActivationRequest parsed;
            Expect(ToastActivationRequest.TryParseJson(original.ToJson(), out parsed) &&
                parsed.SessionKey == "session-a" &&
                parsed.SessionKind == ChatSessionKind.GroupChat,
                "Toast activation request did not round-trip.", failures);
        }

        private static void TestToastIconFallback(ICollection<string> failures)
        {
            var cachedLogoPath = Path.Combine(
                Path.GetTempPath(),
                "WeChatMessageNotifier-" + Guid.NewGuid().ToString("N") + ".png");
            try
            {
                File.WriteAllBytes(cachedLogoPath, new byte[] { 0 });
                Expect(string.Equals(
                        WindowsNotificationCenter.SelectExistingToastLogoForTest(
                            null,
                            cachedLogoPath),
                        cachedLogoPath,
                        StringComparison.OrdinalIgnoreCase),
                    "Cached toast logo was not retained when WeChat was unavailable.",
                    failures);
                Expect(WindowsNotificationCenter.SelectExistingToastLogoForTest(
                           null,
                           cachedLogoPath + ".missing") == null,
                    "Missing cached toast logo was treated as available.",
                    failures);
            }
            finally
            {
                if (File.Exists(cachedLogoPath)) File.Delete(cachedLogoPath);
            }
        }

        private static ChatSession CreateSession(
            string hash,
            ChatSessionKind kind)
        {
            return new ChatSession
            {
                ContactHash = hash,
                DetectedKind = kind,
                Kind = kind,
                SessionKey = "session-" + hash,
                Contact = "Test",
                Preview = "Test"
            };
        }

        private static void Expect(bool condition, string message, ICollection<string> failures)
        {
            if (!condition) failures.Add(message);
        }
    }
}
