// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;

namespace WeChatMessageNotifier
{
    internal static class SelfTests
    {
        // These tests avoid external frameworks so they can run with only the
        // .NET Framework compiler included with Windows.
        internal static int Run()
        {
            var failures = new List<string>();
            TestParser(failures);
            TestChangeDetection(failures);
            TestOutgoingFilter(failures);

            if (failures.Count == 0)
            {
                Console.WriteLine("SELF-TEST PASSED");
                return 0;
            }

            Console.WriteLine("SELF-TEST FAILED");
            foreach (var failure in failures)
            {
                Console.WriteLine("- " + failure);
            }
            return 1;
        }

        private static void TestParser(ICollection<string> failures)
        {
            var session = SessionParser.Parse(
                "联系人甲\n已置顶\n这是消息内容\n12:34\n消息免打扰\n",
                0);

            Expect(session != null, "Parser returned null.", failures);
            if (session == null)
            {
                return;
            }
            Expect(session.Contact == "联系人甲", "Contact parsing failed.", failures);
            Expect(session.Preview == "这是消息内容", "Preview parsing failed.", failures);
            Expect(session.Timestamp == "12:34", "Timestamp parsing failed.", failures);
        }

        private static void TestChangeDetection(ICollection<string> failures)
        {
            var detector = new SessionChangeDetector();
            var baseline = SessionParser.Parse("联系人甲\n旧消息\n12:30", 0);
            var first = detector.Update(new[] { baseline }, new DateTime(2026, 6, 29, 12, 30, 0));
            Expect(first.Count == 0, "Initial baseline generated a notification.", failures);

            var changed = SessionParser.Parse("联系人甲\n新消息\n12:31", 0);
            var second = detector.Update(new[] { changed }, new DateTime(2026, 6, 29, 12, 31, 0));
            Expect(second.Count == 1, "Changed session was not detected.", failures);

            var third = detector.Update(new[] { changed }, new DateTime(2026, 6, 29, 12, 31, 10));
            Expect(third.Count == 0, "Duplicate session generated a notification.", failures);
        }

        private static void TestOutgoingFilter(ICollection<string> failures)
        {
            Expect(SessionParser.LooksLikeOutgoing("我: 好的"), "Outgoing Chinese colon was not detected.", failures);
            Expect(SessionParser.LooksLikeOutgoing("You: okay"), "Outgoing English prefix was not detected.", failures);
            Expect(!SessionParser.LooksLikeOutgoing("对方: 好的"), "Incoming message was classified as outgoing.", failures);
        }

        private static void Expect(bool condition, string message, ICollection<string> failures)
        {
            if (!condition)
            {
                failures.Add(message);
            }
        }
    }
}
