// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace WeChatMessageNotifier
{
    internal static class SessionParser
    {
        private static readonly Regex ClockPattern = new Regex(
            @"^(?:[01]?\d|2[0-3]):[0-5]\d$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex DatePattern = new Regex(
            @"^(?:\d{1,2}/\d{1,2}|昨天|前天|星期[一二三四五六日天]|周[一二三四五六日天]|刚刚)$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex UnreadCountPattern = new Regex(
            @"^(?:\[\s*(?<bracket>\d+)\s*条?\s*\]|(?<label>\d+)\s*条(?:未读(?:消息)?|新消息))$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly HashSet<string> StatusLines = new HashSet<string>(
            new[]
            {
                "已置顶",
                "置顶聊天",
                "消息免打扰",
                "免打扰",
                "静音",
                "折叠的聊天",
                "有新消息",
                "以下为新消息",
                "有人@我",
                "@我"
            },
            StringComparer.Ordinal);

        private const string ServiceAccountLabel = "\u670D\u52A1\u53F7";

        internal static ChatSession Parse(string rawName, int position, string automationId = null)
        {
            if (string.IsNullOrWhiteSpace(rawName))
            {
                return null;
            }

            // WeChat exposes each session as one accessible name containing
            // newline-separated contact, status, preview, and timestamp fields.
            var lines = rawName
                .Replace("\r", string.Empty)
                .Split('\n')
                .Select(delegate(string value) { return value.Trim(); })
                .Where(delegate(string value) { return value.Length > 0; })
                .ToList();

            if (lines.Count < 2)
            {
                return null;
            }

            var contact = lines[0];
            const string SessionItemPrefix = "session_item_";
            if (!string.IsNullOrWhiteSpace(automationId) &&
                automationId.StartsWith(SessionItemPrefix, StringComparison.Ordinal) &&
                automationId.Length > SessionItemPrefix.Length)
            {
                // WeChat 4.x exposes a stable session identity through the
                // AutomationId. Reuse it instead of presentation text that can
                // gain or lose pin/unread labels between UI refreshes.
                contact = automationId.Substring(SessionItemPrefix.Length);
            }

            var timestampIndex = -1;
            var unreadCount = -1;
            for (var index = 1; index < lines.Count; index++)
            {
                var unreadMatch = UnreadCountPattern.Match(lines[index]);
                if (unreadMatch.Success)
                {
                    var value = unreadMatch.Groups["bracket"].Success
                        ? unreadMatch.Groups["bracket"].Value
                        : unreadMatch.Groups["label"].Value;
                    int parsedUnreadCount;
                    if (int.TryParse(value, out parsedUnreadCount))
                    {
                        unreadCount = parsedUnreadCount;
                    }
                }

                if (IsTimestamp(lines[index]))
                {
                    timestampIndex = index;
                    break;
                }
            }

            // Everything between the contact and timestamp is treated as the
            // preview, except known presentation-only status labels.
            var previewEnd = timestampIndex >= 0 ? timestampIndex : lines.Count;
            var isServiceAccountAggregate =
                lines.Count > 1 &&
                string.Equals(lines[1], ServiceAccountLabel, StringComparison.Ordinal);
            var previewParts = new List<string>();
            for (var index = 1; index < previewEnd; index++)
            {
                if (!IsPresentationOnly(lines[index]) &&
                    !string.Equals(
                        lines[index],
                        ServiceAccountLabel,
                        StringComparison.Ordinal))
                {
                    previewParts.Add(lines[index]);
                }
            }

            // WeChat may expose unread counters and other presentation labels
            // before the preview. The last meaningful line is the actual
            // session summary and remains stable while those labels change.
            // A service-account aggregate is different: it contains several
            // message summaries ordered newest first, so its first meaningful
            // line must be used or a new top entry can be missed.
            var preview = previewParts.Count > 0
                ? (isServiceAccountAggregate
                    ? previewParts[0]
                    : previewParts[previewParts.Count - 1]).Trim()
                : string.Empty;
            if (preview.Length == 0)
            {
                preview = "收到一条新消息";
            }

            var timestamp = timestampIndex >= 0 ? lines[timestampIndex] : string.Empty;
            return new ChatSession
            {
                Contact = contact,
                Preview = preview,
                Timestamp = timestamp,
                UnreadCount = unreadCount,
                Position = position,
                // Timestamp text is presentation state: "刚刚" later becomes
                // a clock time even though the message itself did not change.
                Signature = Hash(contact + "\n" + preview)
            };
        }

        internal static bool IsRecentTimestamp(string value, DateTime now)
        {
            DateTime parsed;
            if (DateTime.TryParseExact(
                value,
                "H:mm",
                System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.None,
                out parsed))
            {
                var candidate = now.Date.AddHours(parsed.Hour).AddMinutes(parsed.Minute);
                return Math.Abs((now - candidate).TotalMinutes) <= 3;
            }

            return string.Equals(value, "刚刚", StringComparison.Ordinal);
        }

        internal static bool LooksLikeOutgoing(string preview)
        {
            if (string.IsNullOrWhiteSpace(preview))
            {
                return false;
            }

            return preview.StartsWith("我:", StringComparison.Ordinal) ||
                   preview.StartsWith("我：", StringComparison.Ordinal) ||
                   preview.StartsWith("You:", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsTimestamp(string value)
        {
            return ClockPattern.IsMatch(value) || DatePattern.IsMatch(value);
        }

        private static bool IsPresentationOnly(string value)
        {
            return StatusLines.Contains(value) || UnreadCountPattern.IsMatch(value);
        }

        private static string Hash(string value)
        {
            using (var sha = SHA256.Create())
            {
                var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
                return Convert.ToBase64String(bytes);
            }
        }
    }
}
