// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Linq;

namespace WeChatMessageNotifier
{
    internal sealed class SessionChangeDetector
    {
        private Dictionary<string, ChatSession> previous =
            new Dictionary<string, ChatSession>(StringComparer.Ordinal);
        private bool initialized;

        internal IList<ChatSession> Update(IList<ChatSession> current, DateTime now)
        {
            var notifications = new List<ChatSession>();
            var next = new Dictionary<string, ChatSession>(StringComparer.Ordinal);

            foreach (var session in current)
            {
                if (!next.ContainsKey(session.Contact))
                {
                    next.Add(session.Contact, session);
                }

                // The first scan is a baseline. Without this guard every
                // existing conversation would appear as a new notification.
                if (!initialized)
                {
                    continue;
                }

                ChatSession old;
                var known = previous.TryGetValue(session.Contact, out old);
                var changed = known && !string.Equals(old.Signature, session.Signature, StringComparison.Ordinal);
                var newlyVisibleAndRecent =
                    !known &&
                    session.Position <= 2 &&
                    SessionParser.IsRecentTimestamp(session.Timestamp, now);

                if ((changed || newlyVisibleAndRecent) &&
                    !SessionParser.LooksLikeOutgoing(session.Preview))
                {
                    notifications.Add(session);
                }
            }

            previous = next;
            initialized = true;
            return notifications
                .OrderBy(delegate(ChatSession session) { return session.Position; })
                .ToList();
        }
    }
}
