// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

namespace WeChatMessageNotifier
{
    internal enum SessionNotificationOverride
    {
        Allow,
        Block
    }
}
