// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace WeChatMessageNotifier
{
    internal static class SessionParser
    {
        private static readonly Regex ClockPattern = new Regex(
            @"^(?:[01]?\d|2[0-3]):[0-5]\d$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex DatePattern = new Regex(
            @"^(?:\d{1,2}/\d{1,2}|昨天|前天|星期[一二三四五六日天]|周[一二三四五六日天]|刚刚)$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly HashSet<string> StatusLines = new HashSet<string>(
            new[]
            {
                "已置顶",
                "置顶聊天",
                "消息免打扰",
                "免打扰",
                "静音",
                "折叠的聊天"
            },
            StringComparer.Ordinal);

        internal static ChatSession Parse(string rawName, int position)
        {
            if (string.IsNullOrWhiteSpace(rawName))
            {
                return null;
            }

            // WeChat exposes each session as one accessible name containing
            // newline-separated contact, status, preview, and timestamp fields.
            var lines = rawName
                .Replace("\r", string.Empty)
                .Split('\n')
                .Select(delegate(string value) { return value.Trim(); })
                .Where(delegate(string value) { return value.Length > 0; })
                .ToList();

            if (lines.Count < 2)
            {
                return null;
            }

            var contact = lines[0];
            var timestampIndex = -1;
            for (var index = 1; index < lines.Count; index++)
            {
                if (IsTimestamp(lines[index]))
                {
                    timestampIndex = index;
                    break;
                }
            }

            // Everything between the contact and timestamp is treated as the
            // preview, except known presentation-only status labels.
            var previewEnd = timestampIndex >= 0 ? timestampIndex : lines.Count;
            var previewParts = new List<string>();
            for (var index = 1; index < previewEnd; index++)
            {
                if (!StatusLines.Contains(lines[index]))
                {
                    previewParts.Add(lines[index]);
                }
            }

            var preview = string.Join(" ", previewParts.ToArray()).Trim();
            if (preview.Length == 0)
            {
                preview = "收到一条新消息";
            }

            var timestamp = timestampIndex >= 0 ? lines[timestampIndex] : string.Empty;
            return new ChatSession
            {
                Contact = contact,
                Preview = preview,
                Timestamp = timestamp,
                Position = position,
                Signature = Hash(contact + "\n" + preview + "\n" + timestamp)
            };
        }

        internal static bool IsRecentTimestamp(string value, DateTime now)
        {
            DateTime parsed;
            if (DateTime.TryParseExact(
                value,
                "H:mm",
                System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.None,
                out parsed))
            {
                var candidate = now.Date.AddHours(parsed.Hour).AddMinutes(parsed.Minute);
                return Math.Abs((now - candidate).TotalMinutes) <= 3;
            }

            return string.Equals(value, "刚刚", StringComparison.Ordinal);
        }

        internal static bool LooksLikeOutgoing(string preview)
        {
            if (string.IsNullOrWhiteSpace(preview))
            {
                return false;
            }

            return preview.StartsWith("我:", StringComparison.Ordinal) ||
                   preview.StartsWith("我：", StringComparison.Ordinal) ||
                   preview.StartsWith("You:", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsTimestamp(string value)
        {
            return ClockPattern.IsMatch(value) || DatePattern.IsMatch(value);
        }

        private static string Hash(string value)
        {
            using (var sha = SHA256.Create())
            {
                var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
                return Convert.ToBase64String(bytes);
            }
        }
    }
}
