// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace WeChatMessageNotifier
{
    internal static class SessionParser
    {
        private static readonly Regex ClockPattern = new Regex(
            @"^(?:[01]?\d|2[0-3]):[0-5]\d$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex DatePattern = new Regex(
            @"^(?:\d{1,2}/\d{1,2}|昨天|前天|星期[一二三四五六日天]|周[一二三四五六日天]|刚刚)$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex UnreadCountPattern = new Regex(
            @"^(?:\[\s*(?<bracket>\d+)\s*条?\s*\]|(?<label>\d+)\s*条(?:未读(?:消息)?|新消息))$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly HashSet<string> StatusLines = new HashSet<string>(
            new[]
            {
                "已置顶",
                "置顶聊天",
                "消息免打扰",
                "免打扰",
                "静音",
                "折叠的聊天",
                "有新消息",
                "以下为新消息",
                "有人@我",
                "@我"
            },
            StringComparer.Ordinal);

        private const string ServiceAccountLabel = "\u670D\u52A1\u53F7";
        private const string SubscriptionAccountLabel = "\u8BA2\u9605\u53F7";
        private const string OfficialAccountLabel = "\u516C\u4F17\u53F7";
        private const string GroupChatLabel = "\u7FA4\u804A";

        internal static ChatSession Parse(
            string rawName,
            int position,
            string automationId = null)
        {
            if (string.IsNullOrWhiteSpace(rawName))
            {
                return null;
            }

            // WeChat exposes each session as one accessible name containing
            // newline-separated contact, status, preview, and timestamp fields.
            var lines = rawName
                .Replace("\r", string.Empty)
                .Split('\n')
                .Select(delegate(string value) { return value.Trim(); })
                .Where(delegate(string value) { return value.Length > 0; })
                .ToList();

            if (lines.Count < 2)
            {
                return null;
            }

            var contact = lines[0];
            var sessionKey = contact;
            const string SessionItemPrefix = "session_item_";
            var hasStableAutomationId =
                !string.IsNullOrWhiteSpace(automationId) &&
                automationId.StartsWith(SessionItemPrefix, StringComparison.Ordinal) &&
                automationId.Length > SessionItemPrefix.Length;
            if (hasStableAutomationId)
            {
                // WeChat 4.x exposes a stable session identity through the
                // AutomationId. Keep it separate from the display name so a
                // stable identity can merge notifications without changing
                // what the user sees on the card.
                sessionKey = automationId.Substring(SessionItemPrefix.Length);
            }

            var timestampIndex = -1;
            var unreadCount = -1;
            for (var index = 1; index < lines.Count; index++)
            {
                var unreadMatch = UnreadCountPattern.Match(lines[index]);
                if (unreadMatch.Success)
                {
                    var value = unreadMatch.Groups["bracket"].Success
                        ? unreadMatch.Groups["bracket"].Value
                        : unreadMatch.Groups["label"].Value;
                    int parsedUnreadCount;
                    if (int.TryParse(value, out parsedUnreadCount))
                    {
                        unreadCount = parsedUnreadCount;
                    }
                }

                if (IsTimestamp(lines[index]))
                {
                    timestampIndex = index;
                    break;
                }
            }

            // Everything between the contact and timestamp is treated as the
            // preview, except known presentation-only status labels.
            var previewEnd = timestampIndex >= 0 ? timestampIndex : lines.Count;
            var isServiceAccountAggregate =
                lines.Count > 1 &&
                string.Equals(lines[1], ServiceAccountLabel, StringComparison.Ordinal);
            var previewParts = new List<string>();
            for (var index = 1; index < previewEnd; index++)
            {
                if (!IsPresentationOnly(lines[index]) &&
                    !string.Equals(
                        lines[index],
                        ServiceAccountLabel,
                        StringComparison.Ordinal))
                {
                    previewParts.Add(lines[index]);
                }
            }

            // WeChat may expose unread counters and other presentation labels
            // before the preview. The last meaningful line is the actual
            // session summary and remains stable while those labels change.
            // A service-account aggregate is different: it contains several
            // message summaries ordered newest first, so its first meaningful
            // line must be used or a new top entry can be missed.
            var preview = previewParts.Count > 0
                ? (isServiceAccountAggregate
                    ? previewParts[0]
                    : previewParts[previewParts.Count - 1]).Trim()
                : string.Empty;
            if (preview.Length == 0)
            {
                preview = "收到一条新消息";
            }

            var timestamp = timestampIndex >= 0 ? lines[timestampIndex] : string.Empty;
            var hasServiceLabel = ContainsExactLine(
                lines,
                ServiceAccountLabel);
            var hasOfficialMarker =
                ContainsExactLine(lines, SubscriptionAccountLabel) ||
                ContainsExactLine(lines, OfficialAccountLabel) ||
                HasStableOfficialAccountId(sessionKey, automationId);
            var hasGroupMarker =
                HasStableGroupId(sessionKey) ||
                HasStableGroupId(automationId) ||
                ContainsExactLine(lines, GroupChatLabel);
            var kind = Classify(
                hasServiceLabel,
                hasOfficialMarker,
                hasGroupMarker);
            return new ChatSession
            {
                SessionKey = sessionKey,
                Contact = contact,
                Preview = preview,
                Timestamp = timestamp,
                UnreadCount = unreadCount,
                Position = position,
                Kind = kind,
                DetectedKind = kind,
                ContactHash = ShortHash(sessionKey),
                RawLineCount = lines.Count,
                HasServiceLabel = hasServiceLabel,
                HasOfficialLabel = hasOfficialMarker,
                HasOfficialMarker = hasOfficialMarker,
                HasGroupMarker = hasGroupMarker,
                // Timestamp text is presentation state: "刚刚" later becomes
                // a clock time even though the message itself did not change.
                Signature = Hash(sessionKey + "\n" + preview)
            };
        }

        private static ChatSessionKind Classify(
            bool hasServiceLabel,
            bool hasOfficialMarker,
            bool hasGroupMarker)
        {
            if (hasServiceLabel)
            {
                return ChatSessionKind.ServiceAccount;
            }
            if (hasOfficialMarker)
            {
                return ChatSessionKind.OfficialAccount;
            }

            if (hasGroupMarker)
            {
                return ChatSessionKind.GroupChat;
            }

            // WeChat 4.x often exposes only "session_item_<display name>".
            // That does not prove a row is a direct contact: it can also be a
            // group or account. Unknown is safer and can be manually overridden.
            return ChatSessionKind.Unknown;
        }

        private static bool HasStableOfficialAccountId(
            string sessionKey,
            string automationId)
        {
            return StartsWithOfficialAccountId(sessionKey) ||
                   StartsWithOfficialAccountId(automationId);
        }

        private static bool StartsWithOfficialAccountId(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return false;
            }

            const string SessionItemPrefix = "session_item_";
            var normalized = value.Trim();
            if (normalized.StartsWith(
                SessionItemPrefix,
                StringComparison.Ordinal))
            {
                normalized = normalized.Substring(SessionItemPrefix.Length);
            }

            return normalized.StartsWith(
                "gh_",
                StringComparison.OrdinalIgnoreCase);
        }

        private static bool HasStableGroupId(string value)
        {
            return !string.IsNullOrWhiteSpace(value) &&
                   value.IndexOf(
                       "@chatroom",
                       StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static bool ContainsExactLine(
            IEnumerable<string> lines,
            string expected)
        {
            return lines.Any(
                delegate(string line)
                {
                    return string.Equals(
                        line,
                        expected,
                        StringComparison.Ordinal);
                });
        }

        internal static bool IsRecentTimestamp(string value, DateTime now)
        {
            DateTime parsed;
            if (DateTime.TryParseExact(
                value,
                "H:mm",
                System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.None,
                out parsed))
            {
                var candidate = now.Date.AddHours(parsed.Hour).AddMinutes(parsed.Minute);
                return Math.Abs((now - candidate).TotalMinutes) <= 3;
            }

            return string.Equals(value, "刚刚", StringComparison.Ordinal);
        }

        internal static bool LooksLikeOutgoing(string preview)
        {
            if (string.IsNullOrWhiteSpace(preview))
            {
                return false;
            }

            var value = preview.TrimStart();
            if (StartsWithColonPrefix(value, "You"))
            {
                return true;
            }

            // "你:" is intentionally not treated as outgoing without UIA
            // evidence. Some WeChat builds can expose incoming preview text
            // starting with 你, so filtering it here risks losing real messages.
            return StartsWithOutgoingActor(value, '\u6211');
        }

        private static bool StartsWithColonPrefix(
            string value,
            string prefix)
        {
            if (!value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            var remainder = value.Substring(prefix.Length).TrimStart();
            return remainder.StartsWith(":", StringComparison.Ordinal) ||
                   remainder.StartsWith("\uFF1A", StringComparison.Ordinal);
        }

        private static bool StartsWithOutgoingActor(
            string value,
            char actor)
        {
            if (value.Length == 0 || value[0] != actor)
            {
                return false;
            }

            var remainder = value.Substring(1);
            var hadSeparator = remainder.Length > 0 &&
                char.IsWhiteSpace(remainder[0]);
            remainder = remainder.TrimStart();
            if (remainder.StartsWith(":", StringComparison.Ordinal) ||
                remainder.StartsWith("\uFF1A", StringComparison.Ordinal))
            {
                return true;
            }

            // Attachment and call summaries use a fixed actor token followed
            // by a space. Requiring that separator prevents names such as
            // "你好吗" or "我爱学习" from being treated as outgoing.
            if (!hadSeparator)
            {
                return false;
            }

            var fixedSummaries = new[]
            {
                "[\u56FE\u7247]",
                "[\u6587\u4EF6]",
                "[\u8BED\u97F3]",
                "[\u89C6\u9891]",
                "[\u52A8\u753B\u8868\u60C5]",
                "[\u8868\u60C5]",
                "[\u4F4D\u7F6E]",
                "[\u94FE\u63A5]",
                "[\u97F3\u4E50]",
                "[\u5C0F\u7A0B\u5E8F]",
                "\u53D1\u8D77\u4E86\u8BED\u97F3\u901A\u8BDD",
                "\u53D1\u8D77\u4E86\u89C6\u9891\u901A\u8BDD"
            };
            foreach (var summary in fixedSummaries)
            {
                if (remainder.StartsWith(summary, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsTimestamp(string value)
        {
            return ClockPattern.IsMatch(value) || DatePattern.IsMatch(value);
        }

        private static bool IsPresentationOnly(string value)
        {
            return StatusLines.Contains(value) || UnreadCountPattern.IsMatch(value);
        }

        private static string Hash(string value)
        {
            using (var sha = SHA256.Create())
            {
                var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
                return Convert.ToBase64String(bytes);
            }
        }

        private static string ShortHash(string value)
        {
            using (var sha = SHA256.Create())
            {
                var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
                var builder = new StringBuilder(16);
                for (var index = 0; index < 8; index++)
                {
                    builder.Append(bytes[index].ToString("x2"));
                }
                return builder.ToString();
            }
        }
    }
}
