// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.IO;
using System.Text;

namespace WeChatMessageNotifier
{
    internal sealed class SettingsStore
    {
        private readonly Logger logger;
        private readonly string path;
        private DateTime lastObservedWriteTimeUtc = DateTime.MinValue;

        internal SettingsStore(Logger logger)
            : this(
                logger,
                System.IO.Path.Combine(
                    Environment.GetFolderPath(
                        Environment.SpecialFolder.LocalApplicationData),
                    "WeChatMessageNotifier",
                    "settings.json"))
        {
        }

        internal SettingsStore(Logger logger, string path)
        {
            this.logger = logger;
            this.path = path;
        }

        internal string Path
        {
            get { return path; }
        }

        internal NotificationFilterSettings Load()
        {
            try
            {
                if (!File.Exists(path))
                {
                    lastObservedWriteTimeUtc = DateTime.MinValue;
                    return new NotificationFilterSettings();
                }

                NotificationFilterSettings settings;
                if (NotificationFilterSettings.TryParse(
                    File.ReadAllText(path, Encoding.UTF8),
                    out settings))
                {
                    lastObservedWriteTimeUtc =
                        File.GetLastWriteTimeUtc(path);
                    return settings;
                }

                logger.Info(
                    "Notification filter settings were invalid; defaults were used.");
                lastObservedWriteTimeUtc =
                    File.GetLastWriteTimeUtc(path);
            }
            catch (Exception exception)
            {
                logger.Error(
                    "Notification filter settings could not be loaded; defaults were used",
                    exception);
                if (File.Exists(path))
                {
                    lastObservedWriteTimeUtc =
                        File.GetLastWriteTimeUtc(path);
                }
            }

            return new NotificationFilterSettings();
        }

        internal bool Save(NotificationFilterSettings settings)
        {
            try
            {
                var directory = System.IO.Path.GetDirectoryName(path);
                if (!string.IsNullOrEmpty(directory))
                {
                    Directory.CreateDirectory(directory);
                }
                File.WriteAllText(
                    path,
                    settings.ToJson(),
                    new UTF8Encoding(false));
                lastObservedWriteTimeUtc =
                    File.GetLastWriteTimeUtc(path);
                return true;
            }
            catch (Exception exception)
            {
                logger.Error(
                    "Notification filter settings could not be saved",
                    exception);
                return false;
            }
        }

        internal bool ReloadIfChanged(
            NotificationFilterSettings current)
        {
            try
            {
                if (!File.Exists(path))
                {
                    return false;
                }

                var writeTimeUtc = File.GetLastWriteTimeUtc(path);
                if (writeTimeUtc <= lastObservedWriteTimeUtc)
                {
                    return false;
                }

                var loaded = Load();
                current.ApplyFrom(loaded);
                logger.Info(
                    "Notification filter settings were reloaded.");
                return true;
            }
            catch (Exception exception)
            {
                logger.Error(
                    "Notification filter settings could not be reloaded",
                    exception);
                return false;
            }
        }
    }
}
