// Settings UI generated by OpenAI Codex under the direction of the project owner.
//
// The settings surface deliberately uses only standard WinForms containers and
// controls. It is a long-lived editor with native TextBox, Label, LinkLabel,
// and Button children; mixing those with a fully extended DWM client frame or
// custom UserPaint cards is not a reliable .NET Framework rendering path.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;

namespace WeChatMessageNotifier
{
    internal sealed class SettingsForm : Win11BackdropForm
    {
        private static readonly Size LogicalMinimumSize = new Size(700, 620);
        private const int DefaultClientWidth = 900;
        private const int DefaultClientHeight = 720;
        private const int ResponsiveBreakpoint = 760;
        private const double MaximumRestoredWindowWidthFraction = 0.88d;
        private const double MaximumRestoredWindowHeightFraction = 0.88d;

        private readonly NotificationFilterSettings editedSettings;
        private readonly Logger logger;
        private readonly TableLayoutPanel rootLayout;
        private readonly TableLayoutPanel headerLayout;
        private readonly Panel contentScrollPanel;
        private readonly TableLayoutPanel contentLayout;
        private readonly TableLayoutPanel footerLayout;
        private readonly FlowLayoutPanel footerInformation;
        private readonly TableLayoutPanel footerButtons;
        private readonly Label titleLabel;
        private readonly Label subtitleLabel;
        private readonly Label stateLabel;
        private readonly TextBox serviceKeywords;
        private readonly TextBox officialKeywords;
        private readonly TextBox groupKeywords;
        private readonly CheckBox privacyMode;
        private readonly LinkLabel activityLink;
        private readonly LinkLabel advancedLink;
        private readonly Button saveButton;
        private readonly Button cancelButton;
        private readonly int initializedControlCount;
        private bool placementInitialized;
        private int appliedDpi = 96;

        internal static bool UsesResponsiveLayout { get { return true; } }
        internal static bool IsResizable { get { return true; } }
        internal static bool HandlesPerMonitorDpiChanges { get { return true; } }
        internal static bool UsesStableNativeTextControls { get { return true; } }
        internal static bool UsesSingleConstructionPath { get { return true; } }
        internal static bool UsesScrollableContent { get { return true; } }
        internal static bool FooterIsOutsideScrollContent { get { return true; } }
        internal static bool UsesTableLayoutRoot { get { return true; } }
        internal static bool UsesOpaqueClientContainers { get { return true; } }
        // AutoScaleMode.Dpi owns font/control scaling. This flag means the
        // form always forces a standard layout pass after a monitor change;
        // it does not create or dispose per-monitor Font objects.
        internal static bool UsesForcedDpiMetricRefresh { get { return true; } }
        internal static bool UsesExplicitEditableKeywordEditors { get { return true; } }
        internal static bool UsesStableFooterButtonTable { get { return true; } }
        internal static bool UsesFrameworkDpiAutoScale { get { return true; } }
        internal static bool UsesNoCustomCardPainting { get { return true; } }
        internal static Size MinimumLogicalSize { get { return LogicalMinimumSize; } }

        internal SettingsForm(
            NotificationFilterSettings currentSettings,
            bool currentPrivacyMode,
            string monitoringState,
            IEnumerable<NotificationActivityRecord> recentActivity)
            : this(
                currentSettings,
                currentPrivacyMode,
                monitoringState,
                recentActivity,
                null)
        {
        }

        internal SettingsForm(
            NotificationFilterSettings currentSettings,
            bool currentPrivacyMode,
            string monitoringState,
            IEnumerable<NotificationActivityRecord> recentActivity,
            Logger currentLogger)
        {
            logger = currentLogger;
            editedSettings = currentSettings == null
                ? new NotificationFilterSettings()
                : currentSettings.Clone();
            editedSettings.PrivacyMode = currentPrivacyMode;

            Text = "\u8bbe\u7f6e \u00b7 \u5fae\u4fe1\u6d88\u606f\u63d0\u9192\u5668";
            StartPosition = FormStartPosition.Manual;
            FormBorderStyle = FormBorderStyle.Sizable;
            MaximizeBox = true;
            MinimizeBox = true;
            SizeGripStyle = SizeGripStyle.Show;
            ShowInTaskbar = true;
            AutoScaleMode = AutoScaleMode.Dpi;
            MinimumSize = LogicalMinimumSize;
            ClientSize = new Size(DefaultClientWidth, DefaultClientHeight);
            Win11Visual.ApplyWindowStyle(this);

            rootLayout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 1,
                RowCount = 3,
                Padding = new Padding(18),
                BackColor = Win11Visual.WindowBackground,
                Margin = new Padding(0)
            };
            rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            Controls.Add(rootLayout);

            headerLayout = new TableLayoutPanel
            {
                Dock = DockStyle.Top,
                AutoSize = true,
                AutoSizeMode = AutoSizeMode.GrowAndShrink,
                ColumnCount = 2,
                RowCount = 2,
                Padding = new Padding(14, 10, 14, 10),
                BackColor = Win11Visual.SolidCardBackground,
                Margin = new Padding(0)
            };
            headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 75f));
            headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25f));
            headerLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            headerLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            titleLabel = CreateLabel(
                "\u5fae\u4fe1\u6d88\u606f\u63d0\u9192\u5668",
                Win11Visual.Title,
                Win11Visual.UiTitleFont);
            subtitleLabel = CreateLabel(
                "Windows \u7cfb\u7edf\u901a\u77e5 \u00b7 \u672c\u5730\u89c4\u5219\u4e0e\u9690\u79c1\u8bbe\u7f6e",
                Win11Visual.SecondaryText,
                Win11Visual.UiSmallFont);
            subtitleLabel.Margin = new Padding(0, 2, 0, 0);
            stateLabel = CreateLabel(
                monitoringState ?? "\u72b6\u6001\uff1a\u7b49\u5f85\u9996\u6b21\u626b\u63cf",
                ContainsAttentionState(monitoringState)
                    ? Color.FromArgb(255, 180, 83, 9)
                    : Color.FromArgb(255, 22, 101, 52),
                Win11Visual.UiSmallFont);
            stateLabel.AutoSize = false;
            stateLabel.AutoEllipsis = true;
            stateLabel.Dock = DockStyle.Fill;
            stateLabel.TextAlign = ContentAlignment.MiddleCenter;
            stateLabel.BackColor = ContainsAttentionState(monitoringState)
                ? Color.FromArgb(255, 255, 247, 237)
                : Color.FromArgb(255, 240, 253, 244);
            stateLabel.Margin = new Padding(8, 0, 0, 0);
            headerLayout.Controls.Add(titleLabel, 0, 0);
            headerLayout.Controls.Add(subtitleLabel, 0, 1);
            headerLayout.Controls.Add(stateLabel, 1, 0);
            headerLayout.SetRowSpan(stateLabel, 2);
            rootLayout.Controls.Add(headerLayout, 0, 0);

            contentScrollPanel = new Panel
            {
                Dock = DockStyle.Fill,
                AutoScroll = true,
                Padding = new Padding(0, 12, 0, 12),
                Margin = new Padding(0),
                BackColor = Win11Visual.WindowBackground
            };
            contentLayout = new TableLayoutPanel
            {
                Dock = DockStyle.Top,
                AutoSize = true,
                AutoSizeMode = AutoSizeMode.GrowAndShrink,
                ColumnCount = 1,
                RowCount = 3,
                Padding = new Padding(0),
                Margin = new Padding(0),
                BackColor = Win11Visual.WindowBackground
            };
            contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            contentScrollPanel.Controls.Add(contentLayout);
            rootLayout.Controls.Add(contentScrollPanel, 0, 1);

            serviceKeywords = CreateKeywordCard(
                0,
                "\u670d\u52a1\u53f7\u63d0\u9192\u5173\u952e\u8bcd",
                "\u6d88\u606f\u6458\u8981\u547d\u4e2d\u4efb\u4e00\u8bcd\u65f6\u63d0\u9192\uff1b\u6bcf\u884c\u4e00\u4e2a\u5173\u952e\u8bcd\u3002",
                editedSettings.ServiceAccountAllowKeywords);
            officialKeywords = CreateKeywordCard(
                1,
                "\u516c\u4f17\u53f7\u63d0\u9192\u5173\u952e\u8bcd",
                "\u516c\u4f17\u53f7\u9ed8\u8ba4\u4e0d\u63d0\u9192\uff0c\u53ea\u6709\u6458\u8981\u547d\u4e2d\u8fd9\u4e9b\u8bcd\u624d\u63d0\u9192\u3002",
                editedSettings.OfficialAccountAllowKeywords);
            groupKeywords = CreateKeywordCard(
                2,
                "\u7fa4\u804a\u5c4f\u853d\u5173\u952e\u8bcd",
                "\u540d\u79f0\u542b\u201c\u7fa4\u201d\u7684\u4f1a\u8bdd\u89c6\u4e3a\u7fa4\u804a\uff1b\u547d\u4e2d\u4efb\u4e00\u8bcd\u65f6\u4e0d\u63d0\u9192\u3002",
                editedSettings.GroupChatBlockKeywords);

            footerLayout = new TableLayoutPanel
            {
                Dock = DockStyle.Top,
                AutoSize = true,
                AutoSizeMode = AutoSizeMode.GrowAndShrink,
                ColumnCount = 2,
                RowCount = 1,
                Padding = new Padding(0, 10, 0, 0),
                Margin = new Padding(0),
                BackColor = Win11Visual.WindowBackground
            };
            footerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            footerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            footerLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            footerInformation = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                AutoSize = true,
                AutoSizeMode = AutoSizeMode.GrowAndShrink,
                FlowDirection = FlowDirection.TopDown,
                WrapContents = false,
                Margin = new Padding(0),
                BackColor = Win11Visual.WindowBackground
            };
            privacyMode = new CheckBox
            {
                Text = "\u9690\u79c1\u6a21\u5f0f\uff1a\u901a\u77e5\u53ea\u663e\u793a\u8054\u7cfb\u4eba\uff0c\u4e0d\u663e\u793a\u6d88\u606f\u6458\u8981",
                Checked = currentPrivacyMode,
                AutoSize = true,
                MaximumSize = new Size(470, 0),
                ForeColor = Color.FromArgb(255, 51, 65, 85),
                BackColor = Win11Visual.WindowBackground,
                UseCompatibleTextRendering = true,
                Font = Win11Visual.UiSmallFont,
                Margin = new Padding(0, 0, 0, 4)
            };
            activityLink = CreateLink(
                "\u67e5\u770b\u6700\u8fd1\u901a\u77e5\u51b3\u7b56\uff08" + CountActivity(recentActivity) + " \u6761\uff0c\u5df2\u8131\u654f\uff09");
            advancedLink = CreateLink(
                "\u9ad8\u7ea7\u89c4\u5219\uff08\u6309\u533f\u540d\u4f1a\u8bdd\u54c8\u5e0c Allow / Block\uff09\u5728\u539f\u59cb\u8bbe\u7f6e\u6587\u4ef6\u4e2d\u7f16\u8f91");
            activityLink.Click += delegate { DialogResult = DialogResult.Yes; Close(); };
            advancedLink.Click += delegate { DialogResult = DialogResult.Retry; Close(); };
            footerInformation.Controls.Add(privacyMode);
            footerInformation.Controls.Add(activityLink);
            footerInformation.Controls.Add(advancedLink);
            footerLayout.Controls.Add(footerInformation, 0, 0);

            footerButtons = new TableLayoutPanel
            {
                AutoSize = true,
                AutoSizeMode = AutoSizeMode.GrowAndShrink,
                ColumnCount = 2,
                RowCount = 1,
                Margin = new Padding(8, 0, 0, 0),
                Anchor = AnchorStyles.Right | AnchorStyles.Bottom,
                BackColor = Win11Visual.WindowBackground
            };
            footerButtons.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            footerButtons.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            cancelButton = new Button
            {
                Text = "\u53d6\u6d88",
                DialogResult = DialogResult.Cancel,
                Size = new Size(96, 38),
                MinimumSize = new Size(88, 36),
                Margin = new Padding(0)
            };
            Win11Visual.StyleSecondaryButton(cancelButton);
            saveButton = new Button
            {
                Text = "\u4fdd\u5b58\u8bbe\u7f6e",
                Size = new Size(120, 38),
                MinimumSize = new Size(112, 36),
                Margin = new Padding(8, 0, 0, 0)
            };
            Win11Visual.StylePrimaryButton(saveButton);
            saveButton.Click += SaveAndClose;
            footerButtons.Controls.Add(cancelButton, 0, 0);
            footerButtons.Controls.Add(saveButton, 1, 0);
            footerLayout.Controls.Add(footerButtons, 1, 0);
            rootLayout.Controls.Add(footerLayout, 0, 2);
            AcceptButton = saveButton;
            CancelButton = cancelButton;

            initializedControlCount = CountControls(this);
            ApplyDpiMetrics(GetCurrentWindowDpi());
            ApplyResponsiveLayout(true);
        }

        internal NotificationFilterSettings EditedSettings { get { return editedSettings; } }
        internal bool PrivacyMode { get { return privacyMode.Checked; } }

        protected override void OnLoad(EventArgs eventArgs)
        {
            base.OnLoad(eventArgs);
            RestoreOrCenterOnCurrentScreen();
            ApplyDpiMetrics(GetCurrentWindowDpi());
            ApplyResponsiveLayout(true);
            ReapplyBackdrop();
            AssertStableControlTree();
        }

        protected override void OnDpiChanged(DpiChangedEventArgs eventArgs)
        {
            var oldDpi = appliedDpi;
            base.OnDpiChanged(eventArgs);
            if (eventArgs.SuggestedRectangle.Width > 0 &&
                eventArgs.SuggestedRectangle.Height > 0)
            {
                Bounds = eventArgs.SuggestedRectangle;
            }

            ApplyDpiMetrics(GetCurrentWindowDpi());
            ApplyResponsiveLayout(true);
            PerformLayout();
            ReapplyBackdrop();
            Invalidate(true);
            LogDpiChanged(oldDpi, appliedDpi);
            AssertStableControlTree();
        }

        protected override void OnFormClosing(FormClosingEventArgs eventArgs)
        {
            CaptureWindowPlacement();
            base.OnFormClosing(eventArgs);
        }

        protected override void OnBackdropReapplied(
            bool applied,
            int attributeResult,
            int extendResult)
        {
            if (logger == null || !IsHandleCreated)
            {
                return;
            }

            var screen = Screen.FromHandle(Handle);
            logger.Info(
                "SettingsBackdrop: Dpi=" + GetCurrentWindowDpi() +
                ", Screen=" + (screen == null ? "Unknown" : screen.DeviceName) +
                ", Applied=" + applied +
                ", AttributeResult=" + attributeResult +
                ", ClientFrameExtension=Disabled");
        }

        private TextBox CreateKeywordCard(
            int row,
            string title,
            string description,
            IList<string> keywords)
        {
            // Native Panel rather than a UserPaint surface: all controls on
            // this path use the normal WinForms erase/layout contract.
            var card = new Panel
            {
                Dock = DockStyle.Top,
                Height = 174,
                MinimumSize = new Size(0, 166),
                BorderStyle = BorderStyle.FixedSingle,
                BackColor = Win11Visual.SolidCardBackground,
                Margin = new Padding(0, 0, 0, row == 2 ? 0 : 12),
                Padding = new Padding(14)
            };
            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 1,
                RowCount = 3,
                Margin = new Padding(0),
                Padding = new Padding(0),
                BackColor = Win11Visual.SolidCardBackground
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            var titleLabel = CreateLabel(title, Win11Visual.Title, Win11Visual.UiCardTitleFont);
            titleLabel.Margin = new Padding(0, 0, 0, 4);
            var descriptionLabel = CreateLabel(
                description,
                Win11Visual.SecondaryText,
                Win11Visual.UiSmallFont);
            descriptionLabel.MaximumSize = new Size(1000, 0);
            descriptionLabel.Margin = new Padding(0, 0, 0, 10);
            var editor = new TextBox
            {
                Enabled = true,
                ReadOnly = false,
                TabStop = true,
                Multiline = true,
                AcceptsReturn = true,
                ScrollBars = ScrollBars.Vertical,
                BorderStyle = BorderStyle.FixedSingle,
                Dock = DockStyle.Fill,
                MinimumSize = new Size(0, 76),
                BackColor = Color.White,
                ForeColor = Win11Visual.Title,
                Font = Win11Visual.UiFont,
                Text = JoinKeywords(keywords),
                Margin = new Padding(0)
            };
            layout.Controls.Add(titleLabel, 0, 0);
            layout.Controls.Add(descriptionLabel, 0, 1);
            layout.Controls.Add(editor, 0, 2);
            card.Controls.Add(layout);
            contentLayout.Controls.Add(card, 0, row);
            return editor;
        }

        private static Label CreateLabel(string text, Color color, Font font)
        {
            return new Label
            {
                Text = text ?? string.Empty,
                AutoSize = true,
                ForeColor = Win11Visual.ForceOpaque(color),
                BackColor = Win11Visual.SolidCardBackground,
                Font = font,
                UseCompatibleTextRendering = true,
                Margin = new Padding(0)
            };
        }

        private void ApplyResponsiveLayout(bool force)
        {
            // The fixed minimum width leaves enough room for the header state
            // and footer buttons. TableLayoutPanel handles normal resizes;
            // never move/reparent controls during SizeChanged or DPI events.
            if (!force && !IsHandleCreated)
            {
                return;
            }

            rootLayout.PerformLayout();
            headerLayout.PerformLayout();
            contentLayout.PerformLayout();
            footerLayout.PerformLayout();
        }

        private void ApplyDpiMetrics(int dpi)
        {
            // Use the framework's per-monitor AutoScaleMode.Dpi contract.
            // Point-sized fonts and LayoutPanel metrics scale with the form;
            // keeping this state only makes the responsive threshold and log
            // reflect the current monitor without manually replacing Fonts.
            appliedDpi = dpi < 96 ? 96 : dpi;
        }

        private int GetCurrentWindowDpi()
        {
            return IsHandleCreated
                ? NativeMethods.GetWindowDpiOrDefault(Handle)
                : (DeviceDpi >= 96 ? DeviceDpi : 96);
        }

        private void LogDpiChanged(int oldDpi, int newDpi)
        {
            if (logger == null || !IsHandleCreated)
            {
                return;
            }

            var screen = Screen.FromHandle(Handle);
            logger.Info(
                "SettingsDpiChanged: OldDpi=" + oldDpi +
                ", NewDpi=" + newDpi +
                ", Screen=" + (screen == null ? "Unknown" : screen.DeviceName));
        }

        private void RestoreOrCenterOnCurrentScreen()
        {
            if (placementInitialized)
            {
                return;
            }
            placementInitialized = true;

            var savedBounds = editedSettings.SettingsWindowBounds;
            if (savedBounds.HasValue && IsVisibleOnAnyScreen(savedBounds.Value))
            {
                var screen = Screen.FromRectangle(savedBounds.Value);
                var scaledBounds = ScaleSavedBoundsForCurrentDpi(
                    savedBounds.Value,
                    editedSettings.SettingsWindowDpi,
                    GetCurrentWindowDpi());
                Bounds = ClampToWorkingArea(scaledBounds, screen.WorkingArea);
                if (editedSettings.SettingsWindowMaximized)
                {
                    WindowState = FormWindowState.Maximized;
                }
                return;
            }

            var currentScreen = Screen.FromPoint(Cursor.Position);
            var workingArea = currentScreen.WorkingArea;
            Location = new Point(
                workingArea.Left + Math.Max(0, (workingArea.Width - Width) / 2),
                workingArea.Top + Math.Max(0, (workingArea.Height - Height) / 2));
        }

        private void CaptureWindowPlacement()
        {
            var normalBounds = WindowState == FormWindowState.Normal
                ? Bounds
                : RestoreBounds;
            editedSettings.SetSettingsWindowPlacement(
                normalBounds,
                WindowState == FormWindowState.Maximized,
                GetCurrentWindowDpi());
        }

        private void SaveAndClose(object sender, EventArgs eventArgs)
        {
            ReplaceKeywords(editedSettings.ServiceAccountAllowKeywords, serviceKeywords.Text);
            ReplaceKeywords(editedSettings.OfficialAccountAllowKeywords, officialKeywords.Text);
            ReplaceKeywords(editedSettings.GroupChatBlockKeywords, groupKeywords.Text);
            editedSettings.PrivacyMode = privacyMode.Checked;
            CaptureWindowPlacement();
            DialogResult = DialogResult.OK;
            Close();
        }

        private static LinkLabel CreateLink(string text)
        {
            return new LinkLabel
            {
                Text = text,
                AutoSize = true,
                MaximumSize = new Size(620, 0),
                LinkColor = Color.FromArgb(255, 37, 99, 235),
                ActiveLinkColor = Color.FromArgb(255, 29, 78, 216),
                VisitedLinkColor = Color.FromArgb(255, 37, 99, 235),
                BackColor = Win11Visual.WindowBackground,
                ForeColor = Color.FromArgb(255, 37, 99, 235),
                Font = Win11Visual.UiSmallFont,
                UseCompatibleTextRendering = true,
                Margin = new Padding(0, 0, 0, 3)
            };
        }

        private static bool ContainsAttentionState(string monitoringState)
        {
            return !string.IsNullOrEmpty(monitoringState) &&
                (monitoringState.IndexOf("\u6682\u505c", StringComparison.Ordinal) >= 0 ||
                 monitoringState.IndexOf("\u672a\u68c0\u6d4b", StringComparison.Ordinal) >= 0);
        }

        private static int CountActivity(IEnumerable<NotificationActivityRecord> activity)
        {
            var count = 0;
            if (activity != null)
            {
                foreach (var ignored in activity)
                {
                    count++;
                }
            }
            return count;
        }

        private static bool IsVisibleOnAnyScreen(Rectangle bounds)
        {
            foreach (var screen in Screen.AllScreens)
            {
                var intersection = Rectangle.Intersect(bounds, screen.WorkingArea);
                if (intersection.Width > 32 && intersection.Height > 32)
                {
                    return true;
                }
            }
            return false;
        }

        private static Rectangle ClampToWorkingArea(Rectangle bounds, Rectangle workingArea)
        {
            var minimumWidth = Math.Min(LogicalMinimumSize.Width, workingArea.Width);
            var minimumHeight = Math.Min(LogicalMinimumSize.Height, workingArea.Height);
            var maximumWidth = Math.Max(
                minimumWidth,
                (int)Math.Floor(workingArea.Width * MaximumRestoredWindowWidthFraction));
            var maximumHeight = Math.Max(
                minimumHeight,
                (int)Math.Floor(workingArea.Height * MaximumRestoredWindowHeightFraction));
            var width = Math.Min(Math.Max(minimumWidth, bounds.Width), maximumWidth);
            var height = Math.Min(Math.Max(minimumHeight, bounds.Height), maximumHeight);
            return new Rectangle(
                Math.Max(workingArea.Left, Math.Min(bounds.Left, workingArea.Right - width)),
                Math.Max(workingArea.Top, Math.Min(bounds.Top, workingArea.Bottom - height)),
                width,
                height);
        }

        private static Rectangle ScaleSavedBoundsForCurrentDpi(
            Rectangle bounds,
            int savedDpi,
            int currentDpi)
        {
            var sourceDpi = savedDpi >= 96 ? savedDpi : 96;
            var targetDpi = currentDpi >= 96 ? currentDpi : 96;
            if (sourceDpi == targetDpi)
            {
                return bounds;
            }

            return new Rectangle(
                bounds.X,
                bounds.Y,
                Math.Max(1, (int)Math.Round(bounds.Width * targetDpi / (double)sourceDpi)),
                Math.Max(1, (int)Math.Round(bounds.Height * targetDpi / (double)sourceDpi)));
        }

        private static string JoinKeywords(IList<string> keywords)
        {
            return keywords == null ? string.Empty : string.Join(Environment.NewLine, keywords);
        }

        private static void ReplaceKeywords(IList<string> target, string text)
        {
            target.Clear();
            var known = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var line in (text ?? string.Empty).Replace("\r", string.Empty).Split('\n'))
            {
                var keyword = line.Trim();
                if (keyword.Length > 0 && known.Add(keyword))
                {
                    target.Add(keyword);
                }
            }
        }

        private static int CountControls(Control root)
        {
            var count = 1;
            foreach (Control child in root.Controls)
            {
                count += CountControls(child);
            }
            return count;
        }

        private static int CountControlReference(Control root, Control sought)
        {
            var count = ReferenceEquals(root, sought) ? 1 : 0;
            foreach (Control child in root.Controls)
            {
                count += CountControlReference(child, sought);
            }
            return count;
        }

        [Conditional("DEBUG")]
        private void AssertStableControlTree()
        {
            Debug.Assert(CountControls(this) == initializedControlCount,
                "Settings layout must not create controls during resize or DPI changes.");
            Debug.Assert(CountControlReference(this, privacyMode) == 1,
                "Privacy checkbox must have exactly one instance.");
            Debug.Assert(CountControlReference(this, saveButton) == 1,
                "Save button must have exactly one instance.");
            Debug.Assert(CountControlReference(this, cancelButton) == 1,
                "Cancel button must have exactly one instance.");
            Debug.Assert(saveButton.Visible && cancelButton.Visible,
                "Settings action buttons must remain visible.");
            Debug.Assert(footerButtons.Controls.Count == 2,
                "Footer action table must contain exactly two buttons.");
        }

        internal static bool RunLayoutStructureSelfTest()
        {
            using (var form = new SettingsForm(
                new NotificationFilterSettings(),
                false,
                "\u72b6\u6001\uff1a\u7b49\u5f85\u9996\u6b21\u626b\u63cf",
                null))
            {
                var before = CountControls(form);
                form.ClientSize = new Size(700, 620);
                form.PerformLayout();
                form.ApplyResponsiveLayout(true);
                var narrowStable = CountControls(form) == before;
                form.ClientSize = new Size(1100, 780);
                form.PerformLayout();
                form.ApplyResponsiveLayout(true);
                return narrowStable &&
                    CountControls(form) == before &&
                    form.rootLayout is TableLayoutPanel &&
                    form.contentScrollPanel.AutoScroll &&
                    !ReferenceEquals(form.footerLayout.Parent, form.contentScrollPanel) &&
                    CountControlReference(form, form.privacyMode) == 1 &&
                    CountControlReference(form, form.saveButton) == 1 &&
                    CountControlReference(form, form.cancelButton) == 1;
            }
        }

        internal static bool RunDpiAndEditorSelfTest()
        {
            using (var form = new SettingsForm(
                new NotificationFilterSettings(),
                false,
                "\u72b6\u6001\uff1a\u7b49\u5f85\u9996\u6b21\u626b\u63cf",
                null))
            {
                var before = CountControls(form);
                form.serviceKeywords.Text = "  alpha  \r\n\r\n beta  ";
                ReplaceKeywords(
                    form.editedSettings.ServiceAccountAllowKeywords,
                    form.serviceKeywords.Text);
                var reloaded = form.editedSettings.Clone();
                return form.AutoScaleMode == AutoScaleMode.Dpi &&
                    form.Font.Unit == GraphicsUnit.Point &&
                    form.serviceKeywords.Font.Unit == GraphicsUnit.Point &&
                    form.serviceKeywords.Enabled &&
                    !form.serviceKeywords.ReadOnly &&
                    form.serviceKeywords.TabStop &&
                    form.serviceKeywords.Multiline &&
                    form.serviceKeywords.AcceptsReturn &&
                    form.officialKeywords.Enabled &&
                    !form.officialKeywords.ReadOnly &&
                    form.groupKeywords.Enabled &&
                    !form.groupKeywords.ReadOnly &&
                    CountControls(form) == before &&
                    form.footerButtons.Controls.Count == 2 &&
                    form.saveButton.Parent == form.footerButtons &&
                    form.cancelButton.Parent == form.footerButtons &&
                    reloaded.ServiceAccountAllowKeywords.Count == 2 &&
                    reloaded.ServiceAccountAllowKeywords[0] == "alpha" &&
                    reloaded.ServiceAccountAllowKeywords[1] == "beta";
            }
        }

        // Exercises the code path which previously failed only after a real
        // form handle had been created.  Keeping this off-screen makes the
        // command-line self-test non-disruptive while still covering normal
        // WinForms handle creation, DWM setup, layout and paint dispatch.
        internal static bool RunNativeSurfaceSmokeTest()
        {
            try
            {
                using (var form = new SettingsForm(
                    new NotificationFilterSettings(),
                    false,
                    "状态：等待首次扫描",
                    null))
                {
                    var handle = form.Handle;
                    if (handle == IntPtr.Zero)
                    {
                        return false;
                    }

                    var before = CountControls(form);
                    form.ClientSize = new Size(760, 640);
                    form.PerformLayout();
                    form.Invalidate(true);
                    using (var bitmap = new Bitmap(
                        Math.Max(1, form.Width),
                        Math.Max(1, form.Height)))
                    {
                        form.DrawToBitmap(
                            bitmap,
                            new Rectangle(0, 0, bitmap.Width, bitmap.Height));
                    }

                    return CountControls(form) == before &&
                        form.saveButton.Bounds.Width > 0 &&
                        form.cancelButton.Bounds.Width > 0 &&
                        form.serviceKeywords.Bounds.Width > 0 &&
                        form.officialKeywords.Bounds.Width > 0 &&
                        form.groupKeywords.Bounds.Width > 0;
                }
            }
            catch
            {
                return false;
            }
        }
    }
}
