// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Windows.Automation;

namespace WeChatMessageNotifier
{
    internal sealed class WeChatMonitor
    {
        // Monitoring is read-only: no input is injected into WeChat and no
        // database, process memory, or private protocol is accessed.
        private readonly Logger logger;
        private readonly SessionChangeDetector detector = new SessionChangeDetector();
        private IntPtr mainWindow;
        private DateTime lastWindowSearch = DateTime.MinValue;

        internal WeChatMonitor(Logger logger)
        {
            this.logger = logger;
        }

        internal IntPtr MainWindow
        {
            get { return mainWindow; }
        }

        internal int LastSessionCount { get; private set; }

        internal bool IsWeChatForeground()
        {
            var foreground = NativeMethods.GetForegroundWindow();
            if (foreground == IntPtr.Zero)
            {
                return false;
            }

            uint processId;
            NativeMethods.GetWindowThreadProcessId(foreground, out processId);
            try
            {
                using (var process = Process.GetProcessById((int)processId))
                {
                    return string.Equals(process.ProcessName, "Weixin", StringComparison.OrdinalIgnoreCase);
                }
            }
            catch
            {
                return false;
            }
        }

        internal IList<ChatSession> Poll()
        {
            try
            {
                if (!EnsureMainWindow())
                {
                    return new ChatSession[0];
                }

                var root = AutomationElement.FromHandle(mainWindow);
                if (root == null)
                {
                    mainWindow = IntPtr.Zero;
                    return new ChatSession[0];
                }

                var rawItems = FindSessionItems(root);
                var sessions = new List<ChatSession>();
                for (var index = 0; index < rawItems.Count; index++)
                {
                    string name;
                    string automationId;
                    try
                    {
                        name = rawItems[index].Current.Name;
                        automationId = rawItems[index].Current.AutomationId;
                    }
                    catch (ElementNotAvailableException)
                    {
                        continue;
                    }

                    var session = SessionParser.Parse(name, index, automationId);
                    if (session != null)
                    {
                        sessions.Add(session);
                    }
                }

                LastSessionCount = sessions.Count;
                return detector.Update(sessions, DateTime.Now);
            }
            catch (ElementNotAvailableException)
            {
                mainWindow = IntPtr.Zero;
                return new ChatSession[0];
            }
            catch (Exception exception)
            {
                logger.Error("Polling failed", exception);
                mainWindow = IntPtr.Zero;
                return new ChatSession[0];
            }
        }

        internal void ActivateWeChat()
        {
            if (!EnsureMainWindow())
            {
                return;
            }

            // Do not call SW_RESTORE on a maximized window: doing so would
            // unintentionally downgrade it to a normal window.
            if (NativeMethods.IsIconic(mainWindow))
            {
                NativeMethods.ShowWindow(mainWindow, NativeMethods.SwRestore);
            }
            else if (!NativeMethods.IsWindowVisible(mainWindow))
            {
                NativeMethods.ShowWindow(
                    mainWindow,
                    NativeMethods.IsZoomed(mainWindow)
                        ? NativeMethods.SwShowMaximized
                        : NativeMethods.SwShow);
            }
            NativeMethods.SetForegroundWindow(mainWindow);
        }

        private bool EnsureMainWindow()
        {
            if (mainWindow != IntPtr.Zero && NativeMethods.IsWindow(mainWindow))
            {
                return true;
            }

            if ((DateTime.Now - lastWindowSearch).TotalSeconds < 5)
            {
                return false;
            }

            lastWindowSearch = DateTime.Now;
            var processIds = new HashSet<uint>(
                Process.GetProcessesByName("Weixin").Select(delegate(Process process) { return (uint)process.Id; }));
            if (processIds.Count == 0)
            {
                return false;
            }

            var candidates = new List<IntPtr>();
            NativeMethods.EnumWindows(delegate(IntPtr hWnd, IntPtr ignored)
            {
                uint processId;
                NativeMethods.GetWindowThreadProcessId(hWnd, out processId);
                if (processIds.Contains(processId) &&
                    NativeMethods.ReadClassName(hWnd).IndexOf("Qt", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    candidates.Add(hWnd);
                }
                return true;
            }, IntPtr.Zero);

            IntPtr best = IntPtr.Zero;
            var bestScore = -1;
            foreach (var candidate in candidates)
            {
                try
                {
                    var root = AutomationElement.FromHandle(candidate);
                    if (root == null)
                    {
                        continue;
                    }

                    var items = FindSessionItems(root);
                    var score = items.Count;
                    if (NativeMethods.IsWindowVisible(candidate))
                    {
                        score += 100;
                    }
                    if (score > bestScore && items.Count > 0)
                    {
                        best = candidate;
                        bestScore = score;
                    }
                }
                catch
                {
                    // Ignore auxiliary Qt windows that do not expose UI Automation.
                }
            }

            if (best != IntPtr.Zero)
            {
                mainWindow = best;
                logger.Info("Attached to WeChat main window.");
                return true;
            }

            return false;
        }

        private static List<AutomationElement> FindSessionItems(AutomationElement root)
        {
            var lists = root.FindAll(
                TreeScope.Descendants,
                new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.List));

            var best = new List<AutomationElement>();
            var bestScore = -1;
            foreach (AutomationElement list in lists)
            {
                var children = list.FindAll(
                    TreeScope.Children,
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem));
                var candidates = new List<AutomationElement>();
                var multilineCount = 0;

                foreach (AutomationElement child in children)
                {
                    string name;
                    try
                    {
                        name = child.Current.Name ?? string.Empty;
                    }
                    catch
                    {
                        continue;
                    }

                    if (name.IndexOf('\n') >= 0)
                    {
                        multilineCount++;
                    }
                    candidates.Add(child);
                }

                // The navigation list has short one-line names. The real chat
                // session list consistently contains multiline accessible names.
                var score = multilineCount * 10 + candidates.Count;
                if (score > bestScore && multilineCount > 0)
                {
                    best = candidates;
                    bestScore = score;
                }
            }

            return best;
        }
    }
}
