// Initial implementation generated by OpenAI Codex on 2026-06-29
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Windows.Automation;

namespace WeChatMessageNotifier
{
    internal sealed class WeChatMonitor
    {
        // Monitoring is read-only: no database, process memory, or private
        // protocol is accessed. A user-initiated popup click may post one
        // local click to the matched visible chat row for navigation.
        private readonly Logger logger;
        private readonly SessionChangeDetector detector = new SessionChangeDetector();
        private readonly Dictionary<ChatSessionKind, int> lastKindCounts =
            new Dictionary<ChatSessionKind, int>();
        private IntPtr mainWindow;
        private DateTime lastWindowSearch = DateTime.MinValue;

        internal WeChatMonitor(Logger logger)
        {
            this.logger = logger;
        }

        internal IntPtr MainWindow
        {
            get { return mainWindow; }
        }

        internal int LastSessionCount { get; private set; }

        internal int LastSelectedSessionCount { get; private set; }

        internal int LastMutedSessionCount { get; private set; }

        internal int LastGroupMarkerCount { get; private set; }

        internal int GetLastSessionKindCount(ChatSessionKind kind)
        {
            int count;
            return lastKindCounts.TryGetValue(kind, out count) ? count : 0;
        }

        internal bool IsWeChatForeground()
        {
            var foreground = NativeMethods.GetForegroundWindow();
            if (foreground == IntPtr.Zero)
            {
                return false;
            }

            uint processId;
            NativeMethods.GetWindowThreadProcessId(foreground, out processId);
            try
            {
                using (var process = Process.GetProcessById((int)processId))
                {
                    return string.Equals(process.ProcessName, "Weixin", StringComparison.OrdinalIgnoreCase);
                }
            }
            catch
            {
                return false;
            }
        }

        internal IList<ChatSession> Poll()
        {
            try
            {
                if (!EnsureMainWindow())
                {
                    return new ChatSession[0];
                }

                var root = AutomationElement.FromHandle(mainWindow);
                if (root == null)
                {
                    mainWindow = IntPtr.Zero;
                    return new ChatSession[0];
                }

                var rawItems = FindSessionItems(root);
                var sessions = new List<ChatSession>();
                for (var index = 0; index < rawItems.Count; index++)
                {
                    string name;
                    string automationId;
                    try
                    {
                        name = rawItems[index].Current.Name;
                        automationId = rawItems[index].Current.AutomationId;
                    }
                    catch (ElementNotAvailableException)
                    {
                        continue;
                    }

                    var session = SessionParser.Parse(name, index, automationId);
                    if (session != null)
                    {
                        object selectionPattern;
                        if (rawItems[index].TryGetCurrentPattern(
                            SelectionItemPattern.Pattern,
                            out selectionPattern))
                        {
                            try
                            {
                                session.IsSelected =
                                    ((SelectionItemPattern)selectionPattern)
                                    .Current.IsSelected;
                            }
                            catch (ElementNotAvailableException)
                            {
                                session.IsSelected = false;
                            }
                        }
                        sessions.Add(session);
                    }
                }

                LastSessionCount = sessions.Count;
                LastSelectedSessionCount = sessions.Count(
                    delegate(ChatSession session) { return session.IsSelected; });
                LastMutedSessionCount = sessions.Count(
                    delegate(ChatSession session) { return session.IsMuted; });
                LastGroupMarkerCount = sessions.Count(
                    delegate(ChatSession session)
                    {
                        return session.HasGroupMarker;
                    });
                lastKindCounts.Clear();
                foreach (var session in sessions)
                {
                    int count;
                    lastKindCounts.TryGetValue(session.Kind, out count);
                    lastKindCounts[session.Kind] = count + 1;
                }
                var changes = detector.Update(
                    sessions,
                    DateTime.Now,
                    IsWeChatForeground());
                if (detector.LastOutgoingSuppressedCount > 0)
                {
                    logger.Info(
                        "Suppressed " +
                        detector.LastOutgoingSuppressedCount +
                        " outgoing message change(s).");
                }
                return changes;
            }
            catch (ElementNotAvailableException)
            {
                mainWindow = IntPtr.Zero;
                return new ChatSession[0];
            }
            catch (Exception exception)
            {
                logger.Error("Polling failed", exception);
                mainWindow = IntPtr.Zero;
                return new ChatSession[0];
            }
        }

        internal void ActivateWeChat()
        {
            ActivateWeChat(null);
        }

        internal void ActivateWeChat(string sessionKey)
        {
            if (!EnsureMainWindow())
            {
                return;
            }

            // Do not call SW_RESTORE on a maximized window: doing so would
            // unintentionally downgrade it to a normal window.
            if (NativeMethods.IsIconic(mainWindow))
            {
                NativeMethods.ShowWindow(mainWindow, NativeMethods.SwRestore);
            }
            else if (!NativeMethods.IsWindowVisible(mainWindow))
            {
                NativeMethods.ShowWindow(
                    mainWindow,
                    NativeMethods.IsZoomed(mainWindow)
                        ? NativeMethods.SwShowMaximized
                        : NativeMethods.SwShow);
            }
            NativeMethods.SetForegroundWindow(mainWindow);

            if (string.IsNullOrWhiteSpace(sessionKey))
            {
                return;
            }

            try
            {
                var root = AutomationElement.FromHandle(mainWindow);
                if (root == null)
                {
                    return;
                }

                foreach (var item in FindSessionItems(root))
                {
                    string name;
                    string automationId;
                    try
                    {
                        name = item.Current.Name;
                        automationId = item.Current.AutomationId;
                    }
                    catch (ElementNotAvailableException)
                    {
                        continue;
                    }

                    var session = SessionParser.Parse(name, 0, automationId);
                    if (session == null ||
                        !string.Equals(
                            session.SessionKey,
                            sessionKey,
                            StringComparison.Ordinal))
                    {
                        continue;
                    }

                    object pattern;
                    if (item.TryGetCurrentPattern(
                        ScrollItemPattern.Pattern,
                        out pattern))
                    {
                        ((ScrollItemPattern)pattern).ScrollIntoView();
                    }

                    // WeChat 4.x exposes both Invoke and SelectionItem on chat
                    // rows. Invoke may return successfully without changing the
                    // active conversation (notably for service accounts), while
                    // SelectionItem is the semantic operation for a list row.
                    if (item.TryGetCurrentPattern(
                        SelectionItemPattern.Pattern,
                        out pattern))
                    {
                        ((SelectionItemPattern)pattern).Select();
                        logger.Info(
                            "Target WeChat session activated with selection pattern.");
                    }
                    else if (item.TryGetCurrentPattern(
                        InvokePattern.Pattern,
                        out pattern))
                    {
                        ((InvokePattern)pattern).Invoke();
                        logger.Info(
                            "Target WeChat session activated with invoke pattern.");
                    }
                    else
                    {
                        item.SetFocus();
                        logger.Info(
                            "Target WeChat session activated with focus fallback.");
                    }

                    // On WeChat 4.x, SelectionItem.Select can report success
                    // without refreshing the conversation pane. Post a click
                    // directly to the visible row inside WeChat. This neither
                    // moves the user's pointer nor sends global mouse input.
                    var rectangle = item.Current.BoundingRectangle;
                    if (!rectangle.IsEmpty)
                    {
                        var center = new System.Drawing.Point(
                            (int)(rectangle.Left + rectangle.Width / 2),
                            (int)(rectangle.Top + rectangle.Height / 2));
                        if (NativeMethods.PostLeftClick(mainWindow, center))
                        {
                            logger.Info(
                                "Target WeChat session row click posted.");
                        }
                        else
                        {
                            logger.Info(
                                "Target WeChat session row click could not be posted.");
                        }
                    }

                    return;
                }

                logger.Info("Target WeChat session was not available in the loaded list.");
            }
            catch (Exception exception)
            {
                logger.Error("Could not activate target WeChat session", exception);
            }
        }

        private bool EnsureMainWindow()
        {
            if (mainWindow != IntPtr.Zero && NativeMethods.IsWindow(mainWindow))
            {
                return true;
            }

            if ((DateTime.Now - lastWindowSearch).TotalSeconds < 5)
            {
                return false;
            }

            lastWindowSearch = DateTime.Now;
            var processIds = new HashSet<uint>(
                Process.GetProcessesByName("Weixin").Select(delegate(Process process) { return (uint)process.Id; }));
            if (processIds.Count == 0)
            {
                return false;
            }

            var candidates = new List<IntPtr>();
            NativeMethods.EnumWindows(delegate(IntPtr hWnd, IntPtr ignored)
            {
                uint processId;
                NativeMethods.GetWindowThreadProcessId(hWnd, out processId);
                if (processIds.Contains(processId) &&
                    NativeMethods.ReadClassName(hWnd).IndexOf("Qt", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    candidates.Add(hWnd);
                }
                return true;
            }, IntPtr.Zero);

            IntPtr best = IntPtr.Zero;
            var bestScore = -1;
            foreach (var candidate in candidates)
            {
                try
                {
                    var root = AutomationElement.FromHandle(candidate);
                    if (root == null)
                    {
                        continue;
                    }

                    var items = FindSessionItems(root);
                    var score = items.Count;
                    if (NativeMethods.IsWindowVisible(candidate))
                    {
                        score += 100;
                    }
                    if (score > bestScore && items.Count > 0)
                    {
                        best = candidate;
                        bestScore = score;
                    }
                }
                catch
                {
                    // Ignore auxiliary Qt windows that do not expose UI Automation.
                }
            }

            if (best != IntPtr.Zero)
            {
                mainWindow = best;
                logger.Info("Attached to WeChat main window.");
                return true;
            }

            return false;
        }

        private static List<AutomationElement> FindSessionItems(AutomationElement root)
        {
            var lists = root.FindAll(
                TreeScope.Descendants,
                new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.List));

            var best = new List<AutomationElement>();
            var bestScore = -1;
            foreach (AutomationElement list in lists)
            {
                var children = list.FindAll(
                    TreeScope.Children,
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem));
                var candidates = new List<AutomationElement>();
                var multilineCount = 0;

                foreach (AutomationElement child in children)
                {
                    string name;
                    try
                    {
                        name = child.Current.Name ?? string.Empty;
                    }
                    catch
                    {
                        continue;
                    }

                    if (name.IndexOf('\n') >= 0)
                    {
                        multilineCount++;
                    }
                    candidates.Add(child);
                }

                // The navigation list has short one-line names. The real chat
                // session list consistently contains multiline accessible names.
                var score = multilineCount * 10 + candidates.Count;
                if (score > bestScore && multilineCount > 0)
                {
                    best = candidates;
                    bestScore = score;
                }
            }

            return best;
        }
    }
}
