// Windows notification center integration generated by OpenAI Codex on 2026-07-01
// under the direction of the project owner.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;
using Windows.Data.Xml.Dom;
using Windows.UI.Notifications;

namespace WeChatMessageNotifier
{
    internal sealed class WindowsNotificationCenter : IDisposable
    {
        private const string AppUserModelId = "OpenAICodex.WeChatMessageNotifier";
        private const string ShortcutName = "WeChat Message Notifier.lnk";
        private const string ProtocolName = "wechat-message-notifier";
        private const string ProtocolUri = ProtocolName + "://open";

        private readonly Action<ToastActivationRequest> activateWeChat;
        private readonly Logger logger;
        private readonly SynchronizationContext uiContext;
        private readonly bool emitNativeToast;
        private readonly Dictionary<string, NotificationState> states =
            new Dictionary<string, NotificationState>(StringComparer.Ordinal);
        private readonly List<TrackedToast> activeToasts =
            new List<TrackedToast>();
        private int nextTag;
        private bool available;
        private bool disposed;
        private string lastTagForTest;
        private string lastGroupForTest;
        private string lastTitleForTest;
        private string lastMessageForTest;
        private bool lastSuppressPopupForTest;
        private int showCountForTest;
        private string toastLogoPath;

        internal WindowsNotificationCenter(Action<ToastActivationRequest> activateWeChat, Logger logger)
            : this(activateWeChat, logger, true, true)
        {
        }

        internal WindowsNotificationCenter(
            Action<ToastActivationRequest> activateWeChat,
            Logger logger,
            bool registerWithWindows,
            bool emitNativeToast)
        {
            this.activateWeChat = activateWeChat;
            this.logger = logger;
            this.emitNativeToast = emitNativeToast;
            uiContext = SynchronizationContext.Current;

            try
            {
                if (registerWithWindows)
                {
                    NativeMethods.SetCurrentProcessExplicitAppUserModelID(
                        AppUserModelId);
                    var iconSourcePath = ResolveWeChatIconSourcePath();
                    toastLogoPath = PrepareToastLogo(iconSourcePath);
                    EnsureStartMenuShortcut(iconSourcePath);
                    EnsureProtocolRegistration();
                    logger.Info(
                        "Windows toast icon initialized. HasWeChatIconSource=" +
                        (!string.IsNullOrWhiteSpace(iconSourcePath) &&
                         File.Exists(iconSourcePath)) +
                        " HasToastLogo=" +
                        (!string.IsNullOrWhiteSpace(toastLogoPath) &&
                         File.Exists(toastLogoPath)));
                }
                available = true;
                logger.Info("Windows notification center integration initialized.");
            }
            catch (Exception exception)
            {
                available = false;
                logger.Error("Windows notification center initialization failed", exception);
            }
        }

        internal WindowsNotificationCenter(Action<string> activateWeChat, Logger logger, bool registerWithWindows, bool emitNativeToast)
            : this(delegate(ToastActivationRequest request)
            {
                if (activateWeChat != null)
                {
                    activateWeChat(request == null ? null : request.SessionKey);
                }
            }, logger, registerWithWindows, emitNativeToast)
        {
        }

        internal bool Show(string title, string message, bool suppressPopup)
        {
            nextTag++;
            return ShowToast(
                "general-" + nextTag.ToString("D6"),
                title,
                message,
                suppressPopup,
                null);
        }

        internal int ShowMessage(
            string sessionKey,
            ChatSessionKind sessionKind,
            string title,
            string latestPreview,
            bool privacyMode,
            bool suppressPopup)
        {
            if (string.IsNullOrWhiteSpace(sessionKey))
            {
                sessionKey = title;
            }

            NotificationState state;
            if (!states.TryGetValue(sessionKey, out state))
            {
                state = new NotificationState(BuildTag(sessionKey));
                states.Add(sessionKey, state);
            }
            state.Update();

            var displayedTitle = state.MessageCount > 1
                ? title + "\uFF08" + state.MessageCount + "\u6761\u65B0\u6D88\u606F\uFF09"
                : title;
            var displayedMessage = FormatMessageBody(
                latestPreview,
                state.MessageCount,
                privacyMode);
            ShowToast(
                state.Tag,
                displayedTitle,
                displayedMessage,
                suppressPopup,
                ToastActivationRequest.FromSession(sessionKey, sessionKind));
            return state.MessageCount;
        }

        internal int ShowMessage(
            string sessionKey,
            string title,
            string latestPreview,
            bool privacyMode,
            bool suppressPopup)
        {
            return ShowMessage(sessionKey, ChatSessionKind.Unknown, title, latestPreview, privacyMode, suppressPopup);
        }

        internal int GetMessageCountForTest(string sessionKey)
        {
            NotificationState state;
            return states.TryGetValue(sessionKey, out state)
                ? state.MessageCount
                : 0;
        }

        internal string GetTagForTest(string sessionKey)
        {
            NotificationState state;
            return states.TryGetValue(sessionKey, out state)
                ? state.Tag
                : null;
        }

        // A successful toast activation means the user is now viewing this
        // conversation in WeChat. Clear both the in-memory aggregation state
        // and the matching Notification Center history entry, so the next
        // incoming message starts again at one rather than inheriting stale
        // unread-count text.
        internal void ClearSession(string sessionKey)
        {
            if (string.IsNullOrWhiteSpace(sessionKey))
            {
                return;
            }

            NotificationState state;
            if (!states.TryGetValue(sessionKey, out state))
            {
                return;
            }

            states.Remove(sessionKey);
            RemoveTrackedToast(state.Tag);
            if (emitNativeToast && available && !disposed)
            {
                try
                {
                    ToastNotificationManager.History.Remove(
                        state.Tag,
                        "wechat",
                        AppUserModelId);
                }
                catch (Exception exception)
                {
                    // History removal is best-effort. The in-memory state is
                    // already reset, so a transient WinRT failure must not
                    // block future notifications for this conversation.
                    logger.Error("Could not remove notification center entry", exception);
                }
            }
            logger.Info("Notification state cleared after successful activation.");
        }

        internal int ActiveSessionCountForTest
        {
            get { return states.Count; }
        }

        internal string LastTagForTest
        {
            get { return lastTagForTest; }
        }

        internal string LastGroupForTest
        {
            get { return lastGroupForTest; }
        }

        internal string LastTitleForTest
        {
            get { return lastTitleForTest; }
        }

        internal string LastMessageForTest
        {
            get { return lastMessageForTest; }
        }

        internal bool LastSuppressPopupForTest
        {
            get { return lastSuppressPopupForTest; }
        }

        internal int ShowCountForTest
        {
            get { return showCountForTest; }
        }

        internal string ToastLogoPathForTest
        {
            get { return toastLogoPath; }
        }

        internal void SimulateActivationForTest(string sessionKey)
        {
            if (activateWeChat != null)
            {
                activateWeChat(ToastActivationRequest.FromSession(sessionKey, ChatSessionKind.Unknown));
            }
        }

        internal static string BuildFileUriForTest(string path)
        {
            return BuildFileUri(path);
        }

        internal static string ResolveWeChatIconSourcePathForTest()
        {
            return ResolveWeChatIconSourcePath();
        }

        private bool ShowToast(
            string tag,
            string title,
            string message,
            bool suppressPopup,
            ToastActivationRequest activationRequest)
        {
            if (!available || disposed)
            {
                return false;
            }

            try
            {
                lastTagForTest = tag;
                lastGroupForTest = "wechat";
                lastTitleForTest = title;
                lastMessageForTest = message;
                lastSuppressPopupForTest = suppressPopup;
                showCountForTest++;

                if (!emitNativeToast)
                {
                    return true;
                }

                var xml = ToastNotificationManager.GetTemplateContent(
                    ToastTemplateType.ToastText02);
                var textNodes = xml.GetElementsByTagName("text");
                textNodes[0].AppendChild(xml.CreateTextNode(title));
                textNodes[1].AppendChild(xml.CreateTextNode(message));
                TryAddAppLogoOverride(xml, toastLogoPath);
                xml.DocumentElement.SetAttribute(
                    "launch",
                    BuildProtocolUri(activationRequest));
                xml.DocumentElement.SetAttribute("activationType", "protocol");

                var history = ToastNotificationManager.History.GetHistory(
                    AppUserModelId);
                if (history.Count == 0)
                {
                    nextTag = 0;
                    ClearTrackedToasts();
                }
                nextTag++;

                var toast = new ToastNotification(xml)
                {
                    SuppressPopup = suppressPopup,
                    Group = "wechat",
                    Tag = tag
                };
                Windows.Foundation.TypedEventHandler<ToastNotification, object>
                    activatedHandler = null;
                Windows.Foundation.TypedEventHandler<
                    ToastNotification,
                    ToastDismissedEventArgs> dismissedHandler = null;
                Windows.Foundation.TypedEventHandler<
                    ToastNotification,
                    ToastFailedEventArgs> failedHandler = null;

                activatedHandler =
                    new Windows.Foundation.TypedEventHandler<ToastNotification, object>(
                    delegate
                    {
                        Activate(activationRequest);
                        Release(toast);
                    });
                dismissedHandler =
                    new Windows.Foundation.TypedEventHandler<
                        ToastNotification,
                        ToastDismissedEventArgs>(
                    delegate { Release(toast); });
                failedHandler =
                    new Windows.Foundation.TypedEventHandler<
                        ToastNotification,
                        ToastFailedEventArgs>(
                    delegate
                    {
                        logger.Info(
                            "Windows toast failed. Notification may be blocked by Windows notification settings, focus assist, or system policy.");
                        Release(toast);
                    });

                toast.Activated += activatedHandler;
                toast.Dismissed += dismissedHandler;
                toast.Failed += failedHandler;

                activeToasts.Add(
                    new TrackedToast(
                        toast,
                        activatedHandler,
                        dismissedHandler,
                        failedHandler));
                if (activeToasts.Count > 100)
                {
                    ReleaseTracked(activeToasts[0]);
                }
                ToastNotificationManager
                    .CreateToastNotifier(AppUserModelId)
                    .Show(toast);
                logger.Info(
                    "Notification center entry added. PopupSuppressed=" +
                    suppressPopup +
                    " Tag=" + tag +
                    " Group=wechat" +
                    " TitleLength=" + title.Length +
                    " MessageLength=" + message.Length);
                return true;
            }
            catch (Exception exception)
            {
                logger.Error("Could not add notification center entry", exception);
                return false;
            }
        }

        private void Activate(ToastActivationRequest activationRequest)
        {
            if (uiContext != null)
            {
                uiContext.Post(delegate
                {
                    if (activateWeChat != null)
                    {
                        activateWeChat(activationRequest);
                    }
                }, null);
            }
            else if (activateWeChat != null)
            {
                activateWeChat(activationRequest);
            }
        }

        private static string FormatMessageBody(
            string latestPreview,
            int messageCount,
            bool privacyMode)
        {
            if (privacyMode)
            {
                return messageCount > 1
                    ? "\u6536\u5230 " + messageCount + " \u6761\u65B0\u6D88\u606F"
                    : "\u6536\u5230\u4E00\u6761\u65B0\u6D88\u606F";
            }

            return messageCount > 1
                ? "\u6536\u5230 " + messageCount + " \u6761\u65B0\u6D88\u606F\uFF1A" + latestPreview
                : latestPreview;
        }

        private static string BuildProtocolUri(ToastActivationRequest activationRequest)
        {
            if (activationRequest == null || string.IsNullOrWhiteSpace(activationRequest.SessionKey))
            {
                return ProtocolUri;
            }

            return ProtocolUri +
                "?session=" + Uri.EscapeDataString(activationRequest.SessionKey) +
                "&kind=" + Uri.EscapeDataString(activationRequest.SessionKind.ToString()) +
                "&route=" + Uri.EscapeDataString(activationRequest.Route.ToString());
        }

        private static string BuildTag(string sessionKey)
        {
            using (var sha256 = SHA256.Create())
            {
                var bytes = sha256.ComputeHash(
                    Encoding.UTF8.GetBytes(sessionKey ?? string.Empty));
                var builder = new StringBuilder("session-", 24);
                for (var index = 0; index < 8; index++)
                {
                    builder.Append(bytes[index].ToString("x2"));
                }
                return builder.ToString();
            }
        }

        private static void TryAddAppLogoOverride(
            XmlDocument xml,
            string logoPath)
        {
            if (string.IsNullOrWhiteSpace(logoPath) ||
                !File.Exists(logoPath))
            {
                return;
            }

            var bindings = xml.GetElementsByTagName("binding");
            if (bindings == null || bindings.Length == 0)
            {
                return;
            }

            var binding = bindings[0] as XmlElement;
            if (binding == null)
            {
                return;
            }

            var image = xml.CreateElement("image");
            image.SetAttribute("placement", "appLogoOverride");
            image.SetAttribute("hint-crop", "circle");
            image.SetAttribute("src", BuildFileUri(logoPath));
            binding.AppendChild(image);
        }

        private static string BuildFileUri(string path)
        {
            return new Uri(path).AbsoluteUri;
        }

        private static string PrepareToastLogo(string iconSourcePath)
        {
            if (string.IsNullOrWhiteSpace(iconSourcePath) ||
                !File.Exists(iconSourcePath))
            {
                return null;
            }

            try
            {
                using (var icon = Icon.ExtractAssociatedIcon(iconSourcePath))
                {
                    if (icon == null)
                    {
                        return null;
                    }

                    var directory = Path.Combine(
                        Environment.GetFolderPath(
                            Environment.SpecialFolder.LocalApplicationData),
                        "WeChatMessageNotifier");
                    Directory.CreateDirectory(directory);
                    var iconPath = Path.Combine(
                        directory,
                        "weixin-toast-icon.png");
                    using (var bitmap = icon.ToBitmap())
                    {
                        bitmap.Save(iconPath, ImageFormat.Png);
                    }
                    return iconPath;
                }
            }
            catch
            {
                return null;
            }
        }

        private static string ResolveWeChatIconSourcePath()
        {
            var processPath = FindRunningWeChatProcessPath();
            if (!string.IsNullOrWhiteSpace(processPath))
            {
                return processPath;
            }

            foreach (var candidate in GetCommonWeChatExecutablePaths())
            {
                if (!string.IsNullOrWhiteSpace(candidate) &&
                    File.Exists(candidate))
                {
                    return candidate;
                }
            }

            return null;
        }

        private static string FindRunningWeChatProcessPath()
        {
            foreach (var processName in new[] { "Weixin", "WeChat" })
            {
                try
                {
                    foreach (var process in
                        System.Diagnostics.Process.GetProcessesByName(
                            processName))
                    {
                        using (process)
                        {
                            try
                            {
                                if (!string.IsNullOrWhiteSpace(process.MainModule.FileName) &&
                                    File.Exists(process.MainModule.FileName))
                                {
                                    return process.MainModule.FileName;
                                }
                            }
                            catch
                            {
                                // Access to another process module can be
                                // blocked by Windows. Fall through to common
                                // installation paths below.
                            }
                        }
                    }
                }
                catch
                {
                    // Best-effort process lookup.
                }
            }

            return null;
        }

        private static IEnumerable<string> GetCommonWeChatExecutablePaths()
        {
            var programFiles = Environment.GetFolderPath(
                Environment.SpecialFolder.ProgramFiles);
            var programFilesX86 = Environment.GetFolderPath(
                Environment.SpecialFolder.ProgramFilesX86);
            var localAppData = Environment.GetFolderPath(
                Environment.SpecialFolder.LocalApplicationData);
            var appData = Environment.GetFolderPath(
                Environment.SpecialFolder.ApplicationData);

            yield return Path.Combine(programFiles, "Tencent", "Weixin", "Weixin.exe");
            yield return Path.Combine(programFilesX86, "Tencent", "Weixin", "Weixin.exe");
            yield return Path.Combine(localAppData, "Tencent", "Weixin", "Weixin.exe");
            yield return Path.Combine(appData, "Tencent", "Weixin", "Weixin.exe");
            yield return Path.Combine(programFiles, "Tencent", "WeChat", "WeChat.exe");
            yield return Path.Combine(programFilesX86, "Tencent", "WeChat", "WeChat.exe");
            yield return Path.Combine(localAppData, "Tencent", "WeChat", "WeChat.exe");
            yield return Path.Combine(appData, "Tencent", "WeChat", "WeChat.exe");
        }

        public void Dispose()
        {
            disposed = true;
            if (uiContext != null &&
                !object.ReferenceEquals(SynchronizationContext.Current, uiContext))
            {
                uiContext.Post(delegate { ClearTrackedToasts(); }, null);
            }
            else
            {
                ClearTrackedToasts();
            }
        }

        private void Release(ToastNotification toast)
        {
            if (uiContext != null)
            {
                uiContext.Post(delegate { ReleaseOnCurrentThread(toast); }, null);
            }
            else
            {
                ReleaseOnCurrentThread(toast);
            }
        }

        private void ReleaseOnCurrentThread(ToastNotification toast)
        {
            for (var index = 0; index < activeToasts.Count; index++)
            {
                if (object.ReferenceEquals(activeToasts[index].Toast, toast))
                {
                    ReleaseTracked(activeToasts[index]);
                    return;
                }
            }
        }

        private void ReleaseTracked(TrackedToast tracked)
        {
            tracked.Detach();
            activeToasts.Remove(tracked);
        }

        private void RemoveTrackedToast(string tag)
        {
            for (var index = activeToasts.Count - 1; index >= 0; index--)
            {
                var toast = activeToasts[index].Toast;
                if (toast != null && string.Equals(
                    toast.Tag,
                    tag,
                    StringComparison.Ordinal))
                {
                    ReleaseTracked(activeToasts[index]);
                }
            }
        }

        private void ClearTrackedToasts()
        {
            foreach (var tracked in activeToasts.ToArray())
            {
                tracked.Detach();
            }
            activeToasts.Clear();
        }

        private static void EnsureStartMenuShortcut(string iconSourcePath)
        {
            var programs = Environment.GetFolderPath(
                Environment.SpecialFolder.Programs);
            var shortcutPath = Path.Combine(programs, ShortcutName);
            var executablePath = Application.ExecutablePath;
            var shortcutIconPath =
                !string.IsNullOrWhiteSpace(iconSourcePath) &&
                File.Exists(iconSourcePath)
                    ? iconSourcePath
                    : executablePath;

            var shellLinkObject = Activator.CreateInstance(
                Type.GetTypeFromCLSID(
                    new Guid("00021401-0000-0000-C000-000000000046")));
            var shellLink = (IShellLinkW)shellLinkObject;
            shellLink.SetPath(executablePath);
            shellLink.SetWorkingDirectory(Path.GetDirectoryName(executablePath));
            shellLink.SetDescription("Windows 微信消息提醒器");
            shellLink.SetIconLocation(shortcutIconPath, 0);

            var propertyStore = (IPropertyStore)shellLinkObject;
            var appIdKey = new PropertyKey(
                new Guid("9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3"),
                5);
            var appIdValue = PropVariant.FromString(AppUserModelId);
            try
            {
                propertyStore.SetValue(ref appIdKey, ref appIdValue);
                propertyStore.Commit();
            }
            finally
            {
                appIdValue.Clear();
            }

            ((IPersistFile)shellLinkObject).Save(shortcutPath, true);
        }

        private static void EnsureProtocolRegistration()
        {
            using (var protocol = Registry.CurrentUser.CreateSubKey(
                @"Software\Classes\" + ProtocolName))
            {
                protocol.SetValue(string.Empty, "URL:WeChat Message Notifier");
                protocol.SetValue("URL Protocol", string.Empty);
                using (var command = protocol.CreateSubKey(@"shell\open\command"))
                {
                    command.SetValue(
                        string.Empty,
                        "\"" + Application.ExecutablePath +
                        "\" --toast-activate \"%1\"");
                }
            }
        }

        [ComImport]
        [Guid("000214F9-0000-0000-C000-000000000046")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        private interface IShellLinkW
        {
            void GetPath(
                [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder file,
                int maximum,
                IntPtr findData,
                uint flags);
            void GetIdList(out IntPtr itemIdList);
            void SetIdList(IntPtr itemIdList);
            void GetDescription(
                [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder description,
                int maximum);
            void SetDescription([MarshalAs(UnmanagedType.LPWStr)] string description);
            void GetWorkingDirectory(
                [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder directory,
                int maximum);
            void SetWorkingDirectory([MarshalAs(UnmanagedType.LPWStr)] string directory);
            void GetArguments(
                [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder arguments,
                int maximum);
            void SetArguments([MarshalAs(UnmanagedType.LPWStr)] string arguments);
            void GetHotkey(out short hotkey);
            void SetHotkey(short hotkey);
            void GetShowCommand(out int showCommand);
            void SetShowCommand(int showCommand);
            void GetIconLocation(
                [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder iconPath,
                int maximum,
                out int iconIndex);
            void SetIconLocation(
                [MarshalAs(UnmanagedType.LPWStr)] string iconPath,
                int iconIndex);
            void SetRelativePath(
                [MarshalAs(UnmanagedType.LPWStr)] string path,
                uint reserved);
            void Resolve(IntPtr window, uint flags);
            void SetPath([MarshalAs(UnmanagedType.LPWStr)] string path);
        }

        [ComImport]
        [Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        private interface IPropertyStore
        {
            uint GetCount();
            PropertyKey GetAt(uint index);
            void GetValue(ref PropertyKey key, out PropVariant value);
            void SetValue(ref PropertyKey key, ref PropVariant value);
            void Commit();
        }

        [StructLayout(LayoutKind.Sequential, Pack = 4)]
        private struct PropertyKey
        {
            internal Guid FormatId;
            internal uint PropertyId;

            internal PropertyKey(Guid formatId, uint propertyId)
            {
                FormatId = formatId;
                PropertyId = propertyId;
            }
        }

        [StructLayout(LayoutKind.Explicit)]
        private struct PropVariant
        {
            [FieldOffset(0)]
            private ushort type;

            [FieldOffset(8)]
            private IntPtr pointer;

            internal static PropVariant FromString(string value)
            {
                return new PropVariant
                {
                    type = 31,
                    pointer = Marshal.StringToCoTaskMemUni(value)
                };
            }

            internal void Clear()
            {
                PropVariantClear(ref this);
            }
        }

        [DllImport("ole32.dll")]
        private static extern int PropVariantClear(ref PropVariant value);

        private sealed class TrackedToast
        {
            private readonly Windows.Foundation.TypedEventHandler<
                ToastNotification,
                object> activatedHandler;
            private readonly Windows.Foundation.TypedEventHandler<
                ToastNotification,
                ToastDismissedEventArgs> dismissedHandler;
            private readonly Windows.Foundation.TypedEventHandler<
                ToastNotification,
                ToastFailedEventArgs> failedHandler;
            private bool detached;

            internal TrackedToast(
                ToastNotification toast,
                Windows.Foundation.TypedEventHandler<
                    ToastNotification,
                    object> activatedHandler,
                Windows.Foundation.TypedEventHandler<
                    ToastNotification,
                    ToastDismissedEventArgs> dismissedHandler,
                Windows.Foundation.TypedEventHandler<
                    ToastNotification,
                    ToastFailedEventArgs> failedHandler)
            {
                Toast = toast;
                this.activatedHandler = activatedHandler;
                this.dismissedHandler = dismissedHandler;
                this.failedHandler = failedHandler;
            }

            internal ToastNotification Toast { get; private set; }

            internal void Detach()
            {
                if (detached || Toast == null)
                {
                    return;
                }

                try
                {
                    Toast.Activated -= activatedHandler;
                    Toast.Dismissed -= dismissedHandler;
                    Toast.Failed -= failedHandler;
                }
                catch (Exception)
                {
                    // A WinRT toast may already be torn down by the system.
                    // Detach is a best-effort cleanup path and must not crash
                    // the tray application during notification dismissal.
                }
                finally
                {
                    detached = true;
                    Toast = null;
                }
            }
        }

        private sealed class NotificationState
        {
            internal NotificationState(string tag)
            {
                Tag = tag;
            }

            internal string Tag { get; private set; }

            internal int MessageCount { get; private set; }

            internal void Update()
            {
                MessageCount++;
            }
        }
    }
}
