// Lightweight WeChat-start launcher generated by OpenAI Codex on 2026-07-20
// under the direction of the project owner.
//
// This helper is placed in the current-user Run key.  It does not start the
// notifier at Windows sign-in: it waits for Weixin.exe / WeChat.exe to appear,
// launches the notifier once, and then exits.  WMI delivers process-start
// events, so this helper does not poll the process list in a timer loop.

using System;
using System.Diagnostics;
using System.IO;
using System.Management;
using System.Threading;

namespace WeChatNotifierLauncher
{
    internal static class Program
    {
        private const string NotifierProcessMutex =
            "Local\\WeChatMessageNotifier.Singleton";
        private const string LauncherMutex =
            "Local\\WeChatMessageNotifier.StartAfterWeChat";
        private const int StartupSettleDelayMilliseconds = 800;
        private static int launchRequested;

        [STAThread]
        private static int Main(string[] args)
        {
            if (args != null && args.Length == 1 &&
                string.Equals(args[0], "--self-test", StringComparison.OrdinalIgnoreCase))
            {
                return RunSelfTest();
            }

            bool createdNew;
            using (var launcherMutex = new Mutex(true, LauncherMutex, out createdNew))
            {
                if (!createdNew)
                {
                    return 0;
                }

                using (var launched = new ManualResetEvent(false))
                using (var watcher = new ManagementEventWatcher(
                    new WqlEventQuery("SELECT * FROM Win32_ProcessStartTrace")))
                {
                    watcher.EventArrived += delegate(object sender, EventArrivedEventArgs eventArgs)
                    {
                        if (IsWeChatStartEvent(eventArgs))
                        {
                            LaunchNotifierAfterWeChatStarts(launched);
                        }
                    };

                    try
                    {
                        watcher.Start();
                    }
                    catch
                    {
                        // WMI can be unavailable on a damaged Windows setup.
                        // Do one final direct check, then exit rather than
                        // keeping a fallback polling process alive.
                        LaunchIfWeChatIsAlreadyRunning(launched);
                        return 0;
                    }

                    // Starting the watcher before this check closes the race
                    // where WeChat opens during Windows sign-in.
                    LaunchIfWeChatIsAlreadyRunning(launched);
                    launched.WaitOne();
                    watcher.Stop();
                }
            }

            return 0;
        }

        private static bool IsWeChatStartEvent(EventArrivedEventArgs eventArgs)
        {
            if (eventArgs == null || eventArgs.NewEvent == null)
            {
                return false;
            }

            var processName = eventArgs.NewEvent["ProcessName"] as string;
            return IsWeChatProcessName(processName);
        }

        private static bool IsWeChatProcessName(string processName)
        {
            return string.Equals(processName, "Weixin.exe", StringComparison.OrdinalIgnoreCase) ||
                   string.Equals(processName, "WeChat.exe", StringComparison.OrdinalIgnoreCase);
        }

        private static void LaunchIfWeChatIsAlreadyRunning(WaitHandle launched)
        {
            foreach (var processName in new[] { "Weixin", "WeChat" })
            {
                try
                {
                    var processes = Process.GetProcessesByName(processName);
                    foreach (var process in processes)
                    {
                        using (process)
                        {
                            LaunchNotifierAfterWeChatStarts(launched);
                            return;
                        }
                    }
                }
                catch
                {
                    // Best-effort discovery only.  The WMI event remains
                    // active and will launch the notifier on a future start.
                }
            }
        }

        private static void LaunchNotifierAfterWeChatStarts(WaitHandle launched)
        {
            if (launched.WaitOne(0) ||
                Interlocked.CompareExchange(ref launchRequested, 1, 0) != 0)
            {
                Signal(launched);
                return;
            }

            if (IsNotifierAlreadyRunning())
            {
                Signal(launched);
                return;
            }

            try
            {
                Thread.Sleep(StartupSettleDelayMilliseconds);
                if (!IsNotifierAlreadyRunning())
                {
                    var notifierPath = Path.Combine(
                        AppDomain.CurrentDomain.BaseDirectory,
                        "WeChatMessageNotifier.exe");
                    if (File.Exists(notifierPath))
                    {
                        Process.Start(new ProcessStartInfo
                        {
                            FileName = notifierPath,
                            WorkingDirectory = Path.GetDirectoryName(notifierPath),
                            UseShellExecute = false
                        });
                    }
                }
            }
            catch
            {
                // A failed launch must not surface a dialog during sign-in.
            }
            finally
            {
                Signal(launched);
            }
        }

        private static void Signal(WaitHandle launched)
        {
            var eventHandle = launched as EventWaitHandle;
            if (eventHandle != null)
            {
                eventHandle.Set();
            }
        }

        private static bool IsNotifierAlreadyRunning()
        {
            try
            {
                using (Mutex.OpenExisting(NotifierProcessMutex))
                {
                    return true;
                }
            }
            catch (WaitHandleCannotBeOpenedException)
            {
                return false;
            }
            catch (UnauthorizedAccessException)
            {
                // In the unlikely case that the mutex cannot be opened, do
                // not risk a second notifier process.
                return true;
            }
        }

        private static int RunSelfTest()
        {
            if (!IsWeChatProcessName("Weixin.exe") ||
                !IsWeChatProcessName("wechat.exe") ||
                IsWeChatProcessName("WeixinHelper.exe") ||
                IsWeChatProcessName(null))
            {
                Console.WriteLine("LAUNCHER SELF-TEST FAILED");
                return 1;
            }

            Console.WriteLine("LAUNCHER SELF-TEST PASSED");
            return 0;
        }
    }
}
