// Diagnostic probe initially generated by OpenAI Codex on 2026-06-29.
// It prints only structure, counts, lengths, and masked text shapes.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Automation;

namespace WeChatNotifier.Probe
{
    internal static class Program
    {
        private delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);

        [DllImport("user32.dll")]
        private static extern bool EnumWindows(EnumWindowsProc callback, IntPtr lParam);

        [DllImport("user32.dll")]
        private static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint processId);

        [DllImport("user32.dll")]
        private static extern bool IsWindowVisible(IntPtr hWnd);

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        private static extern int GetWindowText(IntPtr hWnd, StringBuilder text, int maxCount);

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        private static extern int GetClassName(IntPtr hWnd, StringBuilder className, int maxCount);

        private static int Main()
        {
            var processIds = new HashSet<uint>();
            foreach (var process in Process.GetProcessesByName("Weixin"))
            {
                processIds.Add((uint)process.Id);
            }

            if (processIds.Count == 0)
            {
                Console.WriteLine("Weixin is not running.");
                return 2;
            }

            var windows = new List<IntPtr>();
            EnumWindows(delegate(IntPtr hWnd, IntPtr ignored)
            {
                uint processId;
                GetWindowThreadProcessId(hWnd, out processId);
                if (processIds.Contains(processId))
                {
                    windows.Add(hWnd);
                }
                return true;
            }, IntPtr.Zero);

            Console.WriteLine("Top-level Weixin windows: " + windows.Count);
            foreach (var hWnd in windows)
            {
                ProbeWindow(hWnd);
            }

            return 0;
        }

        private static void ProbeWindow(IntPtr hWnd)
        {
            uint processId;
            GetWindowThreadProcessId(hWnd, out processId);

            var title = new StringBuilder(512);
            GetWindowText(hWnd, title, title.Capacity);
            var className = new StringBuilder(256);
            GetClassName(hWnd, className, className.Capacity);

            Console.WriteLine(
                "HWND=0x" + hWnd.ToInt64().ToString("X") +
                " PID=" + processId +
                " Visible=" + IsWindowVisible(hWnd) +
                " Class=" + className +
                " TitleLength=" + title.Length);

            try
            {
                var root = AutomationElement.FromHandle(hWnd);
                if (root == null)
                {
                    Console.WriteLine("  UIA root: unavailable");
                    return;
                }

                var descendants = root.FindAll(TreeScope.Descendants, Condition.TrueCondition);
                var named = 0;
                var textControls = 0;
                var controlTypes = new Dictionary<string, int>(StringComparer.Ordinal);

                foreach (AutomationElement element in descendants)
                {
                    string name = SafeString(delegate { return element.Current.Name; });
                    string type = SafeString(delegate { return element.Current.ControlType.ProgrammaticName; });
                    if (!string.IsNullOrWhiteSpace(name))
                    {
                        named++;
                    }
                    if (type == "ControlType.Text" || type == "ControlType.ListItem")
                    {
                        textControls++;
                    }
                    if (!controlTypes.ContainsKey(type))
                    {
                        controlTypes[type] = 0;
                    }
                    controlTypes[type]++;
                }

                Console.WriteLine(
                    "  UIA descendants=" + descendants.Count +
                    " named=" + named +
                    " textOrListItem=" + textControls);

                foreach (var item in controlTypes)
                {
                    Console.WriteLine("    " + item.Key + "=" + item.Value);
                }

                DumpLists(root);
            }
            catch (Exception exception)
            {
                Console.WriteLine("  UIA error: " + exception.GetType().Name + ": " + exception.Message);
            }
        }

        private static void DumpLists(AutomationElement root)
        {
            var lists = root.FindAll(
                TreeScope.Descendants,
                new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.List));

            for (var listIndex = 0; listIndex < lists.Count; listIndex++)
            {
                var list = lists[listIndex];
                var listRect = SafeRect(list);
                var items = list.FindAll(
                    TreeScope.Children,
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem));

                Console.WriteLine(
                    "  List[" + listIndex + "] rect=" + FormatRect(listRect) +
                    " childItems=" + items.Count);

                for (var itemIndex = 0; itemIndex < items.Count; itemIndex++)
                {
                    var item = items[itemIndex];
                    var itemRect = SafeRect(item);
                    var itemName = SafeString(delegate { return item.Current.Name; });
                    var children = item.FindAll(TreeScope.Children, Condition.TrueCondition);

                    Console.WriteLine(
                        "    Item[" + itemIndex + "] rect=" + FormatRect(itemRect) +
                        " nameLength=" + itemName.Length +
                        " nameLines=" + CountLines(itemName) +
                        " children=" + children.Count +
                        " invoke=" + Supports(item, InvokePattern.Pattern) +
                        " select=" + Supports(item, SelectionItemPattern.Pattern) +
                        " scroll=" + Supports(item, ScrollItemPattern.Pattern));

                    var lines = itemName.Replace("\r", string.Empty).Split('\n');
                    for (var lineIndex = 0; lineIndex < lines.Length; lineIndex++)
                    {
                        if (!string.IsNullOrWhiteSpace(lines[lineIndex]))
                        {
                            Console.WriteLine(
                                "      Line[" + lineIndex + "] length=" + lines[lineIndex].Length +
                                " shape=" + MaskContent(lines[lineIndex]));
                        }
                    }

                    for (var childIndex = 0; childIndex < children.Count; childIndex++)
                    {
                        var child = children[childIndex];
                        var childName = SafeString(delegate { return child.Current.Name; });
                        var childType = SafeString(delegate { return child.Current.ControlType.ProgrammaticName; });
                        Console.WriteLine(
                            "      Child[" + childIndex + "] type=" + childType +
                            " nameLength=" + childName.Length +
                            " nameLines=" + CountLines(childName) +
                            " rect=" + FormatRect(SafeRect(child)));
                    }
                }
            }
        }

        private static System.Windows.Rect SafeRect(AutomationElement element)
        {
            try
            {
                return element.Current.BoundingRectangle;
            }
            catch
            {
                return System.Windows.Rect.Empty;
            }
        }

        private static string FormatRect(System.Windows.Rect rect)
        {
            if (rect.IsEmpty)
            {
                return "empty";
            }

            return ((int)rect.X) + "," + ((int)rect.Y) + "," +
                   ((int)rect.Width) + "," + ((int)rect.Height);
        }

        private static int CountLines(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return 0;
            }

            var count = 1;
            foreach (var character in value)
            {
                if (character == '\n')
                {
                    count++;
                }
            }
            return count;
        }

        private static string MaskContent(string value)
        {
            var builder = new StringBuilder();
            foreach (var character in value)
            {
                if (character >= '\u4e00' && character <= '\u9fff')
                {
                    builder.Append('汉');
                }
                else if (char.IsLetter(character))
                {
                    builder.Append('A');
                }
                else if (char.IsDigit(character))
                {
                    builder.Append('0');
                }
                else if (char.IsWhiteSpace(character))
                {
                    builder.Append(' ');
                }
                else
                {
                    builder.Append(character);
                }
            }

            var masked = builder.ToString();
            return masked.Length <= 80 ? masked : masked.Substring(0, 80) + "...";
        }

        private static string SafeString(Func<string> getter)
        {
            try
            {
                return getter() ?? string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }

        private static bool Supports(
            AutomationElement element,
            AutomationPattern pattern)
        {
            object ignored;
            try
            {
                return element.TryGetCurrentPattern(pattern, out ignored);
            }
            catch
            {
                return false;
            }
        }
    }
}
