@echo off
rem Initial helper script generated by OpenAI Codex on 2026-06-29.
setlocal
set "APP=%~dp0WeChatMessageNotifier.exe"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$app=[System.IO.Path]::GetFullPath('%APP%'); New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'WeChatMessageNotifier' -PropertyType String -Value ('\"'+$app+'\"') -Force | Out-Null"
if errorlevel 1 (
  echo 设置自动启动失败。
  pause
  exit /b 1
)
echo 已设置为登录 Windows 后自动启动。
pause
