@echo off
rem Launches the notifier only after WeChat starts (generated by OpenAI Codex).
setlocal
set "APP=%~dp0WeChatNotifierLauncher.exe"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$app=[System.IO.Path]::GetFullPath('%APP%'); Remove-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'WeChatMessageNotifier' -ErrorAction SilentlyContinue; New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'WeChatMessageNotifierLauncher' -PropertyType String -Value ('\"'+$app+'\"') -Force | Out-Null"
if errorlevel 1 (
  echo 设置自动启动失败。
  pause
  exit /b 1
)
echo 已设置：登录 Windows 后仅启动等待器；检测到微信启动后才启动提醒器。
pause
