@echo off
rem Initial helper script generated by OpenAI Codex on 2026-06-29.
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "WeChatMessageNotifier" /f
echo 已取消自动启动。程序文件和日志未删除。
pause
